# Priority TDE Filter

This jupyter notebook contains python code for the production of:
- A Filtered TDE database
    - based upon early and late epoch designations

This module takes in:

1) 'TDE_List.tsv' file with columns: ['TDE Name','TDE Discovery Date','TDE Host Galaxy Name']

2) 'TDE_Output_Data.csv' file with observational information for each TDE.

The output returns list of indecies for priority TDE objects in 'priority_tde_indicies.txt'

In [1]:
import pandas as pd
import os

In [2]:
# Define Early and Late epochs
early_epoch = 100 # days
late_epoch = 3000 # days

In [3]:
# Get basic TDE info
tde_file_name = 'TDE_List.tsv'
# cwd = os.getcwd()

# print(cwd, '\n' ,tde_file_name)
print(tde_file_name)

TDE_List.tsv

In [4]:
### Read in tde list file and convert to pandas dataframe
tde_list = pd.read_csv(tde_file_name, sep='\t')

tde_list = tde_list[tde_list['Name'].notnull()]

# tde_dates = tde_list['Disc Date'].apply(pd.to_datetime)
tde_dates = tde_list['Disc Date']
tde_dates.head(120)
# tde_dates.head(30)

0      2010/07/14
1      2003/07/13
2      2006/09/01
3      2005/07/23
4      2000/08/23
          ...
111    2014/04/01
112    2005/07/15
113    2018/02/15
114    2006/08/22
115    2018/10/04
Name: Disc Date, Length: 116, dtype: object

In [5]:
# tde_dates = tde_dates['Disc'].head(102)
# tde_dates

In [6]:
# Add discovery dates to information previously created csv file. For determining dt's
# NOTE: this is not saved back to csv file.
xamin_files = pd.read_csv('TDE_Output_Data.csv')
xamin_files = pd.concat( (xamin_files, tde_dates), axis='columns')
xamin_files.head(50)
# xamin_files['XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])'].loc['']
# xamin_files.to_clipboard()

,TDE,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])","XMM TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","XMM Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","XMM Col D ObsID (exp time, date, #days after discovery)","Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)","Chandra TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","Chandra Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","Chandra Col H ObsID (exp time, date, #days after discovery)","Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])","Swift TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","Swift Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","Swift Col L ObsID (exp time, date, #days after discovery)",Disc Date
0,2MASX J01190869-3411305,"10: 0657820101 (2010-12-02, 14913.0), 07409601...","10, 0.0039, 0.017",9.0,"0657820101 (14913.0, 2010-12-02, 154), 0740960...","1: 22096 (2019-02-14, 73570.0, ACIS-S ),","1, 0.0167, 0.0167",1.0,"22096 (73570.0, 2019-02-14, 3150),","32: 00031789003 (2010-08-27, 2073.517), 000317...","32, 0.4007, 24.6643",26.0,"00031789003 (2073.517, 2010-08-27, 57), 000317...",2010/07/14
1,2XMM J123103.2+110648,"5: 0145800101 (2003-07-13, 107002.0), 03066301...","5, 6.9949, 6.9949",5.0,"0145800101 (107002.0, 2003-07-13, 0), 03066301...","1: 17129 (2016-02-10, 40060.0, ACIS-S ),","1, 0.0142, 0.0142",1.0,"17129 (40060.0, 2016-02-10, 4595),","11: 00032732009 (2014-05-13, 2494.821), 000327...","11, 0.8804, 4.3878",11.0,"00032732001 (8465.981, 2013-03-08, 3526), 0003...",2003/07/13
2,2XMMi J184725.1-631724,"3: 0405550401 (2006-09-06, 28262.0), 069461010...","3, 0.0014, 8.2767",3.0,"0405550401 (28262.0, 2006-09-06, 5), 040538050...","1: 15637 (2013-03-29, 15070.0, ACIS-S ),","1, 0.0046, 0.0046",1.0,"15637 (15070.0, 2013-03-29, 2401),","9: 07021936001 (2019-10-01, 72.702), 000319300...","9, 0.6353, 17.342",6.0,"00031930001 (4992.027, 2011-02-23, 1636), 0003...",2006/09/01
3,3XMM J150052.0+015452,"11: 0302460101 (2005-07-23, 36708.0), 05546805...","11, 0.0066, 13.6524",9.0,"0302460101 (36708.0, 2005-07-23, 0), 055468020...","12: 9517 (2008-06-05, 100060.0, ACIS-S ), 5...","11, 0.0227, 19.5223",11.0,"9517 (100060.0, 2008-06-05, 1048), 11324 (635...","62: 03107787002 (2019-04-07, 95.34), 031077870...","62, 0.9842, 23.5488",51.0,"00032250001 (2022.336, 2012-01-14, 2366), 0003...",2005/07/23
4,3XMM J152130.7+074916,"3: 0109930101 (2000-08-22, 55413.0), 010993020...","2, 8.6033, 9.1633",2.0,"0109930201 (6121.0, 2000-08-23, 0), 0723801501...","1: 900 (2000-04-03, 58030.0, ACIS-I ),","0, 8.5391, 8.5391",0.0,NaN,"2: 00035189001 (2005-09-10, 9555.588), 0001036...","2, 3.2383, 6.2276",2.0,"00035189001 (9555.588, 2005-09-10, 1844), 0001...",2000/08/23
5,3XMM J215022.4-055108,"4: 0823360101 (2018-05-24, 60000.0), 060359010...","4, 0.003, 7.0071",3.0,"0404190101 (56713.0, 2006-05-05, 369), 0603590...","2: 17862 (2016-09-14, 78120.0, ACIS-S ), 679...","2, 0.0016, 8.3798",2.0,"6791 (101880.0, 2006-09-28, 515), 17862 (7812...","2: 00033396001 (2014-09-05, 5934.494), 0003339...","2, 2.3606, 3.9747",2.0,"00033396001 (5934.494, 2014-09-05, 3414), 0003...",2005/05/01
6,ASASSN-14ae,"3: 0694651001 (2014-05-15, 23499.0), 069465110...","3, 0.0286, 0.0286",3.0,"0694651001 (23499.0, 2014-05-15, 110), 0694651...","1: 21503 (2018-11-17, 10060.0, ACIS-S ),","1, 0.0301, 0.0301",1.0,"21503 (10060.0, 2018-11-17, 1757),","30: 00033130007 (2014-03-18, 471.367), 0003313...","30, 0.2147, 4.4033",24.0,"00033130001 (2986.154, 2014-01-27, 2), 0003313...",2014/01/25
7,ASASSN-14li,"13: 0694651201 (2014-12-06, 23000.0), 06946514...","13, 0.001, 0.0094",13.0,"0694651201 (23000.0, 2014-12-06, 14), 07224802...","7: 17566 (2014-12-08, 35040.0, HRC-S ), 1756...","7, 0.0077, 0.0089",7.0,"17566 (35040.0, 2014-12-08, 16), 17567 (44790....","131: 00094094009 (2018-04-16, 1597.154), 00094...","131, 0.2215, 11.1812",98.0,"00033539001 (2963.692, 2014-11-30, 8), 0003353...",2014/11/22
8,ASASSN-15lh,"2: 0770581201 (2015-11-18, 13000.0), 080228010...","2, 0.0018, 0.0026",2.0,"0770581201 (13000.0, 2015-11-18, 157), 0802280...","4: 17879 (2015-11-12, 10040.0, ACIS-S ), 1788...","4, 0.0008, 0.0008",4.0,"17879 (10040.0, 2015-11-12, 151), 17880 (10060...","153: 00033886021 (2016-04-09, 1078.609), 00033...","152, 0.0585, 22.9594",125.0,"00033830001 (2515.795, 2015-06-24, 10), 000338...",2015/06/14
9,ASASSN-15oi,"2: 0722160501 (2015-10-29, 17200.0), 072216070...","2, 0.0174, 0.0174",2.0,"0722160501 (17200.0, 2015-10-29, 76), 07221607...",NaN,NaN,NaN,NaN,"59: 00095141005 (2019-07-06, 1807.381), 000951...","59, 0.391, 24.6185",49.0,"00033999002 (2497.26, 2015-08-25, 11), 0003399...",2015/08/14
10,ASASSN-20il,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"13: 00010296002 (2017-09-21, 1028.172), 031047...","0, 0.468, 16.7334",0.0,NaN,2020/07/08
11,AT2016ezh,"1: 0303110101 (2005-07-14, 13109.0),","0, 11.9775, 11.9775",0.0,NaN,"5: 16273 (2014-11-27, 6070.0, ACIS-I ), 7750...","3, 0.0132, 20.0288",3.0,"21460 (10060.0, 2019-01-10, 867), 21461 (10060...","83: 00034704007 (2016-09-22, 1901.209), 000347...","83, 0.1576, 5.592",70.0,"00034704001 (1980.774, 2016-09-01, 6), 0003470...",2016/08/26
12,AT2017eqx,"1: 0762470201 (2015-05-20, 28400.0),","0, 5.2827, 5.2827",0.0,NaN,"4: 20625 (2017-08-16, 10060.0, ACIS-S ), 2143...","2, 0.0075, 16.7853",2.0,"20625 (10060.0, 2017-08-16, 70), 21437 (10110....","18: 00010197006 (2017-08-08, 732.237), 0001019...","17, 0.6117, 22.8757",10.0,"00010197001 (1989.627, 2017-07-11, 34), 000101...",2017/06/07
13,AT2018fyk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/09/08
14,AT2018zr,"3: 0822040301 (2018-04-11, 21000.0), 082204040...","3, 0.0025, 0.0025",3.0,"0822040301 (21000.0, 2018-04-11, 36), 08220405...",NaN,NaN,NaN,NaN,"45: 00095142009 (2019-12-18, 2415.476), 000951...","45, 0.0559, 5.7463",40.0,"00010641003 (2941.056, 2018-03-27, 21), 000106...",2018/03/06
15,AT2019azh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019/02/22
16,AT2019dsg,"2: 0842590901 (2019-05-30, 39999.0), 084259190...","2, 0.0085, 0.0085",2.0,"0842590901 (39999.0, 2019-05-30, 51), 08425919...",NaN,NaN,NaN,NaN,"34: 00011396011 (2019-06-14, 908.154), 0001139...","34, 0.6233, 6.444",17.0,"00011396001 (1965.13, 2019-05-17, 38), 0001139...",2019/04/09
17,AT2020ocn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020/04/29
18,CSS100217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"13: 00049878002 (2020-02-28, 1652.021), 000316...","13, 0.7171, 3.894",6.0,"00031681001 (3518.125, 2010-04-06, 2653), 0003...",2002/12/31
19,CXOU J0332,"49: 0827220901 (2019-08-06, 35300.0), 06049609...","1, 3.22, 14.6699",1.0,"0827220901 (35300.0, 2019-08-06, 1770),","100: 5022 (2004-11-15, 80170.0, ACIS-I ), 6...","39, 3.7743, 12.3711",38.0,"16454 (47760.0, 2014-10-01, 0), 16176 (25000.0...","100: 00032648001 (2012-12-18, 1266.717), 00032...","13, 2.1342, 23.9986",10.0,"00033467001 (4989.526, 2014-10-05, 4), 0003346...",2014/10/01
20,D1-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004/06/22
21,D23H-1,"2: 0652401401 (2010-12-29, 39119.0), 065240300...","2, 9.6501, 9.6501",1.0,"0652401401 (39119.0, 2010-12-29, 1212),","8: 8609 (2008-08-06, 8960.0, ACIS-I ), 8614...","8, 0.0083, 20.1828",5.0,"7867 (22140.0, 2007-10-01, 27), 9719 (8150.0...",NaN,NaN,NaN,NaN,2007/09/04
22,D3-13,NaN,NaN,NaN,NaN,"69: 9458 (2009-03-18, 6740.0, ACIS-I ), 945...","69, 1.7975, 19.3786",67.0,"5845 (49040.0, 2005-03-24, 434), 5846 (50050...","12: 00080737001 (2014-05-16, 1923.108), 000807...","12, 1.3857, 22.5491",9.0,"00080737001 (1923.108, 2014-05-16, 3774), 0008...",2004/01/15
23,DES14C1kia,"2: 0722160401 (2015-02-26, 15000.0), 072216030...","2, 0.0006, 0.0163",2.0,"0722160301 (18000.0, 2015-01-12, 62), 07221604...","1: 21439 (2019-03-09, 10800.0, ACIS-S ),","1, 0.0024, 0.0024",1.0,"21439 (10800.0, 2019-03-09, 1579),","21: 00033565005 (2015-02-04, 2444.2), 00033565...","21, 1.053, 14.3635",18.0,"00033565001 (1986.34, 2015-01-06, 56), 0003356...",2014/11/11
24,Dougie,"2: 0655800101 (2010-05-07, 25655.0), 065580050...","2, 12.8946, 12.8946",2.0,"0655800101 (25655.0, 2010-05-07, 475), 0655800...","1: 1578 (2001-04-03, 15000.0, ACIS-S ),","0, 19.3024, 19.3024",0.0,NaN,"13: 03107573001 (2018-10-03, 584.195), 0003133...","13, 0.0423, 17.5111",8.0,"00031338001 (3985.823, 2009-01-28, 11), 000313...",2009/01/17
25,F01004-2237,"1: 0605880101 (2009-12-08, 34515.0),","0, 0.0044, 0.0044",0.0,NaN,"12: 20786 (2018-10-01, 22540.0, ACIS-I ), 218...","11, 0.025, 19.3355",11.0,"12179 (51770.0, 2010-09-03, 70), 13391 (47050....",NaN,NaN,NaN,NaN,2010/06/25
26,Gaia16aax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016/01/26
27,Gaia16ajq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016/03/29
28,Gaia16aka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016/03/31
29,IGR J17361-4441,"2: 0146420101 (2003-03-21, 48918.0), 067938030...","1, 0.0373, 0.7527",1.0,"0679380301 (42517.0, 2011-09-23, 3107),","2: 12453 (2011-08-29, 2550.0, ACIS-S ), 5505...","2, 0.022, 0.0848",2.0,"5505 (45160.0, 2005-04-21, 761), 12453 (2550....","56: 00091446003 (2012-06-16, 983.05), 00091446...","56, 0.0954, 5.4097",40.0,"00090434001 (1845.347, 2010-05-11, 2607), 0003...",2003/03/22
30,iPTF16axa,NaN,NaN,NaN,NaN,"1: 21436 (2018-11-30, 10110.0, ACIS-S ),","1, 0.0101, 0.0101",1.0,"21436 (10110.0, 2018-11-30, 915),","16: 00034572008 (2016-07-16, 717.081), 0003457...","14, 0.7725, 24.628",10.0,"00034572002 (2011.301, 2016-06-12, 14), 000345...",2016/05/29
31,iPTF16fnl,NaN,NaN,NaN,NaN,"1: 21435 (2019-05-29, 10110.0, ACIS-S ),","1, 0.0097, 0.0097",1.0,"21435 (10110.0, 2019-05-29, 1006),","36: 00034706002 (2016-09-05, 1877.956), 000347...","36, 0.0726, 4.9988",32.0,"00034706001 (1985.569, 2016-08-30, 4), 0003470...",2016/08/26
32,J030257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/11/08
33,J091225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/02/09
34,J094608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,J094806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,J100933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/02/20
37,J113527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/07
38,J121116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/05/04
39,J123715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010/01/23
40,J130819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/14
41,J133737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/12
42,J133837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/11/02
43,J134244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/06
44,J141036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/24
45,J142401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/26
46,J145851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009/04/29
47,J155223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"8: 00057002007 (2014-07-11, 458.205), 00057002...","7, 22.3352, 24.9062",0.0,NaN,2009/05/31
48,J233454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,LEDA 095953,"1: 0086950201 (2002-07-29, 33642.0),","1, 2.9435, 2.9435",1.0,"0086950201 (33642.0, 2002-07-29, 4041),","1: 4203 (2003-07-31, 34440.0, ACIS-S ),","1, 3.7923, 3.7923",1.0,"4203 (34440.0, 2003-07-31, 4408),",NaN,NaN,NaN,NaN,1991/07/06

# Filtering Data

# XMM Data

In [7]:
xmm = pd.DataFrame(xamin_files['XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])'])
xmm = pd.concat( (xmm, xamin_files['Disc Date'], xamin_files['TDE']), axis='columns')
xmm[f'xmm_within_{late_epoch}_days'] = None
xmm[f'xmm_within_{early_epoch}_days'] = None
xmm['xmm_neg_delta_days?'] = None
xmm['xmm_min_dt'] = None
xmm[f'xmm_num_dt_within_{late_epoch}'] = None
xmm[f'xmm_num_dt_within_{early_epoch}'] = None
xmm

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100
0,"10: 0657820101 (2010-12-02, 14913.0), 07409601...",2010/07/14,2MASX J01190869-3411305,None,None,None,None,None,None
1,"5: 0145800101 (2003-07-13, 107002.0), 03066301...",2003/07/13,2XMM J123103.2+110648,None,None,None,None,None,None
2,"3: 0405550401 (2006-09-06, 28262.0), 069461010...",2006/09/01,2XMMi J184725.1-631724,None,None,None,None,None,None
3,"11: 0302460101 (2005-07-23, 36708.0), 05546805...",2005/07/23,3XMM J150052.0+015452,None,None,None,None,None,None
4,"3: 0109930101 (2000-08-22, 55413.0), 010993020...",2000/08/23,3XMM J152130.7+074916,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
111,"4: 0740340301 (2014-04-29, 17340.0), 074034040...",2014/04/01,XMMSL1 J0740-85,None,None,None,None,None,None
112,"1: 0721830301 (2013-12-21, 8600.0),",2005/07/15,XMMSL1 J131952.3+225958,None,None,None,None,None,None
113,"2: 0804860201 (2018-07-17, 34300.0), 080486030...",2018/02/15,XMMSL2 J140446.9-251135,None,None,None,None,None,None
114,"5: 0763640201 (2016-09-08, 11600.0), 076364040...",2006/08/22,XMMSL2 J144605.0+685735,None,None,None,None,None,None
115,"1: 0822040901 (2018-12-27, 21000.0),",2018/10/04,ZTF18abxftqm,None,None,None,None,None,None

In [8]:
for index, row in xmm.iterrows():
    print("Database index: ",index + 2)
    df_row = pd.DataFrame(row)
#     print(df_row)
    tde = xmm['TDE'][index]
    df_row_disc_date = df_row.to_string().split('\n')[2].split()[1]
#     print(df_row_disc_date, type(df_row_disc_date))
    df_row = df_row.to_string().split(')')[1:]
    # print(df_row)

    xmm_within_late_epoch = False
    xmm_within_early_epoch = False
    xmm_neg_delta_days = False
    xmm_diff_time_list = []
    xmm_diff_supedd_time_list = []

    for i, line in enumerate(df_row):
#         if i == 0:
#             print("Num of Obs Ids: ",line.split(':')[0])
#             print('-'*20)
        if i < len(df_row) - 1:
            if i == 0:
                line = line.split(':')[1].split(' ')[1:]
                # print(line)
                # print("exp time = ", line[2])
                exp_time = float(line[2])
            if i > 0:
                line = line.split(':')[0].split(' ')[1:]
                # print(line)
                # print("exp time = ", line[2])
                exp_time = float(line[2])
            for j, element in enumerate(line):
                element = element.strip('(').strip(',')
                # print(element)

                if j==1 and exp_time>1e3:  # getting the obervation date for all >1 ksec exposures
                    element = pd.to_datetime(element)
#                     print("obs date",element)
#                     print(type(element))
#                     print(element.year)
#                     disc_date = pd.to_datetime('1950-12-01')
#                     disc_date = pd.to_datetime(xmm['Disc Date'][index].split('?')[0])
                    disc_date = pd.to_datetime(xmm['Disc Date'][index])
#                     print("disc date",disc_date)
                    diff_time = element - disc_date
                    diff_time = diff_time.days
                    print(diff_time)
        
                    if 0 <= diff_time <= late_epoch:
                        print(f"YES, Obs within {late_epoch} days: ", diff_time)
                        print(tde)
                        xmm_within_late_epoch = True
#                         xmm_within_late_epoch = diff_time
                        xmm_diff_time_list.append(diff_time)
    
                        if 0 <= diff_time <= early_epoch:
                            print(f"YES, Obs within {early_epoch} days: ", diff_time)
                            print(tde)
                            xmm_within_early_epoch = True
    #                         xmm_within_early_epoch = diff_time
                            xmm_diff_supedd_time_list.append(diff_time)
                        
                    if diff_time < 0:
                        print("ERROR negative delta days. CHECK DISC DATE!!!", diff_time)
                        print(tde)
                        xmm_neg_delta_days = True
    
    if xmm_within_late_epoch == True:
        xmm[f'xmm_within_{late_epoch}_days'][index] = True
        xmm['xmm_min_dt'][index] = min(xmm_diff_time_list)
        xmm[f'xmm_num_dt_within_{late_epoch}'][index] = len(xmm_diff_time_list)
        if xmm_within_early_epoch == True:
            xmm[f'xmm_within_{early_epoch}_days'][index] = True
            xmm['xmm_min_dt'][index] = min(xmm_diff_supedd_time_list)
            xmm[f'xmm_num_dt_within_{early_epoch}'][index] = len(xmm_diff_supedd_time_list)
        else:
            xmm[f'xmm_within_{early_epoch}_days'][index] = False
    else:
        xmm[f'xmm_within_{late_epoch}_days'][index] = False


    if xmm_neg_delta_days == True:
        xmm['xmm_neg_delta_days?'][index] = True
    else:
        xmm['xmm_neg_delta_days?'][index] = False
                    
#             print('\n')
# #         print('.'*40)
    print('='*40)

Database index:  2
141
YES, Obs within 3000 days:  141
2MASX J01190869-3411305
1605
YES, Obs within 3000 days:  1605
2MASX J01190869-3411305
3085
3108
3243
3467
3606
3612
3622
3622
========================================
Database index:  3
0
YES, Obs within 3000 days:  0
2XMM J123103.2+110648
YES, Obs within 100 days:  0
2XMM J123103.2+110648
884
YES, Obs within 3000 days:  884
2XMM J123103.2+110648
888
YES, Obs within 3000 days:  888
2XMM J123103.2+110648
885
YES, Obs within 3000 days:  885
2XMM J123103.2+110648
889
YES, Obs within 3000 days:  889
2XMM J123103.2+110648
========================================
Database index:  4
5
YES, Obs within 3000 days:  5
2XMMi J184725.1-631724
YES, Obs within 100 days:  5
2XMMi J184725.1-631724
2375
YES, Obs within 3000 days:  2375
2XMMi J184725.1-631724
227
YES, Obs within 3000 days:  227
2XMMi J184725.1-631724
========================================
Database index:  5
0
YES, Obs within 3000 days:  0
3XMM J150052.0+015452
YES, Obs within 100 days:  0
3XMM J150052.0+015452
1305
YES, Obs within 3000 days:  1305
3XMM J150052.0+015452
1299
YES, Obs within 3000 days:  1299
3XMM J150052.0+015452
1305
YES, Obs within 3000 days:  1305
3XMM J150052.0+015452
1299
YES, Obs within 3000 days:  1299
3XMM J150052.0+015452
4564
4400
4381
6025
6042
5326
========================================
Database index:  6
-1
ERROR negative delta days. CHECK DISC DATE!!! -1
3XMM J152130.7+074916
0
YES, Obs within 3000 days:  0
3XMM J152130.7+074916
YES, Obs within 100 days:  0
3XMM J152130.7+074916
4897
========================================
Database index:  7
4771
1498
YES, Obs within 3000 days:  1498
3XMM J215022.4-055108
369
YES, Obs within 3000 days:  369
3XMM J215022.4-055108
369
YES, Obs within 3000 days:  369
3XMM J215022.4-055108
========================================
Database index:  8
110
YES, Obs within 3000 days:  110
ASASSN-14ae
139
YES, Obs within 3000 days:  139
ASASSN-14ae
469
YES, Obs within 3000 days:  469
ASASSN-14ae
========================================
Database index:  9
14
YES, Obs within 3000 days:  14
ASASSN-14li
YES, Obs within 100 days:  14
ASASSN-14li
40
YES, Obs within 3000 days:  40
ASASSN-14li
YES, Obs within 100 days:  40
ASASSN-14li
230
YES, Obs within 3000 days:  230
ASASSN-14li
16
YES, Obs within 3000 days:  16
ASASSN-14li
YES, Obs within 100 days:  16
ASASSN-14li
383
YES, Obs within 3000 days:  383
ASASSN-14li
416
YES, Obs within 3000 days:  416
ASASSN-14li
560
YES, Obs within 3000 days:  560
ASASSN-14li
743
YES, Obs within 3000 days:  743
ASASSN-14li
929
YES, Obs within 3000 days:  929
ASASSN-14li
1109
YES, Obs within 3000 days:  1109
ASASSN-14li
1321
YES, Obs within 3000 days:  1321
ASASSN-14li
1479
YES, Obs within 3000 days:  1479
ASASSN-14li
1657
YES, Obs within 3000 days:  1657
ASASSN-14li
========================================
Database index:  10
157
YES, Obs within 3000 days:  157
ASASSN-15lh
1033
YES, Obs within 3000 days:  1033
ASASSN-15lh
========================================
Database index:  11
76
YES, Obs within 3000 days:  76
ASASSN-15oi
YES, Obs within 100 days:  76
ASASSN-15oi
234
YES, Obs within 3000 days:  234
ASASSN-15oi
========================================
Database index:  12
========================================
Database index:  13
-4061
ERROR negative delta days. CHECK DISC DATE!!! -4061
AT2016ezh
========================================
Database index:  14
-749
ERROR negative delta days. CHECK DISC DATE!!! -749
AT2017eqx
========================================
Database index:  15
========================================
Database index:  16
36
YES, Obs within 3000 days:  36
AT2018zr
YES, Obs within 100 days:  36
AT2018zr
385
YES, Obs within 3000 days:  385
AT2018zr
58
YES, Obs within 3000 days:  58
AT2018zr
YES, Obs within 100 days:  58
AT2018zr
========================================
Database index:  17
========================================
Database index:  18
51
YES, Obs within 3000 days:  51
AT2019dsg
YES, Obs within 100 days:  51
AT2019dsg
197
YES, Obs within 3000 days:  197
AT2019dsg
========================================
Database index:  19
========================================
Database index:  20
========================================
Database index:  21
1770
YES, Obs within 3000 days:  1770
CXOU J0332
-1693
ERROR negative delta days. CHECK DISC DATE!!! -1693
CXOU J0332
-1699
ERROR negative delta days. CHECK DISC DATE!!! -1699
CXOU J0332
-2078
ERROR negative delta days. CHECK DISC DATE!!! -2078
CXOU J0332
-2078
ERROR negative delta days. CHECK DISC DATE!!! -2078
CXOU J0332
-2076
ERROR negative delta days. CHECK DISC DATE!!! -2076
CXOU J0332
-2076
ERROR negative delta days. CHECK DISC DATE!!! -2076
CXOU J0332
-2088
ERROR negative delta days. CHECK DISC DATE!!! -2088
CXOU J0332
-2088
ERROR negative delta days. CHECK DISC DATE!!! -2088
CXOU J0332
-1691
ERROR negative delta days. CHECK DISC DATE!!! -1691
CXOU J0332
-2082
ERROR negative delta days. CHECK DISC DATE!!! -2082
CXOU J0332
-1687
ERROR negative delta days. CHECK DISC DATE!!! -1687
CXOU J0332
-2082
ERROR negative delta days. CHECK DISC DATE!!! -2082
CXOU J0332
-2090
ERROR negative delta days. CHECK DISC DATE!!! -2090
CXOU J0332
-1709
ERROR negative delta days. CHECK DISC DATE!!! -1709
CXOU J0332
-2090
ERROR negative delta days. CHECK DISC DATE!!! -2090
CXOU J0332
-2084
ERROR negative delta days. CHECK DISC DATE!!! -2084
CXOU J0332
-1723
ERROR negative delta days. CHECK DISC DATE!!! -1723
CXOU J0332
-2084
ERROR negative delta days. CHECK DISC DATE!!! -2084
CXOU J0332
-2094
ERROR negative delta days. CHECK DISC DATE!!! -2094
CXOU J0332
-1716
ERROR negative delta days. CHECK DISC DATE!!! -1716
CXOU J0332
-1717
ERROR negative delta days. CHECK DISC DATE!!! -1717
CXOU J0332
-2094
ERROR negative delta days. CHECK DISC DATE!!! -2094
CXOU J0332
-1727
ERROR negative delta days. CHECK DISC DATE!!! -1727
CXOU J0332
-1731
ERROR negative delta days. CHECK DISC DATE!!! -1731
CXOU J0332
-4644
ERROR negative delta days. CHECK DISC DATE!!! -4644
CXOU J0332
-4643
ERROR negative delta days. CHECK DISC DATE!!! -4643
CXOU J0332
-4643
ERROR negative delta days. CHECK DISC DATE!!! -4643
CXOU J0332
-4814
ERROR negative delta days. CHECK DISC DATE!!! -4814
CXOU J0332
-4641
ERROR negative delta days. CHECK DISC DATE!!! -4641
CXOU J0332
-4641
ERROR negative delta days. CHECK DISC DATE!!! -4641
CXOU J0332
-4637
ERROR negative delta days. CHECK DISC DATE!!! -4637
CXOU J0332
-4637
ERROR negative delta days. CHECK DISC DATE!!! -4637
CXOU J0332
-4814
ERROR negative delta days. CHECK DISC DATE!!! -4814
CXOU J0332
-4814
ERROR negative delta days. CHECK DISC DATE!!! -4814
CXOU J0332
-4634
ERROR negative delta days. CHECK DISC DATE!!! -4634
CXOU J0332
-4640
ERROR negative delta days. CHECK DISC DATE!!! -4640
CXOU J0332
-1914
ERROR negative delta days. CHECK DISC DATE!!! -1914
CXOU J0332
-1890
ERROR negative delta days. CHECK DISC DATE!!! -1890
CXOU J0332
-1902
ERROR negative delta days. CHECK DISC DATE!!! -1902
CXOU J0332
-2275
ERROR negative delta days. CHECK DISC DATE!!! -2275
CXOU J0332
-2274
ERROR negative delta days. CHECK DISC DATE!!! -2274
CXOU J0332
-2276
ERROR negative delta days. CHECK DISC DATE!!! -2276
CXOU J0332
-1892
ERROR negative delta days. CHECK DISC DATE!!! -1892
CXOU J0332
-2277
ERROR negative delta days. CHECK DISC DATE!!! -2277
CXOU J0332
-2272
ERROR negative delta days. CHECK DISC DATE!!! -2272
CXOU J0332
-2273
ERROR negative delta days. CHECK DISC DATE!!! -2273
CXOU J0332
-2278
ERROR negative delta days. CHECK DISC DATE!!! -2278
CXOU J0332
-2279
ERROR negative delta days. CHECK DISC DATE!!! -2279
CXOU J0332
========================================
Database index:  22
========================================
Database index:  23
1212
YES, Obs within 3000 days:  1212
D23H-1
1212
YES, Obs within 3000 days:  1212
D23H-1
========================================
Database index:  24
========================================
Database index:  25
107
YES, Obs within 3000 days:  107
DES14C1kia
62
YES, Obs within 3000 days:  62
DES14C1kia
YES, Obs within 100 days:  62
DES14C1kia
========================================
Database index:  26
475
YES, Obs within 3000 days:  475
Dougie
663
YES, Obs within 3000 days:  663
Dougie
========================================
Database index:  27
-199
ERROR negative delta days. CHECK DISC DATE!!! -199
F01004-2237
========================================
Database index:  28
========================================
Database index:  29
========================================
Database index:  30
========================================
Database index:  31
-1
ERROR negative delta days. CHECK DISC DATE!!! -1
IGR J17361-4441
3107
========================================
Database index:  32
========================================
Database index:  33
========================================
Database index:  34
========================================
Database index:  35
========================================
Database index:  36
========================================
Database index:  37
========================================
Database index:  38
========================================
Database index:  39
========================================
Database index:  40
========================================
Database index:  41
========================================
Database index:  42
========================================
Database index:  43
========================================
Database index:  44
========================================
Database index:  45
========================================
Database index:  46
========================================
Database index:  47
========================================
Database index:  48
========================================
Database index:  49
========================================
Database index:  50
========================================
Database index:  51
4041
========================================
Database index:  52
14
YES, Obs within 3000 days:  14
MAXI J1807+132
YES, Obs within 100 days:  14
MAXI J1807+132
15
YES, Obs within 3000 days:  15
MAXI J1807+132
YES, Obs within 100 days:  15
MAXI J1807+132
========================================
Database index:  53
-1647
ERROR negative delta days. CHECK DISC DATE!!! -1647
NGC 247
0
YES, Obs within 3000 days:  0
NGC 247
YES, Obs within 100 days:  0
NGC 247
1981
YES, Obs within 3000 days:  1981
NGC 247
1987
YES, Obs within 3000 days:  1987
NGC 247
2009
YES, Obs within 3000 days:  2009
NGC 247
2011
YES, Obs within 3000 days:  2011
NGC 247
2013
YES, Obs within 3000 days:  2013
NGC 247
2015
YES, Obs within 3000 days:  2015
NGC 247
2017
YES, Obs within 3000 days:  2017
NGC 247
2021
YES, Obs within 3000 days:  2021
NGC 247
-4741
ERROR negative delta days. CHECK DISC DATE!!! -4741
NGC 247
========================================
Database index:  54
1488
YES, Obs within 3000 days:  1488
NGC 3599
2381
YES, Obs within 3000 days:  2381
NGC 3599
========================================
Database index:  55
8802
========================================
Database index:  56
========================================
Database index:  57
175
YES, Obs within 3000 days:  175
OGLE16aaa
349
YES, Obs within 3000 days:  349
OGLE16aaa
========================================
Database index:  58
========================================
Database index:  59
========================================
Database index:  60
-1277
ERROR negative delta days. CHECK DISC DATE!!! -1277
PGC 1127938
========================================
Database index:  61
========================================
Database index:  62
========================================
Database index:  63
========================================
Database index:  64
========================================
Database index:  65
3200
========================================
Database index:  66
========================================
Database index:  67
========================================
Database index:  68
========================================
Database index:  69
-1919
ERROR negative delta days. CHECK DISC DATE!!! -1919
PS1-13jw
========================================
Database index:  70
========================================
Database index:  71
========================================
Database index:  72
========================================
Database index:  73
========================================
Database index:  74
========================================
Database index:  75
========================================
Database index:  76
6956
========================================
Database index:  77
3263
========================================
Database index:  78
9337
========================================
Database index:  79
========================================
Database index:  80
0
YES, Obs within 3000 days:  0
SDSSJ0159
YES, Obs within 100 days:  0
SDSSJ0159
========================================
Database index:  81
========================================
Database index:  82
========================================
Database index:  83
12
YES, Obs within 3000 days:  12
SDSSJ1201+30
YES, Obs within 100 days:  12
SDSSJ1201+30
165
YES, Obs within 3000 days:  165
SDSSJ1201+30
195
YES, Obs within 3000 days:  195
SDSSJ1201+30
========================================
Database index:  84
-796
ERROR negative delta days. CHECK DISC DATE!!! -796
SDSSJ1311
3237
========================================
Database index:  85
956
YES, Obs within 3000 days:  956
SDSSJ1323
========================================
Database index:  86
3888
========================================
Database index:  87
========================================
Database index:  88
========================================
Database index:  89
========================================
Database index:  90
========================================
Database index:  91
========================================
Database index:  92
========================================
Database index:  93
========================================
Database index:  94
========================================
Database index:  95
========================================
Database index:  96
========================================
Database index:  97
========================================
Database index:  98
========================================
Database index:  99
========================================
Database index:  100
========================================
Database index:  101
========================================
Database index:  102
========================================
Database index:  103
18
YES, Obs within 3000 days:  18
Swift J1644+57
YES, Obs within 100 days:  18
Swift J1644+57
32
YES, Obs within 3000 days:  32
Swift J1644+57
YES, Obs within 100 days:  32
Swift J1644+57
48
YES, Obs within 3000 days:  48
Swift J1644+57
YES, Obs within 100 days:  48
Swift J1644+57
62
YES, Obs within 3000 days:  62
Swift J1644+57
YES, Obs within 100 days:  62
Swift J1644+57
96
YES, Obs within 3000 days:  96
Swift J1644+57
YES, Obs within 100 days:  96
Swift J1644+57
108
YES, Obs within 3000 days:  108
Swift J1644+57
120
YES, Obs within 3000 days:  120
Swift J1644+57
138
YES, Obs within 3000 days:  138
Swift J1644+57
151
YES, Obs within 3000 days:  151
Swift J1644+57
161
YES, Obs within 3000 days:  161
Swift J1644+57
175
YES, Obs within 3000 days:  175
Swift J1644+57
187
YES, Obs within 3000 days:  187
Swift J1644+57
2030
YES, Obs within 3000 days:  2030
Swift J1644+57
2
YES, Obs within 3000 days:  2
Swift J1644+57
YES, Obs within 100 days:  2
Swift J1644+57
2
YES, Obs within 3000 days:  2
Swift J1644+57
YES, Obs within 100 days:  2
Swift J1644+57
841
YES, Obs within 3000 days:  841
Swift J1644+57
2537
YES, Obs within 3000 days:  2537
Swift J1644+57
548
YES, Obs within 3000 days:  548
Swift J1644+57
556
YES, Obs within 3000 days:  556
Swift J1644+57
========================================
Database index:  104
177
YES, Obs within 3000 days:  177
Swift J2058+05
179
YES, Obs within 3000 days:  179
Swift J2058+05
340
YES, Obs within 3000 days:  340
Swift J2058+05
========================================
Database index:  105
========================================
Database index:  106
3096
========================================
Database index:  107
========================================
Database index:  108
========================================
Database index:  109
1120
YES, Obs within 3000 days:  1120
WINGS J134849.88+263557.5
189
YES, Obs within 3000 days:  189
WINGS J134849.88+263557.5
========================================
Database index:  110
720
YES, Obs within 3000 days:  720
XMMSL1 J024916.6-041244
6222
6222
========================================
Database index:  111
33
YES, Obs within 3000 days:  33
XMMSL1 J061927.1-655311
YES, Obs within 100 days:  33
XMMSL1 J061927.1-655311
159
YES, Obs within 3000 days:  159
XMMSL1 J061927.1-655311
========================================
Database index:  112
21
YES, Obs within 3000 days:  21
XMMSL1 J063045.9-603110
YES, Obs within 100 days:  21
XMMSL1 J063045.9-603110
========================================
Database index:  113
28
YES, Obs within 3000 days:  28
XMMSL1 J0740-85
YES, Obs within 100 days:  28
XMMSL1 J0740-85
29
YES, Obs within 3000 days:  29
XMMSL1 J0740-85
YES, Obs within 100 days:  29
XMMSL1 J0740-85
29
YES, Obs within 3000 days:  29
XMMSL1 J0740-85
YES, Obs within 100 days:  29
XMMSL1 J0740-85
285
YES, Obs within 3000 days:  285
XMMSL1 J0740-85
========================================
Database index:  114
3081
========================================
Database index:  115
152
YES, Obs within 3000 days:  152
XMMSL2 J140446.9-251135
329
YES, Obs within 3000 days:  329
XMMSL2 J140446.9-251135
========================================
Database index:  116
3670
3678
3722
3750
4264
========================================
Database index:  117
84
YES, Obs within 3000 days:  84
ZTF18abxftqm
YES, Obs within 100 days:  84
ZTF18abxftqm
========================================

In [9]:
xmm.head(30)

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100
0,"10: 0657820101 (2010-12-02, 14913.0), 07409601...",2010/07/14,2MASX J01190869-3411305,True,False,False,141,2,None
1,"5: 0145800101 (2003-07-13, 107002.0), 03066301...",2003/07/13,2XMM J123103.2+110648,True,True,False,0,5,1
2,"3: 0405550401 (2006-09-06, 28262.0), 069461010...",2006/09/01,2XMMi J184725.1-631724,True,True,False,5,3,1
3,"11: 0302460101 (2005-07-23, 36708.0), 05546805...",2005/07/23,3XMM J150052.0+015452,True,True,False,0,5,1
4,"3: 0109930101 (2000-08-22, 55413.0), 010993020...",2000/08/23,3XMM J152130.7+074916,True,True,True,0,1,1
5,"4: 0823360101 (2018-05-24, 60000.0), 060359010...",2005/05/01,3XMM J215022.4-055108,True,False,False,369,3,None
6,"3: 0694651001 (2014-05-15, 23499.0), 069465110...",2014/01/25,ASASSN-14ae,True,False,False,110,3,None
7,"13: 0694651201 (2014-12-06, 23000.0), 06946514...",2014/11/22,ASASSN-14li,True,True,False,14,13,3
8,"2: 0770581201 (2015-11-18, 13000.0), 080228010...",2015/06/14,ASASSN-15lh,True,False,False,157,2,None
9,"2: 0722160501 (2015-10-29, 17200.0), 072216070...",2015/08/14,ASASSN-15oi,True,True,False,76,2,1
10,NaN,2020/07/08,ASASSN-20il,False,None,False,None,None,None
11,"1: 0303110101 (2005-07-14, 13109.0),",2016/08/26,AT2016ezh,False,None,True,None,None,None
12,"1: 0762470201 (2015-05-20, 28400.0),",2017/06/07,AT2017eqx,False,None,True,None,None,None
13,NaN,2018/09/08,AT2018fyk,False,None,False,None,None,None
14,"3: 0822040301 (2018-04-11, 21000.0), 082204040...",2018/03/06,AT2018zr,True,True,False,36,3,2
15,NaN,2019/02/22,AT2019azh,False,None,False,None,None,None
16,"2: 0842590901 (2019-05-30, 39999.0), 084259190...",2019/04/09,AT2019dsg,True,True,False,51,2,1
17,NaN,2020/04/29,AT2020ocn,False,None,False,None,None,None
18,NaN,2002/12/31,CSS100217,False,None,False,None,None,None
19,"49: 0827220901 (2019-08-06, 35300.0), 06049609...",2014/10/01,CXOU J0332,True,False,True,1770,1,None
20,NaN,2004/06/22,D1-9,False,None,False,None,None,None
21,"2: 0652401401 (2010-12-29, 39119.0), 065240300...",2007/09/04,D23H-1,True,False,False,1212,2,None
22,NaN,2004/01/15,D3-13,False,None,False,None,None,None
23,"2: 0722160401 (2015-02-26, 15000.0), 072216030...",2014/11/11,DES14C1kia,True,True,False,62,2,1
24,"2: 0655800101 (2010-05-07, 25655.0), 065580050...",2009/01/17,Dougie,True,False,False,475,2,None
25,"1: 0605880101 (2009-12-08, 34515.0),",2010/06/25,F01004-2237,False,None,True,None,None,None
26,NaN,2016/01/26,Gaia16aax,False,None,False,None,None,None
27,NaN,2016/03/29,Gaia16ajq,False,None,False,None,None,None
28,NaN,2016/03/31,Gaia16aka,False,None,False,None,None,None
29,"2: 0146420101 (2003-03-21, 48918.0), 067938030...",2003/03/22,IGR J17361-4441,False,None,True,None,None,None

In [10]:
print(xmm[f'xmm_within_{late_epoch}_days'].sum())
print(xmm[f'xmm_within_{early_epoch}_days'].sum())
# xmm.sample(10)
# xmm.head(10)

32
18

In [11]:
# Displays TDEs with obs within 1000 days
xmm["TDE"].loc[(xmm[f'xmm_within_{late_epoch}_days'] == True)]

0        2MASX J01190869-3411305
1          2XMM J123103.2+110648
2         2XMMi J184725.1-631724
3          3XMM J150052.0+015452
4          3XMM J152130.7+074916
5          3XMM J215022.4-055108
6                    ASASSN-14ae
7                    ASASSN-14li
8                    ASASSN-15lh
9                    ASASSN-15oi
14                      AT2018zr
16                     AT2019dsg
19                    CXOU J0332
21                        D23H-1
23                    DES14C1kia
24                        Dougie
50                MAXI J1807+132
51                       NGC 247
52                      NGC 3599
55                     OGLE16aaa
78                     SDSSJ0159
81                  SDSSJ1201+30
83                     SDSSJ1323
101               Swift J1644+57
102               Swift J2058+05
107    WINGS J134849.88+263557.5
108      XMMSL1 J024916.6-041244
109      XMMSL1 J061927.1-655311
110      XMMSL1 J063045.9-603110
111              XMMSL1 J0740-85
113      XMMSL2 J140446.9-251135
115                 ZTF18abxftqm
Name: TDE, dtype: object

In [12]:
# Displays TDEs with obs within 100 days
xmm["TDE"].loc[(xmm[f'xmm_within_{early_epoch}_days'] == True)]

1        2XMM J123103.2+110648
2       2XMMi J184725.1-631724
3        3XMM J150052.0+015452
4        3XMM J152130.7+074916
7                  ASASSN-14li
9                  ASASSN-15oi
14                    AT2018zr
16                   AT2019dsg
23                  DES14C1kia
50              MAXI J1807+132
51                     NGC 247
78                   SDSSJ0159
81                SDSSJ1201+30
101             Swift J1644+57
109    XMMSL1 J061927.1-655311
110    XMMSL1 J063045.9-603110
111            XMMSL1 J0740-85
115               ZTF18abxftqm
Name: TDE, dtype: object

In [13]:
# Returns table of objects above
xmm.loc[(xmm[f'xmm_within_{late_epoch}_days'] == True)]

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100
0,"10: 0657820101 (2010-12-02, 14913.0), 07409601...",2010/07/14,2MASX J01190869-3411305,True,False,False,141,2,None
1,"5: 0145800101 (2003-07-13, 107002.0), 03066301...",2003/07/13,2XMM J123103.2+110648,True,True,False,0,5,1
2,"3: 0405550401 (2006-09-06, 28262.0), 069461010...",2006/09/01,2XMMi J184725.1-631724,True,True,False,5,3,1
3,"11: 0302460101 (2005-07-23, 36708.0), 05546805...",2005/07/23,3XMM J150052.0+015452,True,True,False,0,5,1
4,"3: 0109930101 (2000-08-22, 55413.0), 010993020...",2000/08/23,3XMM J152130.7+074916,True,True,True,0,1,1
5,"4: 0823360101 (2018-05-24, 60000.0), 060359010...",2005/05/01,3XMM J215022.4-055108,True,False,False,369,3,None
6,"3: 0694651001 (2014-05-15, 23499.0), 069465110...",2014/01/25,ASASSN-14ae,True,False,False,110,3,None
7,"13: 0694651201 (2014-12-06, 23000.0), 06946514...",2014/11/22,ASASSN-14li,True,True,False,14,13,3
8,"2: 0770581201 (2015-11-18, 13000.0), 080228010...",2015/06/14,ASASSN-15lh,True,False,False,157,2,None
9,"2: 0722160501 (2015-10-29, 17200.0), 072216070...",2015/08/14,ASASSN-15oi,True,True,False,76,2,1
14,"3: 0822040301 (2018-04-11, 21000.0), 082204040...",2018/03/06,AT2018zr,True,True,False,36,3,2
16,"2: 0842590901 (2019-05-30, 39999.0), 084259190...",2019/04/09,AT2019dsg,True,True,False,51,2,1
19,"49: 0827220901 (2019-08-06, 35300.0), 06049609...",2014/10/01,CXOU J0332,True,False,True,1770,1,None
21,"2: 0652401401 (2010-12-29, 39119.0), 065240300...",2007/09/04,D23H-1,True,False,False,1212,2,None
23,"2: 0722160401 (2015-02-26, 15000.0), 072216030...",2014/11/11,DES14C1kia,True,True,False,62,2,1
24,"2: 0655800101 (2010-05-07, 25655.0), 065580050...",2009/01/17,Dougie,True,False,False,475,2,None
50,"2: 0744250301 (2017-03-29, 19000.0), 074425040...",2017/03/15,MAXI J1807+132,True,True,False,14,2,2
51,"11: 0601010101 (2009-12-27, 34816.0), 07281901...",2014/07/01,NGC 247,True,True,True,0,9,1
52,"2: 0411980101 (2006-06-23, 6894.0), 0556090101...",2002/05/27,NGC 3599,True,False,False,1488,2,None
55,"2: 0790181801 (2016-06-09, 15000.0), 079318320...",2015/12/17,OGLE16aaa,True,False,False,175,2,None
78,"1: 0101640201 (2000-07-29, 14769.0),",2000/07/29,SDSSJ0159,True,True,False,0,1,1
81,"3: 0555060301 (2010-06-22, 35819.0), 055506040...",2010/06/10,SDSSJ1201+30,True,True,False,12,3,1
83,"1: 0411980501 (2006-07-15, 6892.0),",2003/12/02,SDSSJ1323,True,False,False,956,1,None
101,"19: 0678380101 (2011-04-16, 24919.0), 06783802...",2011/03/29,Swift J1644+57,True,True,False,2,19,7
102,"3: 0679380801 (2011-11-20, 23917.0), 067938090...",2011/05/27,Swift J2058+05,True,False,False,177,3,None
107,"2: 0109070201 (2003-01-13, 72061.0), 009782010...",1999/12/20,WINGS J134849.88+263557.5,True,False,False,189,2,None
108,"3: 0411980401 (2006-07-14, 11739.0), 089180060...",2004/07/24,XMMSL1 J024916.6-041244,True,False,False,720,1,None
109,"2: 0691100201 (2012-12-15, 31917.0), 069110030...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,33,2,1
110,"1: 0679381201 (2011-12-22, 14719.0),",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,21,1,1
111,"4: 0740340301 (2014-04-29, 17340.0), 074034040...",2014/04/01,XMMSL1 J0740-85,True,True,False,28,4,3
113,"2: 0804860201 (2018-07-17, 34300.0), 080486030...",2018/02/15,XMMSL2 J140446.9-251135,True,False,False,152,2,None
115,"1: 0822040901 (2018-12-27, 21000.0),",2018/10/04,ZTF18abxftqm,True,True,False,84,1,1

In [14]:
# Displays TDEs with obs with neg dt
# Double check the disc dates here for errors
xmm.TDE.loc[(xmm["xmm_neg_delta_days?"] == True)]

4     3XMM J152130.7+074916
11                AT2016ezh
12                AT2017eqx
19               CXOU J0332
25              F01004-2237
29          IGR J17361-4441
51                  NGC 247
58              PGC 1127938
67                 PS1-13jw
82                SDSSJ1311
Name: TDE, dtype: object

In [15]:
# Returns table of objects above
xmm.loc[(xmm["xmm_neg_delta_days?"] == True)]

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100
4,"3: 0109930101 (2000-08-22, 55413.0), 010993020...",2000/08/23,3XMM J152130.7+074916,True,True,True,0,1,1
11,"1: 0303110101 (2005-07-14, 13109.0),",2016/08/26,AT2016ezh,False,None,True,None,None,None
12,"1: 0762470201 (2015-05-20, 28400.0),",2017/06/07,AT2017eqx,False,None,True,None,None,None
19,"49: 0827220901 (2019-08-06, 35300.0), 06049609...",2014/10/01,CXOU J0332,True,False,True,1770,1,None
25,"1: 0605880101 (2009-12-08, 34515.0),",2010/06/25,F01004-2237,False,None,True,None,None,None
29,"2: 0146420101 (2003-03-21, 48918.0), 067938030...",2003/03/22,IGR J17361-4441,False,None,True,None,None,None
51,"11: 0601010101 (2009-12-27, 34816.0), 07281901...",2014/07/01,NGC 247,True,True,True,0,9,1
58,"1: 0153170101 (2003-07-11, 22204.0),",2007/01/08,PGC 1127938,False,None,True,None,None,None
67,"1: 0503600101 (2007-11-06, 26817.0),",2013/02/06,PS1-13jw,False,None,True,None,None,None
82,"2: 0093030101 (2001-12-24, 39763.0), 069382020...",2004/02/28,SDSSJ1311,False,None,True,None,None,None

In [16]:
# Shows TDEs with dt less than 1000 days AND has no neg dts
xmm.loc[ (xmm[f'xmm_within_{late_epoch}_days'] == True) 
            & (xmm["xmm_neg_delta_days?"] == False)
           ]

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100
0,"10: 0657820101 (2010-12-02, 14913.0), 07409601...",2010/07/14,2MASX J01190869-3411305,True,False,False,141,2,None
1,"5: 0145800101 (2003-07-13, 107002.0), 03066301...",2003/07/13,2XMM J123103.2+110648,True,True,False,0,5,1
2,"3: 0405550401 (2006-09-06, 28262.0), 069461010...",2006/09/01,2XMMi J184725.1-631724,True,True,False,5,3,1
3,"11: 0302460101 (2005-07-23, 36708.0), 05546805...",2005/07/23,3XMM J150052.0+015452,True,True,False,0,5,1
5,"4: 0823360101 (2018-05-24, 60000.0), 060359010...",2005/05/01,3XMM J215022.4-055108,True,False,False,369,3,None
6,"3: 0694651001 (2014-05-15, 23499.0), 069465110...",2014/01/25,ASASSN-14ae,True,False,False,110,3,None
7,"13: 0694651201 (2014-12-06, 23000.0), 06946514...",2014/11/22,ASASSN-14li,True,True,False,14,13,3
8,"2: 0770581201 (2015-11-18, 13000.0), 080228010...",2015/06/14,ASASSN-15lh,True,False,False,157,2,None
9,"2: 0722160501 (2015-10-29, 17200.0), 072216070...",2015/08/14,ASASSN-15oi,True,True,False,76,2,1
14,"3: 0822040301 (2018-04-11, 21000.0), 082204040...",2018/03/06,AT2018zr,True,True,False,36,3,2
16,"2: 0842590901 (2019-05-30, 39999.0), 084259190...",2019/04/09,AT2019dsg,True,True,False,51,2,1
21,"2: 0652401401 (2010-12-29, 39119.0), 065240300...",2007/09/04,D23H-1,True,False,False,1212,2,None
23,"2: 0722160401 (2015-02-26, 15000.0), 072216030...",2014/11/11,DES14C1kia,True,True,False,62,2,1
24,"2: 0655800101 (2010-05-07, 25655.0), 065580050...",2009/01/17,Dougie,True,False,False,475,2,None
50,"2: 0744250301 (2017-03-29, 19000.0), 074425040...",2017/03/15,MAXI J1807+132,True,True,False,14,2,2
52,"2: 0411980101 (2006-06-23, 6894.0), 0556090101...",2002/05/27,NGC 3599,True,False,False,1488,2,None
55,"2: 0790181801 (2016-06-09, 15000.0), 079318320...",2015/12/17,OGLE16aaa,True,False,False,175,2,None
78,"1: 0101640201 (2000-07-29, 14769.0),",2000/07/29,SDSSJ0159,True,True,False,0,1,1
81,"3: 0555060301 (2010-06-22, 35819.0), 055506040...",2010/06/10,SDSSJ1201+30,True,True,False,12,3,1
83,"1: 0411980501 (2006-07-15, 6892.0),",2003/12/02,SDSSJ1323,True,False,False,956,1,None
101,"19: 0678380101 (2011-04-16, 24919.0), 06783802...",2011/03/29,Swift J1644+57,True,True,False,2,19,7
102,"3: 0679380801 (2011-11-20, 23917.0), 067938090...",2011/05/27,Swift J2058+05,True,False,False,177,3,None
107,"2: 0109070201 (2003-01-13, 72061.0), 009782010...",1999/12/20,WINGS J134849.88+263557.5,True,False,False,189,2,None
108,"3: 0411980401 (2006-07-14, 11739.0), 089180060...",2004/07/24,XMMSL1 J024916.6-041244,True,False,False,720,1,None
109,"2: 0691100201 (2012-12-15, 31917.0), 069110030...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,33,2,1
110,"1: 0679381201 (2011-12-22, 14719.0),",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,21,1,1
111,"4: 0740340301 (2014-04-29, 17340.0), 074034040...",2014/04/01,XMMSL1 J0740-85,True,True,False,28,4,3
113,"2: 0804860201 (2018-07-17, 34300.0), 080486030...",2018/02/15,XMMSL2 J140446.9-251135,True,False,False,152,2,None
115,"1: 0822040901 (2018-12-27, 21000.0),",2018/10/04,ZTF18abxftqm,True,True,False,84,1,1

In [17]:
# Gets list of objects from above table
print(list(xmm.TDE.loc[ (xmm[f'xmm_within_{late_epoch}_days'] == True) 
            & (xmm["xmm_neg_delta_days?"] == False)
           ]))

xmm_late_list = list(xmm.TDE.loc[ (xmm[f'xmm_within_{late_epoch}_days'] == True) 
            & (xmm["xmm_neg_delta_days?"] == False)
           ])

print(len(xmm_late_list))

['2MASX J01190869-3411305', '2XMM J123103.2+110648', '2XMMi J184725.1-631724', '3XMM J150052.0+015452', '3XMM J215022.4-055108', 'ASASSN-14ae', 'ASASSN-14li', 'ASASSN-15lh', 'ASASSN-15oi', 'AT2018zr', 'AT2019dsg', 'D23H-1', 'DES14C1kia', 'Dougie', 'MAXI J1807+132', 'NGC 3599', 'OGLE16aaa', 'SDSSJ0159', 'SDSSJ1201+30', 'SDSSJ1323', 'Swift J1644+57', 'Swift J2058+05', 'WINGS J134849.88+263557.5', 'XMMSL1 J024916.6-041244', 'XMMSL1 J061927.1-655311', 'XMMSL1 J063045.9-603110', 'XMMSL1 J0740-85', 'XMMSL2 J140446.9-251135', 'ZTF18abxftqm']
29

In [18]:
# Shows TDEs with dt less than 100 days AND has no neg dts
xmm.loc[ (xmm[f'xmm_within_{early_epoch}_days'] == True) 
            & (xmm["xmm_neg_delta_days?"] == False)
           ]

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100
1,"5: 0145800101 (2003-07-13, 107002.0), 03066301...",2003/07/13,2XMM J123103.2+110648,True,True,False,0,5,1
2,"3: 0405550401 (2006-09-06, 28262.0), 069461010...",2006/09/01,2XMMi J184725.1-631724,True,True,False,5,3,1
3,"11: 0302460101 (2005-07-23, 36708.0), 05546805...",2005/07/23,3XMM J150052.0+015452,True,True,False,0,5,1
7,"13: 0694651201 (2014-12-06, 23000.0), 06946514...",2014/11/22,ASASSN-14li,True,True,False,14,13,3
9,"2: 0722160501 (2015-10-29, 17200.0), 072216070...",2015/08/14,ASASSN-15oi,True,True,False,76,2,1
14,"3: 0822040301 (2018-04-11, 21000.0), 082204040...",2018/03/06,AT2018zr,True,True,False,36,3,2
16,"2: 0842590901 (2019-05-30, 39999.0), 084259190...",2019/04/09,AT2019dsg,True,True,False,51,2,1
23,"2: 0722160401 (2015-02-26, 15000.0), 072216030...",2014/11/11,DES14C1kia,True,True,False,62,2,1
50,"2: 0744250301 (2017-03-29, 19000.0), 074425040...",2017/03/15,MAXI J1807+132,True,True,False,14,2,2
78,"1: 0101640201 (2000-07-29, 14769.0),",2000/07/29,SDSSJ0159,True,True,False,0,1,1
81,"3: 0555060301 (2010-06-22, 35819.0), 055506040...",2010/06/10,SDSSJ1201+30,True,True,False,12,3,1
101,"19: 0678380101 (2011-04-16, 24919.0), 06783802...",2011/03/29,Swift J1644+57,True,True,False,2,19,7
109,"2: 0691100201 (2012-12-15, 31917.0), 069110030...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,33,2,1
110,"1: 0679381201 (2011-12-22, 14719.0),",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,21,1,1
111,"4: 0740340301 (2014-04-29, 17340.0), 074034040...",2014/04/01,XMMSL1 J0740-85,True,True,False,28,4,3
115,"1: 0822040901 (2018-12-27, 21000.0),",2018/10/04,ZTF18abxftqm,True,True,False,84,1,1

In [19]:
# Gets list of objects from above table
print(list(xmm.TDE.loc[ (xmm[f'xmm_within_{early_epoch}_days'] == True) 
            & (xmm["xmm_neg_delta_days?"] == False)
           ]))

xmm_early_list = list(xmm.TDE.loc[ (xmm[f'xmm_within_{early_epoch}_days'] == True) 
            & (xmm["xmm_neg_delta_days?"] == False)
           ])

print(len(xmm_early_list))

['2XMM J123103.2+110648', '2XMMi J184725.1-631724', '3XMM J150052.0+015452', 'ASASSN-14li', 'ASASSN-15oi', 'AT2018zr', 'AT2019dsg', 'DES14C1kia', 'MAXI J1807+132', 'SDSSJ0159', 'SDSSJ1201+30', 'Swift J1644+57', 'XMMSL1 J061927.1-655311', 'XMMSL1 J063045.9-603110', 'XMMSL1 J0740-85', 'ZTF18abxftqm']
16

# Chandra Data

In [20]:
xamin_files.head(1)

,TDE,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])","XMM TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","XMM Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","XMM Col D ObsID (exp time, date, #days after discovery)","Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)","Chandra TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","Chandra Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","Chandra Col H ObsID (exp time, date, #days after discovery)","Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])","Swift TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","Swift Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","Swift Col L ObsID (exp time, date, #days after discovery)",Disc Date
0,2MASX J01190869-3411305,"10: 0657820101 (2010-12-02, 14913.0), 07409601...","10, 0.0039, 0.017",9.0,"0657820101 (14913.0, 2010-12-02, 154), 0740960...","1: 22096 (2019-02-14, 73570.0, ACIS-S ),","1, 0.0167, 0.0167",1.0,"22096 (73570.0, 2019-02-14, 3150),","32: 00031789003 (2010-08-27, 2073.517), 000317...","32, 0.4007, 24.6643",26.0,"00031789003 (2073.517, 2010-08-27, 57), 000317...",2010/07/14

In [21]:
chan = pd.DataFrame(xamin_files['Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)'])
chan = pd.concat( (chan, xamin_files['Disc Date'], xamin_files['TDE']), axis='columns')
chan[f'chan_within_{late_epoch}_days'] = None
chan[f'chan_within_{early_epoch}_days'] = None
chan['chan_neg_delta_days?'] = None
chan['chan_min_dt'] = None
chan[f'chan_num_dt_within_{late_epoch}'] = None
chan[f'chan_num_dt_within_{early_epoch}'] = None
chan

,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",Disc Date,TDE,chan_within_3000_days,chan_within_100_days,chan_neg_delta_days?,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100
0,"1: 22096 (2019-02-14, 73570.0, ACIS-S ),",2010/07/14,2MASX J01190869-3411305,None,None,None,None,None,None
1,"1: 17129 (2016-02-10, 40060.0, ACIS-S ),",2003/07/13,2XMM J123103.2+110648,None,None,None,None,None,None
2,"1: 15637 (2013-03-29, 15070.0, ACIS-S ),",2006/09/01,2XMMi J184725.1-631724,None,None,None,None,None,None
3,"12: 9517 (2008-06-05, 100060.0, ACIS-S ), 5...",2005/07/23,3XMM J150052.0+015452,None,None,None,None,None,None
4,"1: 900 (2000-04-03, 58030.0, ACIS-I ),",2000/08/23,3XMM J152130.7+074916,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
111,NaN,2014/04/01,XMMSL1 J0740-85,None,None,None,None,None,None
112,NaN,2005/07/15,XMMSL1 J131952.3+225958,None,None,None,None,None,None
113,NaN,2018/02/15,XMMSL2 J140446.9-251135,None,None,None,None,None,None
114,NaN,2006/08/22,XMMSL2 J144605.0+685735,None,None,None,None,None,None
115,NaN,2018/10/04,ZTF18abxftqm,None,None,None,None,None,None

In [22]:
for index, row in chan.iterrows():
    print("Database index: ",index + 2)
    df_row = pd.DataFrame(row)
#     print(df_row)
    tde = chan['TDE'][index]
    df_row_disc_date = df_row.to_string().split('\n')[2].split()[1]
#     print(df_row_disc_date, type(df_row_disc_date))
    df_row = df_row.to_string().split(')')[1:]
#     print(df_row)
    
    chan_within_late_epoch = False
    chan_within_early_epoch = False
    chan_neg_delta_days = False
    chan_diff_time_list = []
    chan_diff_supedd_time_list = []

    for i, line in enumerate(df_row):
#         print(line)
#         if i == 0:
#             print("Num of Obs Ids: ",line.split(':')[0])
#             print('-'*20)
        if i < len(df_row) - 1:
            if i == 0:
                line = line.split(':')[1].replace('   ', ' ').replace('  ', ' ').split(' ')[1:]
                # print(line)
                exp_time = float(line[2].split(',')[0])
            if i > 0:
                line = line.split(':')[0].replace('   ', ' ').replace('  ', ' ').strip().split(' ')[1:]
                # print(line)
                exp_time = float(line[2].split(',')[0])
            for j, element in enumerate(line):
#                 print(element, j)
                element = element.strip('(').strip(',')
#                 print(element, j)

                if j==1 and exp_time>1e3:  # getting the obervation date for all >1 ksec exposures
                    if element == 'null':
                        break
#                     print(element)
                    element = pd.to_datetime(element)
#                     print(type(element))
#                     print(element.year)
#                     disc_date = pd.to_datetime('1950-12-01')
#                     disc_date = pd.to_datetime(chan['Disc Date'][index].split('?')[0])
                    disc_date = pd.to_datetime(chan['Disc Date'][index])
#                     print(disc_date)
                    diff_time = element - disc_date
                    diff_time = diff_time.days
#                     print(diff_time)
    
                    if 0 <= diff_time <= late_epoch:
                        print(f"YES, Obs within {late_epoch} days: ", diff_time)
                        print(tde)
                        chan_within_late_epoch = True
                        chan_diff_time_list.append(diff_time)
                        
                        if 0 <= diff_time <= early_epoch:
                            print(f"YES, Obs within {early_epoch} days: ", diff_time)
                            print(tde)
                            chan_within_early_epoch = True
                            chan_diff_supedd_time_list.append(diff_time)
                        
                    if diff_time < 0:
                        print("ERROR negative delta days. CHECK DISC DATE!!!", diff_time)
                        print(tde)
                        chan_neg_delta_days = True
                    
    if chan_within_late_epoch == True:
        chan[f'chan_within_{late_epoch}_days'][index] = True
        chan['chan_min_dt'][index] = min(chan_diff_time_list)
        chan[f'chan_num_dt_within_{late_epoch}'][index] = len(chan_diff_time_list)
        if chan_within_early_epoch == True:
            chan[f'chan_within_{early_epoch}_days'][index] = True
            chan['chan_min_dt'][index] = min(chan_diff_supedd_time_list)
            chan[f'chan_num_dt_within_{early_epoch}'][index] = len(chan_diff_supedd_time_list)
        else:
            chan[f'chan_within_{early_epoch}_days'][index] = False
    else:
        chan[f'chan_within_{late_epoch}_days'][index] = False

    if chan_neg_delta_days == True:
        chan['chan_neg_delta_days?'][index] = True
    else:
        chan['chan_neg_delta_days?'][index] = False
                    
#             print('\n')
# #         print('.'*40)
    print('='*40)

Database index:  2
========================================
Database index:  3
========================================
Database index:  4
YES, Obs within 3000 days:  2401
2XMMi J184725.1-631724
========================================
Database index:  5
YES, Obs within 3000 days:  1048
3XMM J150052.0+015452
ERROR negative delta days. CHECK DISC DATE!!! -112
3XMM J150052.0+015452
YES, Obs within 3000 days:  2085
3XMM J150052.0+015452
YES, Obs within 3000 days:  2074
3XMM J150052.0+015452
YES, Obs within 3000 days:  2082
3XMM J150052.0+015452
YES, Obs within 3000 days:  2084
3XMM J150052.0+015452
YES, Obs within 3000 days:  2076
3XMM J150052.0+015452
YES, Obs within 3000 days:  2077
3XMM J150052.0+015452
YES, Obs within 3000 days:  2087
3XMM J150052.0+015452
YES, Obs within 3000 days:  1726
3XMM J150052.0+015452
========================================
Database index:  6
ERROR negative delta days. CHECK DISC DATE!!! -142
3XMM J152130.7+074916
========================================
Database index:  7
YES, Obs within 3000 days:  515
3XMM J215022.4-055108
========================================
Database index:  8
YES, Obs within 3000 days:  1757
ASASSN-14ae
========================================
Database index:  9
YES, Obs within 3000 days:  16
ASASSN-14li
YES, Obs within 100 days:  16
ASASSN-14li
YES, Obs within 3000 days:  19
ASASSN-14li
YES, Obs within 100 days:  19
ASASSN-14li
YES, Obs within 3000 days:  432
ASASSN-14li
YES, Obs within 3000 days:  620
ASASSN-14li
YES, Obs within 3000 days:  985
ASASSN-14li
YES, Obs within 3000 days:  986
ASASSN-14li
YES, Obs within 3000 days:  987
ASASSN-14li
========================================
Database index:  10
YES, Obs within 3000 days:  151
ASASSN-15lh
YES, Obs within 3000 days:  182
ASASSN-15lh
YES, Obs within 3000 days:  251
ASASSN-15lh
YES, Obs within 3000 days:  432
ASASSN-15lh
========================================
Database index:  11
========================================
Database index:  12
========================================
Database index:  13
ERROR negative delta days. CHECK DISC DATE!!! -638
AT2016ezh
ERROR negative delta days. CHECK DISC DATE!!! -3357
AT2016ezh
YES, Obs within 3000 days:  867
AT2016ezh
YES, Obs within 3000 days:  1172
AT2016ezh
YES, Obs within 3000 days:  1517
AT2016ezh
========================================
Database index:  14
YES, Obs within 3000 days:  70
AT2017eqx
YES, Obs within 100 days:  70
AT2017eqx
YES, Obs within 3000 days:  575
AT2017eqx
ERROR negative delta days. CHECK DISC DATE!!! -2483
AT2017eqx
ERROR negative delta days. CHECK DISC DATE!!! -1390
AT2017eqx
========================================
Database index:  15
========================================
Database index:  16
========================================
Database index:  17
========================================
Database index:  18
========================================
Database index:  19
========================================
Database index:  20
========================================
Database index:  21
ERROR negative delta days. CHECK DISC DATE!!! -3607
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -3602
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -3609
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -3605
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -3607
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2552
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2568
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2536
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2526
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2539
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2534
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2541
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2531
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2528
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2566
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2523
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -2555
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5466
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5240
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5233
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5037
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5042
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5465
CXOU J0332
YES, Obs within 3000 days:  52
CXOU J0332
YES, Obs within 100 days:  52
CXOU J0332
YES, Obs within 3000 days:  236
CXOU J0332
YES, Obs within 3000 days:  27
CXOU J0332
YES, Obs within 100 days:  27
CXOU J0332
YES, Obs within 3000 days:  48
CXOU J0332
YES, Obs within 100 days:  48
CXOU J0332
YES, Obs within 3000 days:  174
CXOU J0332
YES, Obs within 3000 days:  30
CXOU J0332
YES, Obs within 100 days:  30
CXOU J0332
YES, Obs within 3000 days:  437
CXOU J0332
YES, Obs within 3000 days:  171
CXOU J0332
YES, Obs within 3000 days:  0
CXOU J0332
YES, Obs within 100 days:  0
CXOU J0332
YES, Obs within 3000 days:  391
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -64
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -101
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -57
CXOU J0332
YES, Obs within 3000 days:  394
CXOU J0332
YES, Obs within 3000 days:  91
CXOU J0332
YES, Obs within 100 days:  91
CXOU J0332
YES, Obs within 3000 days:  262
CXOU J0332
YES, Obs within 3000 days:  258
CXOU J0332
YES, Obs within 3000 days:  230
CXOU J0332
YES, Obs within 3000 days:  13
CXOU J0332
YES, Obs within 100 days:  13
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -8
CXOU J0332
YES, Obs within 3000 days:  6
CXOU J0332
YES, Obs within 100 days:  6
CXOU J0332
YES, Obs within 3000 days:  9
CXOU J0332
YES, Obs within 100 days:  9
CXOU J0332
YES, Obs within 3000 days:  7
CXOU J0332
YES, Obs within 100 days:  7
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -62
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -56
CXOU J0332
YES, Obs within 3000 days:  1
CXOU J0332
YES, Obs within 100 days:  1
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -3
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -6
CXOU J0332
YES, Obs within 3000 days:  16
CXOU J0332
YES, Obs within 100 days:  16
CXOU J0332
YES, Obs within 3000 days:  2
CXOU J0332
YES, Obs within 100 days:  2
CXOU J0332
YES, Obs within 3000 days:  23
CXOU J0332
YES, Obs within 100 days:  23
CXOU J0332
YES, Obs within 3000 days:  32
CXOU J0332
YES, Obs within 100 days:  32
CXOU J0332
YES, Obs within 3000 days:  374
CXOU J0332
YES, Obs within 3000 days:  69
CXOU J0332
YES, Obs within 100 days:  69
CXOU J0332
YES, Obs within 3000 days:  95
CXOU J0332
YES, Obs within 100 days:  95
CXOU J0332
YES, Obs within 3000 days:  166
CXOU J0332
YES, Obs within 3000 days:  169
CXOU J0332
YES, Obs within 3000 days:  540
CXOU J0332
YES, Obs within 3000 days:  417
CXOU J0332
YES, Obs within 3000 days:  435
CXOU J0332
YES, Obs within 3000 days:  489
CXOU J0332
YES, Obs within 3000 days:  410
CXOU J0332
YES, Obs within 3000 days:  32
CXOU J0332
YES, Obs within 100 days:  32
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -114
CXOU J0332
YES, Obs within 3000 days:  33
CXOU J0332
YES, Obs within 100 days:  33
CXOU J0332
YES, Obs within 3000 days:  43
CXOU J0332
YES, Obs within 100 days:  43
CXOU J0332
YES, Obs within 3000 days:  59
CXOU J0332
YES, Obs within 100 days:  59
CXOU J0332
YES, Obs within 3000 days:  25
CXOU J0332
YES, Obs within 100 days:  25
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5043
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5034
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5032
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5030
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -5040
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1655
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1658
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1653
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1648
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1637
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1633
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1592
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1587
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1581
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1574
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1569
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1549
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1545
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1600
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1649
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1642
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1639
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1629
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1627
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1598
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1573
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1578
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1566
CXOU J0332
ERROR negative delta days. CHECK DISC DATE!!! -1579
CXOU J0332
========================================
Database index:  22
========================================
Database index:  23
YES, Obs within 3000 days:  337
D23H-1
YES, Obs within 3000 days:  337
D23H-1
YES, Obs within 3000 days:  336
D23H-1
YES, Obs within 3000 days:  336
D23H-1
YES, Obs within 3000 days:  336
D23H-1
YES, Obs within 3000 days:  27
D23H-1
YES, Obs within 100 days:  27
D23H-1
YES, Obs within 3000 days:  141
D23H-1
YES, Obs within 3000 days:  29
D23H-1
YES, Obs within 100 days:  29
D23H-1
========================================
Database index:  24
YES, Obs within 3000 days:  1889
D3-13
YES, Obs within 3000 days:  1720
D3-13
YES, Obs within 3000 days:  1730
D3-13
YES, Obs within 3000 days:  1989
D3-13
YES, Obs within 3000 days:  1706
D3-13
YES, Obs within 3000 days:  1709
D3-13
YES, Obs within 3000 days:  1710
D3-13
YES, Obs within 3000 days:  1711
D3-13
YES, Obs within 3000 days:  1722
D3-13
YES, Obs within 3000 days:  1725
D3-13
YES, Obs within 3000 days:  1880
D3-13
YES, Obs within 3000 days:  1891
D3-13
YES, Obs within 3000 days:  1812
D3-13
YES, Obs within 3000 days:  1813
D3-13
YES, Obs within 3000 days:  1814
D3-13
YES, Obs within 3000 days:  1882
D3-13
YES, Obs within 3000 days:  1883
D3-13
YES, Obs within 3000 days:  1978
D3-13
YES, Obs within 3000 days:  1985
D3-13
YES, Obs within 3000 days:  635
D3-13
YES, Obs within 3000 days:  638
D3-13
YES, Obs within 3000 days:  631
D3-13
YES, Obs within 3000 days:  619
D3-13
YES, Obs within 3000 days:  1701
D3-13
YES, Obs within 3000 days:  1703
D3-13
YES, Obs within 3000 days:  1714
D3-13
YES, Obs within 3000 days:  1625
D3-13
YES, Obs within 3000 days:  1702
D3-13
YES, Obs within 3000 days:  1637
D3-13
YES, Obs within 3000 days:  1715
D3-13
YES, Obs within 3000 days:  1631
D3-13
YES, Obs within 3000 days:  1717
D3-13
YES, Obs within 3000 days:  1626
D3-13
YES, Obs within 3000 days:  1627
D3-13
YES, Obs within 3000 days:  1633
D3-13
YES, Obs within 3000 days:  1718
D3-13
YES, Obs within 3000 days:  447
D3-13
YES, Obs within 3000 days:  448
D3-13
YES, Obs within 3000 days:  614
D3-13
YES, Obs within 3000 days:  617
D3-13
YES, Obs within 3000 days:  1426
D3-13
YES, Obs within 3000 days:  1431
D3-13
YES, Obs within 3000 days:  1433
D3-13
YES, Obs within 3000 days:  1613
D3-13
YES, Obs within 3000 days:  1615
D3-13
YES, Obs within 3000 days:  1610
D3-13
YES, Obs within 3000 days:  1611
D3-13
YES, Obs within 3000 days:  1616
D3-13
YES, Obs within 3000 days:  1437
D3-13
YES, Obs within 3000 days:  1537
D3-13
YES, Obs within 3000 days:  1603
D3-13
YES, Obs within 3000 days:  1434
D3-13
YES, Obs within 3000 days:  1435
D3-13
YES, Obs within 3000 days:  1435
D3-13
YES, Obs within 3000 days:  1436
D3-13
YES, Obs within 3000 days:  1438
D3-13
YES, Obs within 3000 days:  1539
D3-13
YES, Obs within 3000 days:  1539
D3-13
YES, Obs within 3000 days:  1542
D3-13
YES, Obs within 3000 days:  1605
D3-13
YES, Obs within 3000 days:  1601
D3-13
YES, Obs within 3000 days:  1608
D3-13
YES, Obs within 3000 days:  1609
D3-13
YES, Obs within 3000 days:  1621
D3-13
YES, Obs within 3000 days:  1620
D3-13
YES, Obs within 3000 days:  434
D3-13
YES, Obs within 3000 days:  437
D3-13
YES, Obs within 3000 days:  622
D3-13
YES, Obs within 3000 days:  623
D3-13
========================================
Database index:  25
YES, Obs within 3000 days:  1579
DES14C1kia
========================================
Database index:  26
ERROR negative delta days. CHECK DISC DATE!!! -2846
Dougie
========================================
Database index:  27
ERROR negative delta days. CHECK DISC DATE!!! -2518
F01004-2237
YES, Obs within 3000 days:  417
F01004-2237
YES, Obs within 3000 days:  448
F01004-2237
YES, Obs within 3000 days:  434
F01004-2237
YES, Obs within 3000 days:  467
F01004-2237
YES, Obs within 3000 days:  471
F01004-2237
YES, Obs within 3000 days:  477
F01004-2237
YES, Obs within 3000 days:  472
F01004-2237
YES, Obs within 3000 days:  70
F01004-2237
YES, Obs within 100 days:  70
F01004-2237
========================================
Database index:  28
========================================
Database index:  29
========================================
Database index:  30
========================================
Database index:  31
YES, Obs within 3000 days:  761
IGR J17361-4441
========================================
Database index:  32
YES, Obs within 3000 days:  915
iPTF16axa
========================================
Database index:  33
YES, Obs within 3000 days:  1006
iPTF16fnl
========================================
Database index:  34
========================================
Database index:  35
========================================
Database index:  36
========================================
Database index:  37
========================================
Database index:  38
========================================
Database index:  39
========================================
Database index:  40
========================================
Database index:  41
========================================
Database index:  42
========================================
Database index:  43
========================================
Database index:  44
========================================
Database index:  45
========================================
Database index:  46
========================================
Database index:  47
========================================
Database index:  48
========================================
Database index:  49
========================================
Database index:  50
========================================
Database index:  51
========================================
Database index:  52
========================================
Database index:  53
YES, Obs within 3000 days:  134
NGC 247
ERROR negative delta days. CHECK DISC DATE!!! -1246
NGC 247
========================================
Database index:  54
YES, Obs within 3000 days:  2070
NGC 3599
========================================
Database index:  55
========================================
Database index:  56
========================================
Database index:  57
========================================
Database index:  58
========================================
Database index:  59
========================================
Database index:  60
ERROR negative delta days. CHECK DISC DATE!!! -694
PGC 1127938
========================================
Database index:  61
YES, Obs within 3000 days:  218
PGC 1185375
YES, Obs within 3000 days:  225
PGC 1185375
========================================
Database index:  62
========================================
Database index:  63
========================================
Database index:  64
========================================
Database index:  65
========================================
Database index:  66
YES, Obs within 3000 days:  371
PS1-10jh
ERROR negative delta days. CHECK DISC DATE!!! -1563
PS1-10jh
ERROR negative delta days. CHECK DISC DATE!!! -1561
PS1-10jh
========================================
Database index:  67
========================================
Database index:  68
========================================
Database index:  69
YES, Obs within 3000 days:  1054
PS1-13jw
========================================
Database index:  70
========================================
Database index:  71
========================================
Database index:  72
========================================
Database index:  73
========================================
Database index:  74
========================================
Database index:  75
========================================
Database index:  76
========================================
Database index:  77
========================================
Database index:  78
========================================
Database index:  79
========================================
Database index:  80
YES, Obs within 3000 days:  1123
SDSSJ0159
YES, Obs within 3000 days:  1861
SDSSJ0159
========================================
Database index:  81
========================================
Database index:  82
YES, Obs within 3000 days:  0
SDSSJ0952
YES, Obs within 100 days:  0
SDSSJ0952
YES, Obs within 3000 days:  404
SDSSJ0952
YES, Obs within 3000 days:  609
SDSSJ0952
========================================
Database index:  83
========================================
Database index:  84
YES, Obs within 3000 days:  1103
SDSSJ1311
YES, Obs within 3000 days:  737
SDSSJ1311
YES, Obs within 3000 days:  740
SDSSJ1311
YES, Obs within 3000 days:  0
SDSSJ1311
YES, Obs within 100 days:  0
SDSSJ1311
ERROR negative delta days. CHECK DISC DATE!!! -1414
SDSSJ1311
ERROR negative delta days. CHECK DISC DATE!!! -1147
SDSSJ1311
========================================
Database index:  85
========================================
Database index:  86
========================================
Database index:  87
========================================
Database index:  88
========================================
Database index:  89
========================================
Database index:  90
========================================
Database index:  91
========================================
Database index:  92
========================================
Database index:  93
========================================
Database index:  94
========================================
Database index:  95
========================================
Database index:  96
========================================
Database index:  97
========================================
Database index:  98
========================================
Database index:  99
========================================
Database index:  100
========================================
Database index:  101
========================================
Database index:  102
========================================
Database index:  103
YES, Obs within 3000 days:  608
Swift J1644+57
YES, Obs within 3000 days:  1767
Swift J1644+57
YES, Obs within 3000 days:  1832
Swift J1644+57
YES, Obs within 3000 days:  1906
Swift J1644+57
YES, Obs within 3000 days:  2015
Swift J1644+57
YES, Obs within 3000 days:  1607
Swift J1644+57
YES, Obs within 3000 days:  2505
Swift J1644+57
YES, Obs within 3000 days:  2507
Swift J1644+57
YES, Obs within 3000 days:  2511
Swift J1644+57
YES, Obs within 3000 days:  2687
Swift J1644+57
YES, Obs within 3000 days:  2687
Swift J1644+57
YES, Obs within 3000 days:  1421
Swift J1644+57
YES, Obs within 3000 days:  1469
Swift J1644+57
YES, Obs within 3000 days:  6
Swift J1644+57
YES, Obs within 100 days:  6
Swift J1644+57
========================================

In [23]:
print(chan[f'chan_within_{late_epoch}_days'].sum())
print(chan[f'chan_within_{early_epoch}_days'].sum())
# chan.sample(10)
# chan.head(10)

27
10

In [24]:
chan["TDE"].loc[(chan[f'chan_within_{late_epoch}_days'] == True)]

2         2XMMi J184725.1-631724
3          3XMM J150052.0+015452
5          3XMM J215022.4-055108
6                    ASASSN-14ae
7                    ASASSN-14li
8                    ASASSN-15lh
11                     AT2016ezh
12                     AT2017eqx
19                    CXOU J0332
21                        D23H-1
22                         D3-13
23                    DES14C1kia
25                   F01004-2237
29               IGR J17361-4441
30                     iPTF16axa
31                     iPTF16fnl
51                       NGC 247
52                      NGC 3599
59                   PGC 1185375
64                      PS1-10jh
67                      PS1-13jw
78                     SDSSJ0159
80                     SDSSJ0952
82                     SDSSJ1311
101               Swift J1644+57
102               Swift J2058+05
107    WINGS J134849.88+263557.5
Name: TDE, dtype: object

In [25]:
chan["TDE"].loc[(chan[f'chan_within_{early_epoch}_days'] == True)]

7                    ASASSN-14li
12                     AT2017eqx
19                    CXOU J0332
21                        D23H-1
25                   F01004-2237
80                     SDSSJ0952
82                     SDSSJ1311
101               Swift J1644+57
102               Swift J2058+05
107    WINGS J134849.88+263557.5
Name: TDE, dtype: object

In [26]:
chan.loc[(chan[f'chan_within_{late_epoch}_days'] == True)]

,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",Disc Date,TDE,chan_within_3000_days,chan_within_100_days,chan_neg_delta_days?,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100
2,"1: 15637 (2013-03-29, 15070.0, ACIS-S ),",2006/09/01,2XMMi J184725.1-631724,True,False,False,2401,1,None
3,"12: 9517 (2008-06-05, 100060.0, ACIS-S ), 5...",2005/07/23,3XMM J150052.0+015452,True,False,True,1048,9,None
5,"2: 17862 (2016-09-14, 78120.0, ACIS-S ), 679...",2005/05/01,3XMM J215022.4-055108,True,False,False,515,1,None
6,"1: 21503 (2018-11-17, 10060.0, ACIS-S ),",2014/01/25,ASASSN-14ae,True,False,False,1757,1,None
7,"7: 17566 (2014-12-08, 35040.0, HRC-S ), 1756...",2014/11/22,ASASSN-14li,True,True,False,16,7,2
8,"4: 17879 (2015-11-12, 10040.0, ACIS-S ), 1788...",2015/06/14,ASASSN-15lh,True,False,False,151,4,None
11,"5: 16273 (2014-11-27, 6070.0, ACIS-I ), 7750...",2016/08/26,AT2016ezh,True,False,True,867,3,None
12,"4: 20625 (2017-08-16, 10060.0, ACIS-S ), 2143...",2017/06/07,AT2017eqx,True,True,True,70,2,1
19,"100: 5022 (2004-11-15, 80170.0, ACIS-I ), 6...",2014/10/01,CXOU J0332,True,True,True,0,39,22
21,"8: 8609 (2008-08-06, 8960.0, ACIS-I ), 8614...",2007/09/04,D23H-1,True,True,False,27,8,2
22,"69: 9458 (2009-03-18, 6740.0, ACIS-I ), 945...",2004/01/15,D3-13,True,False,False,434,69,None
23,"1: 21439 (2019-03-09, 10800.0, ACIS-S ),",2014/11/11,DES14C1kia,True,False,False,1579,1,None
25,"12: 20786 (2018-10-01, 22540.0, ACIS-I ), 218...",2010/06/25,F01004-2237,True,True,True,70,8,1
29,"2: 12453 (2011-08-29, 2550.0, ACIS-S ), 5505...",2003/03/22,IGR J17361-4441,True,False,False,761,1,None
30,"1: 21436 (2018-11-30, 10110.0, ACIS-S ),",2016/05/29,iPTF16axa,True,False,False,915,1,None
31,"1: 21435 (2019-05-29, 10110.0, ACIS-S ),",2016/08/26,iPTF16fnl,True,False,False,1006,1,None
51,"2: 17547 (2014-11-12, 5070.0, ACIS-S ), 12437...",2014/07/01,NGC 247,True,False,True,134,1,None
52,"1: 9556 (2008-01-26, 20160.0, ACIS-S ),",2002/05/27,NGC 3599,True,False,False,2070,1,None
59,"2: 11330 (2010-09-09, 9960.0, ACIS-S ), 11314...",2010/02/03,PGC 1185375,True,False,False,218,2,None
64,"4: 21502 (2019-07-10, 20060.0, ACIS-S ), 1341...",2010/05/16,PS1-10jh,True,False,True,371,1,None
67,"1: 18229 (2015-12-27, 22060.0, ACIS-S ),",2013/02/06,PS1-13jw,True,False,False,1054,1,None
78,"4: 4104 (2003-08-26, 10720.0, ACIS-S ), 577...",2000/07/29,SDSSJ0159,True,False,False,1123,2,None
80,"3: 9814 (2008-02-05, 9910.0, ACIS-S ), 10727...",2008/02/05,SDSSJ0952,True,True,False,0,3,1
82,"6: 7701 (2007-03-07, 5060.0, ACIS-I ), 6930...",2004/02/28,SDSSJ1311,True,True,True,0,4,1
101,"14: 15584 (2012-11-26, 24970.0, ACIS-S ), 171...",2011/03/29,Swift J1644+57,True,True,False,6,14,1
102,"4: 13423 (2011-06-22, 5190.0, HRC-I ), 14975...",2011/05/27,Swift J2058+05,True,True,False,26,4,1
107,"161: 17612 (2016-12-03, 60040.0, ACIS-I ), 17...",1999/12/20,WINGS J134849.88+263557.5,True,True,False,0,13,2

In [27]:
chan.loc[(chan[f'chan_within_{early_epoch}_days'] == True)]

,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",Disc Date,TDE,chan_within_3000_days,chan_within_100_days,chan_neg_delta_days?,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100
7,"7: 17566 (2014-12-08, 35040.0, HRC-S ), 1756...",2014/11/22,ASASSN-14li,True,True,False,16,7,2
12,"4: 20625 (2017-08-16, 10060.0, ACIS-S ), 2143...",2017/06/07,AT2017eqx,True,True,True,70,2,1
19,"100: 5022 (2004-11-15, 80170.0, ACIS-I ), 6...",2014/10/01,CXOU J0332,True,True,True,0,39,22
21,"8: 8609 (2008-08-06, 8960.0, ACIS-I ), 8614...",2007/09/04,D23H-1,True,True,False,27,8,2
25,"12: 20786 (2018-10-01, 22540.0, ACIS-I ), 218...",2010/06/25,F01004-2237,True,True,True,70,8,1
80,"3: 9814 (2008-02-05, 9910.0, ACIS-S ), 10727...",2008/02/05,SDSSJ0952,True,True,False,0,3,1
82,"6: 7701 (2007-03-07, 5060.0, ACIS-I ), 6930...",2004/02/28,SDSSJ1311,True,True,True,0,4,1
101,"14: 15584 (2012-11-26, 24970.0, ACIS-S ), 171...",2011/03/29,Swift J1644+57,True,True,False,6,14,1
102,"4: 13423 (2011-06-22, 5190.0, HRC-I ), 14975...",2011/05/27,Swift J2058+05,True,True,False,26,4,1
107,"161: 17612 (2016-12-03, 60040.0, ACIS-I ), 17...",1999/12/20,WINGS J134849.88+263557.5,True,True,False,0,13,2

In [28]:
chan.TDE.loc[(chan["chan_neg_delta_days?"] == True)]

3     3XMM J150052.0+015452
4     3XMM J152130.7+074916
11                AT2016ezh
12                AT2017eqx
19               CXOU J0332
24                   Dougie
25              F01004-2237
51                  NGC 247
58              PGC 1127938
64                 PS1-10jh
82                SDSSJ1311
Name: TDE, dtype: object

In [29]:
chan.loc[(chan["chan_neg_delta_days?"] == True)]

,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",Disc Date,TDE,chan_within_3000_days,chan_within_100_days,chan_neg_delta_days?,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100
3,"12: 9517 (2008-06-05, 100060.0, ACIS-S ), 5...",2005/07/23,3XMM J150052.0+015452,True,False,True,1048,9,None
4,"1: 900 (2000-04-03, 58030.0, ACIS-I ),",2000/08/23,3XMM J152130.7+074916,False,None,True,None,None,None
11,"5: 16273 (2014-11-27, 6070.0, ACIS-I ), 7750...",2016/08/26,AT2016ezh,True,False,True,867,3,None
12,"4: 20625 (2017-08-16, 10060.0, ACIS-S ), 2143...",2017/06/07,AT2017eqx,True,True,True,70,2,1
19,"100: 5022 (2004-11-15, 80170.0, ACIS-I ), 6...",2014/10/01,CXOU J0332,True,True,True,0,39,22
24,"1: 1578 (2001-04-03, 15000.0, ACIS-S ),",2009/01/17,Dougie,False,None,True,None,None,None
25,"12: 20786 (2018-10-01, 22540.0, ACIS-I ), 218...",2010/06/25,F01004-2237,True,True,True,70,8,1
51,"2: 17547 (2014-11-12, 5070.0, ACIS-S ), 12437...",2014/07/01,NGC 247,True,False,True,134,1,None
58,"1: 4963 (2005-02-13, 39770.0, ACIS-S ),",2007/01/08,PGC 1127938,False,None,True,None,None,None
64,"4: 21502 (2019-07-10, 20060.0, ACIS-S ), 1341...",2010/05/16,PS1-10jh,True,False,True,371,1,None
82,"6: 7701 (2007-03-07, 5060.0, ACIS-I ), 6930...",2004/02/28,SDSSJ1311,True,True,True,0,4,1

In [30]:
chan.loc[ (chan[f'chan_within_{late_epoch}_days'] == True) 
            & (chan["chan_neg_delta_days?"] == False)
           ]

,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",Disc Date,TDE,chan_within_3000_days,chan_within_100_days,chan_neg_delta_days?,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100
2,"1: 15637 (2013-03-29, 15070.0, ACIS-S ),",2006/09/01,2XMMi J184725.1-631724,True,False,False,2401,1,None
5,"2: 17862 (2016-09-14, 78120.0, ACIS-S ), 679...",2005/05/01,3XMM J215022.4-055108,True,False,False,515,1,None
6,"1: 21503 (2018-11-17, 10060.0, ACIS-S ),",2014/01/25,ASASSN-14ae,True,False,False,1757,1,None
7,"7: 17566 (2014-12-08, 35040.0, HRC-S ), 1756...",2014/11/22,ASASSN-14li,True,True,False,16,7,2
8,"4: 17879 (2015-11-12, 10040.0, ACIS-S ), 1788...",2015/06/14,ASASSN-15lh,True,False,False,151,4,None
21,"8: 8609 (2008-08-06, 8960.0, ACIS-I ), 8614...",2007/09/04,D23H-1,True,True,False,27,8,2
22,"69: 9458 (2009-03-18, 6740.0, ACIS-I ), 945...",2004/01/15,D3-13,True,False,False,434,69,None
23,"1: 21439 (2019-03-09, 10800.0, ACIS-S ),",2014/11/11,DES14C1kia,True,False,False,1579,1,None
29,"2: 12453 (2011-08-29, 2550.0, ACIS-S ), 5505...",2003/03/22,IGR J17361-4441,True,False,False,761,1,None
30,"1: 21436 (2018-11-30, 10110.0, ACIS-S ),",2016/05/29,iPTF16axa,True,False,False,915,1,None
31,"1: 21435 (2019-05-29, 10110.0, ACIS-S ),",2016/08/26,iPTF16fnl,True,False,False,1006,1,None
52,"1: 9556 (2008-01-26, 20160.0, ACIS-S ),",2002/05/27,NGC 3599,True,False,False,2070,1,None
59,"2: 11330 (2010-09-09, 9960.0, ACIS-S ), 11314...",2010/02/03,PGC 1185375,True,False,False,218,2,None
67,"1: 18229 (2015-12-27, 22060.0, ACIS-S ),",2013/02/06,PS1-13jw,True,False,False,1054,1,None
78,"4: 4104 (2003-08-26, 10720.0, ACIS-S ), 577...",2000/07/29,SDSSJ0159,True,False,False,1123,2,None
80,"3: 9814 (2008-02-05, 9910.0, ACIS-S ), 10727...",2008/02/05,SDSSJ0952,True,True,False,0,3,1
101,"14: 15584 (2012-11-26, 24970.0, ACIS-S ), 171...",2011/03/29,Swift J1644+57,True,True,False,6,14,1
102,"4: 13423 (2011-06-22, 5190.0, HRC-I ), 14975...",2011/05/27,Swift J2058+05,True,True,False,26,4,1
107,"161: 17612 (2016-12-03, 60040.0, ACIS-I ), 17...",1999/12/20,WINGS J134849.88+263557.5,True,True,False,0,13,2

In [31]:
print(list(chan.TDE.loc[ (chan[f'chan_within_{late_epoch}_days'] == True) 
            & (chan["chan_neg_delta_days?"] == False)
           ]))

chan_late_list = list(chan.TDE.loc[ (chan[f'chan_within_{late_epoch}_days'] == True) 
            & (chan["chan_neg_delta_days?"] == False)
           ])

print(len(chan_late_list))

['2XMMi J184725.1-631724', '3XMM J215022.4-055108', 'ASASSN-14ae', 'ASASSN-14li', 'ASASSN-15lh', 'D23H-1', 'D3-13', 'DES14C1kia', 'IGR J17361-4441', 'iPTF16axa', 'iPTF16fnl', 'NGC 3599', 'PGC 1185375', 'PS1-13jw', 'SDSSJ0159', 'SDSSJ0952', 'Swift J1644+57', 'Swift J2058+05', 'WINGS J134849.88+263557.5']
19

In [32]:
chan.loc[ (chan[f'chan_within_{early_epoch}_days'] == True) 
            & (chan["chan_neg_delta_days?"] == False)
           ]

,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",Disc Date,TDE,chan_within_3000_days,chan_within_100_days,chan_neg_delta_days?,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100
7,"7: 17566 (2014-12-08, 35040.0, HRC-S ), 1756...",2014/11/22,ASASSN-14li,True,True,False,16,7,2
21,"8: 8609 (2008-08-06, 8960.0, ACIS-I ), 8614...",2007/09/04,D23H-1,True,True,False,27,8,2
80,"3: 9814 (2008-02-05, 9910.0, ACIS-S ), 10727...",2008/02/05,SDSSJ0952,True,True,False,0,3,1
101,"14: 15584 (2012-11-26, 24970.0, ACIS-S ), 171...",2011/03/29,Swift J1644+57,True,True,False,6,14,1
102,"4: 13423 (2011-06-22, 5190.0, HRC-I ), 14975...",2011/05/27,Swift J2058+05,True,True,False,26,4,1
107,"161: 17612 (2016-12-03, 60040.0, ACIS-I ), 17...",1999/12/20,WINGS J134849.88+263557.5,True,True,False,0,13,2

In [33]:
print(list(chan.TDE.loc[ (chan[f'chan_within_{early_epoch}_days'] == True) 
            & (chan["chan_neg_delta_days?"] == False)
           ]))

chan_early_list = list(chan.TDE.loc[ (chan[f'chan_within_{early_epoch}_days'] == True) 
            & (chan["chan_neg_delta_days?"] == False)
           ])

['ASASSN-14li', 'D23H-1', 'SDSSJ0952', 'Swift J1644+57', 'Swift J2058+05', 'WINGS J134849.88+263557.5']

# Swift Data

In [34]:
xamin_files.head(1)

,TDE,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])","XMM TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","XMM Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","XMM Col D ObsID (exp time, date, #days after discovery)","Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)","Chandra TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","Chandra Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","Chandra Col H ObsID (exp time, date, #days after discovery)","Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])","Swift TDE Data (#obs_TDE, minoff_TDE, maxoff_TDE, comment)","Swift Good TDE Data (total #ObsIDs with TDE, unique date, >1000 [sec])","Swift Col L ObsID (exp time, date, #days after discovery)",Disc Date
0,2MASX J01190869-3411305,"10: 0657820101 (2010-12-02, 14913.0), 07409601...","10, 0.0039, 0.017",9.0,"0657820101 (14913.0, 2010-12-02, 154), 0740960...","1: 22096 (2019-02-14, 73570.0, ACIS-S ),","1, 0.0167, 0.0167",1.0,"22096 (73570.0, 2019-02-14, 3150),","32: 00031789003 (2010-08-27, 2073.517), 000317...","32, 0.4007, 24.6643",26.0,"00031789003 (2073.517, 2010-08-27, 57), 000317...",2010/07/14

In [35]:
swift = pd.DataFrame(xamin_files['Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])'])
swift = pd.concat( (swift, xamin_files['Disc Date'], xamin_files['TDE']), axis='columns')
swift[f'swift_within_{late_epoch}_days'] = None
swift[f'swift_within_{early_epoch}_days'] = None
swift['swift_neg_delta_days?'] = None
swift['swift_min_dt'] = None
swift[f'swift_num_dt_within_{late_epoch}'] = None
swift[f'swift_num_dt_within_{early_epoch}'] = None
swift

,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,"32: 00031789003 (2010-08-27, 2073.517), 000317...",2010/07/14,2MASX J01190869-3411305,None,None,None,None,None,None
1,"11: 00032732009 (2014-05-13, 2494.821), 000327...",2003/07/13,2XMM J123103.2+110648,None,None,None,None,None,None
2,"9: 07021936001 (2019-10-01, 72.702), 000319300...",2006/09/01,2XMMi J184725.1-631724,None,None,None,None,None,None
3,"62: 03107787002 (2019-04-07, 95.34), 031077870...",2005/07/23,3XMM J150052.0+015452,None,None,None,None,None,None
4,"2: 00035189001 (2005-09-10, 9555.588), 0001036...",2000/08/23,3XMM J152130.7+074916,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
111,"15: 00033229006 (2014-05-26, 513.208), 0003322...",2014/04/01,XMMSL1 J0740-85,None,None,None,None,None,None
112,"1: 03106172001 (2018-08-14, 576.671),",2005/07/15,XMMSL1 J131952.3+225958,None,None,None,None,None,None
113,"18: 00010584010 (2018-05-30, 2883.386), 000105...",2018/02/15,XMMSL2 J140446.9-251135,None,None,None,None,None,None
114,"23: 00034707020 (2017-03-26, 2219.934), 000347...",2006/08/22,XMMSL2 J144605.0+685735,None,None,None,None,None,None
115,"14: 00010994007 (2018-12-21, 2883.404), 000109...",2018/10/04,ZTF18abxftqm,None,None,None,None,None,None

In [36]:
for index, row in swift.iterrows():
    print("Database index: ",index + 2)
    df_row = pd.DataFrame(row)
#     print(df_row)
    tde = swift['TDE'][index]
    df_row_disc_date = df_row.to_string().split('\n')[2].split()[1]
#     print(df_row_disc_date, type(df_row_disc_date))
    df_row = df_row.to_string().split(')')[1:]
#     print(df_row)

    swift_within_late_epoch = False
    swift_within_early_epoch = False
    swift_neg_delta_days = False
    swift_diff_time_list = []
    swift_diff_supedd_time_list = []

    for i, line in enumerate(df_row):
#         if i == 0:
#             print("Num of Obs Ids: ",line.split(':')[0])
#             print('-'*20)
        if i < len(df_row) - 1:
            if i == 0:
                line = line.split(':')[1].split(' ')[1:]
                # print(line)
                exp_time = float(line[2])
            if i > 0:
                line = line.split(':')[0].split(' ')[1:]
                # print(line)
                exp_time = float(line[2])
            for j, element in enumerate(line):
                element = element.strip('(').strip(',')
#                 print(element)

                if j==1 and exp_time>1e3:  # getting the obervation date for all >1 ksec exposures
                    element = pd.to_datetime(element)
#                     print(type(element))
#                     print(element.year)
#                     disc_date = pd.to_datetime('1950-12-01')
#                     disc_date = pd.to_datetime(swift['Disc Date'][index].split('?')[0])
                    disc_date = pd.to_datetime(swift['Disc Date'][index])
#                     print(disc_date)
                    diff_time = element - disc_date
                    diff_time = diff_time.days
#                     print(diff_time)
    
                    if 0 <= diff_time <= late_epoch:
                        print(f"YES, Obs within {late_epoch} days: ", diff_time)
                        print(tde)
                        swift_within_late_epoch = True
                        swift_diff_time_list.append(diff_time)
                        
                        if 0 <= diff_time <= early_epoch:
                            print(f"YES, Obs within {early_epoch} days: ", diff_time)
                            print(tde)
                            swift_within_early_epoch = True
                            swift_diff_supedd_time_list.append(diff_time)
                        
                    if diff_time < 0:
                        print("ERROR negative delta days. CHECK DISC DATE!!!", diff_time)
                        print(tde)
                        swift_neg_delta_days = True
                    
    if swift_within_late_epoch == True:
        swift[f'swift_within_{late_epoch}_days'][index] = True
        swift['swift_min_dt'][index] = min(swift_diff_time_list)
        swift[f'swift_num_dt_within_{late_epoch}'][index] = len(swift_diff_time_list)
        if swift_within_early_epoch == True:
            swift[f'swift_within_{early_epoch}_days'][index] = True
            swift['swift_min_dt'][index] = min(swift_diff_time_list)
            swift[f'swift_num_dt_within_{early_epoch}'][index] = len(swift_diff_time_list)
        else:
            swift[f'swift_within_{early_epoch}_days'][index] = False
    else:
        swift[f'swift_within_{late_epoch}_days'][index] = False

    if swift_neg_delta_days == True:
        swift['swift_neg_delta_days?'][index] = True
    else:
        swift['swift_neg_delta_days?'][index] = False
                    
#             print('\n')
# #         print('.'*40)
    print('='*40)

Database index:  2
YES, Obs within 3000 days:  44
2MASX J01190869-3411305
YES, Obs within 100 days:  44
2MASX J01190869-3411305
YES, Obs within 3000 days:  285
2MASX J01190869-3411305
YES, Obs within 3000 days:  368
2MASX J01190869-3411305
YES, Obs within 3000 days:  341
2MASX J01190869-3411305
YES, Obs within 3000 days:  2705
2MASX J01190869-3411305
YES, Obs within 3000 days:  313
2MASX J01190869-3411305
YES, Obs within 3000 days:  397
2MASX J01190869-3411305
YES, Obs within 3000 days:  1166
2MASX J01190869-3411305
YES, Obs within 3000 days:  133
2MASX J01190869-3411305
YES, Obs within 3000 days:  105
2MASX J01190869-3411305
YES, Obs within 3000 days:  1173
2MASX J01190869-3411305
YES, Obs within 3000 days:  2721
2MASX J01190869-3411305
YES, Obs within 3000 days:  2715
2MASX J01190869-3411305
YES, Obs within 3000 days:  161
2MASX J01190869-3411305
YES, Obs within 3000 days:  189
2MASX J01190869-3411305
YES, Obs within 3000 days:  217
2MASX J01190869-3411305
========================================
Database index:  3
========================================
Database index:  4
YES, Obs within 3000 days:  1636
2XMMi J184725.1-631724
YES, Obs within 3000 days:  2408
2XMMi J184725.1-631724
YES, Obs within 3000 days:  2564
2XMMi J184725.1-631724
YES, Obs within 3000 days:  2410
2XMMi J184725.1-631724
YES, Obs within 3000 days:  2554
2XMMi J184725.1-631724
========================================
Database index:  5
YES, Obs within 3000 days:  2886
3XMM J150052.0+015452
YES, Obs within 3000 days:  2896
3XMM J150052.0+015452
YES, Obs within 3000 days:  2908
3XMM J150052.0+015452
YES, Obs within 3000 days:  2907
3XMM J150052.0+015452
YES, Obs within 3000 days:  2922
3XMM J150052.0+015452
YES, Obs within 3000 days:  2903
3XMM J150052.0+015452
YES, Obs within 3000 days:  2890
3XMM J150052.0+015452
YES, Obs within 3000 days:  2381
3XMM J150052.0+015452
YES, Obs within 3000 days:  2899
3XMM J150052.0+015452
YES, Obs within 3000 days:  2376
3XMM J150052.0+015452
YES, Obs within 3000 days:  2368
3XMM J150052.0+015452
YES, Obs within 3000 days:  2911
3XMM J150052.0+015452
YES, Obs within 3000 days:  2377
3XMM J150052.0+015452
YES, Obs within 3000 days:  2379
3XMM J150052.0+015452
YES, Obs within 3000 days:  2366
3XMM J150052.0+015452
========================================
Database index:  6
YES, Obs within 3000 days:  1844
3XMM J152130.7+074916
========================================
Database index:  7
========================================
Database index:  8
YES, Obs within 3000 days:  753
ASASSN-14ae
YES, Obs within 3000 days:  57
ASASSN-14ae
YES, Obs within 100 days:  57
ASASSN-14ae
YES, Obs within 3000 days:  122
ASASSN-14ae
YES, Obs within 3000 days:  62
ASASSN-14ae
YES, Obs within 100 days:  62
ASASSN-14ae
YES, Obs within 3000 days:  78
ASASSN-14ae
YES, Obs within 100 days:  78
ASASSN-14ae
YES, Obs within 3000 days:  73
ASASSN-14ae
YES, Obs within 100 days:  73
ASASSN-14ae
YES, Obs within 3000 days:  88
ASASSN-14ae
YES, Obs within 100 days:  88
ASASSN-14ae
YES, Obs within 3000 days:  486
ASASSN-14ae
YES, Obs within 3000 days:  47
ASASSN-14ae
YES, Obs within 100 days:  47
ASASSN-14ae
YES, Obs within 3000 days:  2
ASASSN-14ae
YES, Obs within 100 days:  2
ASASSN-14ae
YES, Obs within 3000 days:  127
ASASSN-14ae
YES, Obs within 3000 days:  143
ASASSN-14ae
YES, Obs within 3000 days:  757
ASASSN-14ae
YES, Obs within 3000 days:  146
ASASSN-14ae
YES, Obs within 3000 days:  480
ASASSN-14ae
YES, Obs within 3000 days:  412
ASASSN-14ae
YES, Obs within 3000 days:  440
ASASSN-14ae
YES, Obs within 3000 days:  56
ASASSN-14ae
YES, Obs within 100 days:  56
ASASSN-14ae
YES, Obs within 3000 days:  15
ASASSN-14ae
YES, Obs within 100 days:  15
ASASSN-14ae
YES, Obs within 3000 days:  81
ASASSN-14ae
YES, Obs within 100 days:  81
ASASSN-14ae
YES, Obs within 3000 days:  117
ASASSN-14ae
YES, Obs within 3000 days:  112
ASASSN-14ae
YES, Obs within 3000 days:  747
ASASSN-14ae
YES, Obs within 3000 days:  20
ASASSN-14ae
YES, Obs within 100 days:  20
ASASSN-14ae
========================================
Database index:  9
YES, Obs within 3000 days:  1241
ASASSN-14li
YES, Obs within 3000 days:  1241
ASASSN-14li
YES, Obs within 3000 days:  1241
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  1241
ASASSN-14li
YES, Obs within 3000 days:  94
ASASSN-14li
YES, Obs within 100 days:  94
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  70
ASASSN-14li
YES, Obs within 100 days:  70
ASASSN-14li
YES, Obs within 3000 days:  1241
ASASSN-14li
YES, Obs within 3000 days:  449
ASASSN-14li
YES, Obs within 3000 days:  82
ASASSN-14li
YES, Obs within 100 days:  82
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  91
ASASSN-14li
YES, Obs within 100 days:  91
ASASSN-14li
YES, Obs within 3000 days:  137
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  97
ASASSN-14li
YES, Obs within 100 days:  97
ASASSN-14li
YES, Obs within 3000 days:  1613
ASASSN-14li
YES, Obs within 3000 days:  571
ASASSN-14li
YES, Obs within 3000 days:  167
ASASSN-14li
YES, Obs within 3000 days:  452
ASASSN-14li
YES, Obs within 3000 days:  1606
ASASSN-14li
YES, Obs within 3000 days:  149
ASASSN-14li
YES, Obs within 3000 days:  106
ASASSN-14li
YES, Obs within 3000 days:  1242
ASASSN-14li
YES, Obs within 3000 days:  1242
ASASSN-14li
YES, Obs within 3000 days:  217
ASASSN-14li
YES, Obs within 3000 days:  143
ASASSN-14li
YES, Obs within 3000 days:  140
ASASSN-14li
YES, Obs within 3000 days:  156
ASASSN-14li
YES, Obs within 3000 days:  134
ASASSN-14li
YES, Obs within 3000 days:  119
ASASSN-14li
YES, Obs within 3000 days:  190
ASASSN-14li
YES, Obs within 3000 days:  211
ASASSN-14li
YES, Obs within 3000 days:  392
ASASSN-14li
YES, Obs within 3000 days:  170
ASASSN-14li
YES, Obs within 3000 days:  563
ASASSN-14li
YES, Obs within 3000 days:  567
ASASSN-14li
YES, Obs within 3000 days:  845
ASASSN-14li
YES, Obs within 3000 days:  202
ASASSN-14li
YES, Obs within 3000 days:  146
ASASSN-14li
YES, Obs within 3000 days:  444
ASASSN-14li
YES, Obs within 3000 days:  116
ASASSN-14li
YES, Obs within 3000 days:  193
ASASSN-14li
YES, Obs within 3000 days:  1242
ASASSN-14li
YES, Obs within 3000 days:  103
ASASSN-14li
YES, Obs within 3000 days:  255
ASASSN-14li
YES, Obs within 3000 days:  536
ASASSN-14li
YES, Obs within 3000 days:  164
ASASSN-14li
YES, Obs within 3000 days:  1241
ASASSN-14li
YES, Obs within 3000 days:  843
ASASSN-14li
YES, Obs within 3000 days:  128
ASASSN-14li
YES, Obs within 3000 days:  543
ASASSN-14li
YES, Obs within 3000 days:  1592
ASASSN-14li
YES, Obs within 3000 days:  357
ASASSN-14li
YES, Obs within 3000 days:  386
ASASSN-14li
YES, Obs within 3000 days:  559
ASASSN-14li
YES, Obs within 3000 days:  122
ASASSN-14li
YES, Obs within 3000 days:  59
ASASSN-14li
YES, Obs within 100 days:  59
ASASSN-14li
YES, Obs within 3000 days:  62
ASASSN-14li
YES, Obs within 100 days:  62
ASASSN-14li
YES, Obs within 3000 days:  1627
ASASSN-14li
YES, Obs within 3000 days:  1633
ASASSN-14li
YES, Obs within 3000 days:  389
ASASSN-14li
YES, Obs within 3000 days:  173
ASASSN-14li
YES, Obs within 3000 days:  368
ASASSN-14li
YES, Obs within 3000 days:  125
ASASSN-14li
YES, Obs within 3000 days:  1240
ASASSN-14li
YES, Obs within 3000 days:  24
ASASSN-14li
YES, Obs within 100 days:  24
ASASSN-14li
YES, Obs within 3000 days:  88
ASASSN-14li
YES, Obs within 100 days:  88
ASASSN-14li
YES, Obs within 3000 days:  1242
ASASSN-14li
YES, Obs within 3000 days:  199
ASASSN-14li
YES, Obs within 3000 days:  153
ASASSN-14li
YES, Obs within 3000 days:  220
ASASSN-14li
YES, Obs within 3000 days:  36
ASASSN-14li
YES, Obs within 100 days:  36
ASASSN-14li
YES, Obs within 3000 days:  1242
ASASSN-14li
YES, Obs within 3000 days:  18
ASASSN-14li
YES, Obs within 100 days:  18
ASASSN-14li
YES, Obs within 3000 days:  1242
ASASSN-14li
YES, Obs within 3000 days:  56
ASASSN-14li
YES, Obs within 100 days:  56
ASASSN-14li
YES, Obs within 3000 days:  208
ASASSN-14li
YES, Obs within 3000 days:  39
ASASSN-14li
YES, Obs within 100 days:  39
ASASSN-14li
YES, Obs within 3000 days:  434
ASASSN-14li
YES, Obs within 3000 days:  539
ASASSN-14li
YES, Obs within 3000 days:  253
ASASSN-14li
YES, Obs within 3000 days:  8
ASASSN-14li
YES, Obs within 100 days:  8
ASASSN-14li
YES, Obs within 3000 days:  53
ASASSN-14li
YES, Obs within 100 days:  53
ASASSN-14li
YES, Obs within 3000 days:  46
ASASSN-14li
YES, Obs within 100 days:  46
ASASSN-14li
YES, Obs within 3000 days:  30
ASASSN-14li
YES, Obs within 100 days:  30
ASASSN-14li
YES, Obs within 3000 days:  65
ASASSN-14li
YES, Obs within 100 days:  65
ASASSN-14li
YES, Obs within 3000 days:  50
ASASSN-14li
YES, Obs within 100 days:  50
ASASSN-14li
YES, Obs within 3000 days:  131
ASASSN-14li
YES, Obs within 3000 days:  263
ASASSN-14li
YES, Obs within 3000 days:  395
ASASSN-14li
YES, Obs within 3000 days:  27
ASASSN-14li
YES, Obs within 100 days:  27
ASASSN-14li
YES, Obs within 3000 days:  76
ASASSN-14li
YES, Obs within 100 days:  76
ASASSN-14li
YES, Obs within 3000 days:  33
ASASSN-14li
YES, Obs within 100 days:  33
ASASSN-14li
YES, Obs within 3000 days:  428
ASASSN-14li
YES, Obs within 3000 days:  259
ASASSN-14li
YES, Obs within 3000 days:  837
ASASSN-14li
YES, Obs within 3000 days:  15
ASASSN-14li
YES, Obs within 100 days:  15
ASASSN-14li
YES, Obs within 3000 days:  21
ASASSN-14li
YES, Obs within 100 days:  21
ASASSN-14li
YES, Obs within 3000 days:  12
ASASSN-14li
YES, Obs within 100 days:  12
ASASSN-14li
YES, Obs within 3000 days:  68
ASASSN-14li
YES, Obs within 100 days:  68
ASASSN-14li
YES, Obs within 3000 days:  74
ASASSN-14li
YES, Obs within 100 days:  74
ASASSN-14li
YES, Obs within 3000 days:  380
ASASSN-14li
YES, Obs within 3000 days:  85
ASASSN-14li
YES, Obs within 100 days:  85
ASASSN-14li
YES, Obs within 3000 days:  243
ASASSN-14li
YES, Obs within 3000 days:  838
ASASSN-14li
YES, Obs within 3000 days:  735
ASASSN-14li
YES, Obs within 3000 days:  377
ASASSN-14li
YES, Obs within 3000 days:  10
ASASSN-14li
YES, Obs within 100 days:  10
ASASSN-14li
YES, Obs within 3000 days:  371
ASASSN-14li
YES, Obs within 3000 days:  383
ASASSN-14li
YES, Obs within 3000 days:  374
ASASSN-14li
========================================
Database index:  10
YES, Obs within 3000 days:  300
ASASSN-15lh
YES, Obs within 3000 days:  250
ASASSN-15lh
YES, Obs within 3000 days:  30
ASASSN-15lh
YES, Obs within 100 days:  30
ASASSN-15lh
YES, Obs within 3000 days:  242
ASASSN-15lh
YES, Obs within 3000 days:  501
ASASSN-15lh
YES, Obs within 3000 days:  270
ASASSN-15lh
YES, Obs within 3000 days:  302
ASASSN-15lh
YES, Obs within 3000 days:  318
ASASSN-15lh
YES, Obs within 3000 days:  290
ASASSN-15lh
YES, Obs within 3000 days:  209
ASASSN-15lh
YES, Obs within 3000 days:  34
ASASSN-15lh
YES, Obs within 100 days:  34
ASASSN-15lh
YES, Obs within 3000 days:  336
ASASSN-15lh
YES, Obs within 3000 days:  321
ASASSN-15lh
YES, Obs within 3000 days:  103
ASASSN-15lh
YES, Obs within 3000 days:  21
ASASSN-15lh
YES, Obs within 100 days:  21
ASASSN-15lh
YES, Obs within 3000 days:  212
ASASSN-15lh
YES, Obs within 3000 days:  278
ASASSN-15lh
YES, Obs within 3000 days:  694
ASASSN-15lh
YES, Obs within 3000 days:  611
ASASSN-15lh
YES, Obs within 3000 days:  269
ASASSN-15lh
YES, Obs within 3000 days:  404
ASASSN-15lh
YES, Obs within 3000 days:  288
ASASSN-15lh
YES, Obs within 3000 days:  246
ASASSN-15lh
YES, Obs within 3000 days:  324
ASASSN-15lh
YES, Obs within 3000 days:  283
ASASSN-15lh
YES, Obs within 3000 days:  120
ASASSN-15lh
YES, Obs within 3000 days:  329
ASASSN-15lh
YES, Obs within 3000 days:  266
ASASSN-15lh
YES, Obs within 3000 days:  12
ASASSN-15lh
YES, Obs within 100 days:  12
ASASSN-15lh
YES, Obs within 3000 days:  45
ASASSN-15lh
YES, Obs within 100 days:  45
ASASSN-15lh
YES, Obs within 3000 days:  138
ASASSN-15lh
YES, Obs within 3000 days:  143
ASASSN-15lh
YES, Obs within 3000 days:  29
ASASSN-15lh
YES, Obs within 100 days:  29
ASASSN-15lh
YES, Obs within 3000 days:  373
ASASSN-15lh
YES, Obs within 3000 days:  607
ASASSN-15lh
YES, Obs within 3000 days:  178
ASASSN-15lh
YES, Obs within 3000 days:  333
ASASSN-15lh
YES, Obs within 3000 days:  33
ASASSN-15lh
YES, Obs within 100 days:  33
ASASSN-15lh
YES, Obs within 3000 days:  517
ASASSN-15lh
YES, Obs within 3000 days:  32
ASASSN-15lh
YES, Obs within 100 days:  32
ASASSN-15lh
YES, Obs within 3000 days:  42
ASASSN-15lh
YES, Obs within 100 days:  42
ASASSN-15lh
YES, Obs within 3000 days:  24
ASASSN-15lh
YES, Obs within 100 days:  24
ASASSN-15lh
YES, Obs within 3000 days:  328
ASASSN-15lh
YES, Obs within 3000 days:  96
ASASSN-15lh
YES, Obs within 100 days:  96
ASASSN-15lh
YES, Obs within 3000 days:  539
ASASSN-15lh
YES, Obs within 3000 days:  315
ASASSN-15lh
YES, Obs within 3000 days:  190
ASASSN-15lh
YES, Obs within 3000 days:  85
ASASSN-15lh
YES, Obs within 100 days:  85
ASASSN-15lh
YES, Obs within 3000 days:  292
ASASSN-15lh
YES, Obs within 3000 days:  262
ASASSN-15lh
YES, Obs within 3000 days:  36
ASASSN-15lh
YES, Obs within 100 days:  36
ASASSN-15lh
YES, Obs within 3000 days:  435
ASASSN-15lh
YES, Obs within 3000 days:  260
ASASSN-15lh
YES, Obs within 3000 days:  61
ASASSN-15lh
YES, Obs within 100 days:  61
ASASSN-15lh
YES, Obs within 3000 days:  90
ASASSN-15lh
YES, Obs within 100 days:  90
ASASSN-15lh
YES, Obs within 3000 days:  365
ASASSN-15lh
YES, Obs within 3000 days:  206
ASASSN-15lh
YES, Obs within 3000 days:  370
ASASSN-15lh
YES, Obs within 3000 days:  606
ASASSN-15lh
YES, Obs within 3000 days:  439
ASASSN-15lh
YES, Obs within 3000 days:  85
ASASSN-15lh
YES, Obs within 100 days:  85
ASASSN-15lh
YES, Obs within 3000 days:  27
ASASSN-15lh
YES, Obs within 100 days:  27
ASASSN-15lh
YES, Obs within 3000 days:  181
ASASSN-15lh
YES, Obs within 3000 days:  340
ASASSN-15lh
YES, Obs within 3000 days:  445
ASASSN-15lh
YES, Obs within 3000 days:  54
ASASSN-15lh
YES, Obs within 100 days:  54
ASASSN-15lh
YES, Obs within 3000 days:  129
ASASSN-15lh
YES, Obs within 3000 days:  500
ASASSN-15lh
YES, Obs within 3000 days:  458
ASASSN-15lh
YES, Obs within 3000 days:  495
ASASSN-15lh
YES, Obs within 3000 days:  124
ASASSN-15lh
YES, Obs within 3000 days:  443
ASASSN-15lh
YES, Obs within 3000 days:  39
ASASSN-15lh
YES, Obs within 100 days:  39
ASASSN-15lh
YES, Obs within 3000 days:  414
ASASSN-15lh
YES, Obs within 3000 days:  81
ASASSN-15lh
YES, Obs within 100 days:  81
ASASSN-15lh
YES, Obs within 3000 days:  543
ASASSN-15lh
YES, Obs within 3000 days:  240
ASASSN-15lh
YES, Obs within 3000 days:  75
ASASSN-15lh
YES, Obs within 100 days:  75
ASASSN-15lh
YES, Obs within 3000 days:  10
ASASSN-15lh
YES, Obs within 100 days:  10
ASASSN-15lh
YES, Obs within 3000 days:  169
ASASSN-15lh
YES, Obs within 3000 days:  367
ASASSN-15lh
YES, Obs within 3000 days:  480
ASASSN-15lh
YES, Obs within 3000 days:  424
ASASSN-15lh
YES, Obs within 3000 days:  14
ASASSN-15lh
YES, Obs within 100 days:  14
ASASSN-15lh
YES, Obs within 3000 days:  95
ASASSN-15lh
YES, Obs within 100 days:  95
ASASSN-15lh
YES, Obs within 3000 days:  141
ASASSN-15lh
YES, Obs within 3000 days:  68
ASASSN-15lh
YES, Obs within 100 days:  68
ASASSN-15lh
YES, Obs within 3000 days:  111
ASASSN-15lh
YES, Obs within 3000 days:  453
ASASSN-15lh
YES, Obs within 3000 days:  144
ASASSN-15lh
YES, Obs within 3000 days:  156
ASASSN-15lh
YES, Obs within 3000 days:  18
ASASSN-15lh
YES, Obs within 100 days:  18
ASASSN-15lh
YES, Obs within 3000 days:  428
ASASSN-15lh
YES, Obs within 3000 days:  63
ASASSN-15lh
YES, Obs within 100 days:  63
ASASSN-15lh
YES, Obs within 3000 days:  527
ASASSN-15lh
YES, Obs within 3000 days:  162
ASASSN-15lh
YES, Obs within 3000 days:  57
ASASSN-15lh
YES, Obs within 100 days:  57
ASASSN-15lh
YES, Obs within 3000 days:  1137
ASASSN-15lh
YES, Obs within 3000 days:  97
ASASSN-15lh
YES, Obs within 100 days:  97
ASASSN-15lh
YES, Obs within 3000 days:  147
ASASSN-15lh
YES, Obs within 3000 days:  122
ASASSN-15lh
YES, Obs within 3000 days:  115
ASASSN-15lh
YES, Obs within 3000 days:  175
ASASSN-15lh
YES, Obs within 3000 days:  118
ASASSN-15lh
YES, Obs within 3000 days:  490
ASASSN-15lh
YES, Obs within 3000 days:  397
ASASSN-15lh
YES, Obs within 3000 days:  570
ASASSN-15lh
YES, Obs within 3000 days:  193
ASASSN-15lh
YES, Obs within 3000 days:  382
ASASSN-15lh
YES, Obs within 3000 days:  109
ASASSN-15lh
YES, Obs within 3000 days:  126
ASASSN-15lh
YES, Obs within 3000 days:  184
ASASSN-15lh
YES, Obs within 3000 days:  112
ASASSN-15lh
YES, Obs within 3000 days:  159
ASASSN-15lh
YES, Obs within 3000 days:  187
ASASSN-15lh
YES, Obs within 3000 days:  421
ASASSN-15lh
YES, Obs within 3000 days:  97
ASASSN-15lh
YES, Obs within 100 days:  97
ASASSN-15lh
YES, Obs within 3000 days:  132
ASASSN-15lh
YES, Obs within 3000 days:  172
ASASSN-15lh
YES, Obs within 3000 days:  467
ASASSN-15lh
YES, Obs within 3000 days:  196
ASASSN-15lh
YES, Obs within 3000 days:  376
ASASSN-15lh
YES, Obs within 3000 days:  106
ASASSN-15lh
YES, Obs within 3000 days:  390
ASASSN-15lh
YES, Obs within 3000 days:  559
ASASSN-15lh
YES, Obs within 3000 days:  72
ASASSN-15lh
YES, Obs within 100 days:  72
ASASSN-15lh
YES, Obs within 3000 days:  130
ASASSN-15lh
YES, Obs within 3000 days:  421
ASASSN-15lh
========================================
Database index:  11
YES, Obs within 3000 days:  1422
ASASSN-15oi
YES, Obs within 3000 days:  1408
ASASSN-15oi
YES, Obs within 3000 days:  332
ASASSN-15oi
YES, Obs within 3000 days:  1415
ASASSN-15oi
YES, Obs within 3000 days:  280
ASASSN-15oi
YES, Obs within 3000 days:  1429
ASASSN-15oi
YES, Obs within 3000 days:  273
ASASSN-15oi
YES, Obs within 3000 days:  43
ASASSN-15oi
YES, Obs within 100 days:  43
ASASSN-15oi
YES, Obs within 3000 days:  324
ASASSN-15oi
YES, Obs within 3000 days:  28
ASASSN-15oi
YES, Obs within 100 days:  28
ASASSN-15oi
YES, Obs within 3000 days:  1447
ASASSN-15oi
YES, Obs within 3000 days:  596
ASASSN-15oi
YES, Obs within 3000 days:  16
ASASSN-15oi
YES, Obs within 100 days:  16
ASASSN-15oi
YES, Obs within 3000 days:  32
ASASSN-15oi
YES, Obs within 100 days:  32
ASASSN-15oi
YES, Obs within 3000 days:  79
ASASSN-15oi
YES, Obs within 100 days:  79
ASASSN-15oi
YES, Obs within 3000 days:  253
ASASSN-15oi
YES, Obs within 3000 days:  258
ASASSN-15oi
YES, Obs within 3000 days:  266
ASASSN-15oi
YES, Obs within 3000 days:  1450
ASASSN-15oi
YES, Obs within 3000 days:  212
ASASSN-15oi
YES, Obs within 3000 days:  228
ASASSN-15oi
YES, Obs within 3000 days:  61
ASASSN-15oi
YES, Obs within 100 days:  61
ASASSN-15oi
YES, Obs within 3000 days:  245
ASASSN-15oi
YES, Obs within 3000 days:  58
ASASSN-15oi
YES, Obs within 100 days:  58
ASASSN-15oi
YES, Obs within 3000 days:  1394
ASASSN-15oi
YES, Obs within 3000 days:  64
ASASSN-15oi
YES, Obs within 100 days:  64
ASASSN-15oi
YES, Obs within 3000 days:  85
ASASSN-15oi
YES, Obs within 100 days:  85
ASASSN-15oi
YES, Obs within 3000 days:  352
ASASSN-15oi
YES, Obs within 3000 days:  70
ASASSN-15oi
YES, Obs within 100 days:  70
ASASSN-15oi
YES, Obs within 3000 days:  20
ASASSN-15oi
YES, Obs within 100 days:  20
ASASSN-15oi
YES, Obs within 3000 days:  91
ASASSN-15oi
YES, Obs within 100 days:  91
ASASSN-15oi
YES, Obs within 3000 days:  1436
ASASSN-15oi
YES, Obs within 3000 days:  1457
ASASSN-15oi
YES, Obs within 3000 days:  82
ASASSN-15oi
YES, Obs within 100 days:  82
ASASSN-15oi
YES, Obs within 3000 days:  37
ASASSN-15oi
YES, Obs within 100 days:  37
ASASSN-15oi
YES, Obs within 3000 days:  345
ASASSN-15oi
YES, Obs within 3000 days:  338
ASASSN-15oi
YES, Obs within 3000 days:  55
ASASSN-15oi
YES, Obs within 100 days:  55
ASASSN-15oi
YES, Obs within 3000 days:  52
ASASSN-15oi
YES, Obs within 100 days:  52
ASASSN-15oi
YES, Obs within 3000 days:  94
ASASSN-15oi
YES, Obs within 100 days:  94
ASASSN-15oi
YES, Obs within 3000 days:  76
ASASSN-15oi
YES, Obs within 100 days:  76
ASASSN-15oi
YES, Obs within 3000 days:  46
ASASSN-15oi
YES, Obs within 100 days:  46
ASASSN-15oi
YES, Obs within 3000 days:  24
ASASSN-15oi

In [37]:
print(swift[f'swift_within_{late_epoch}_days'].sum())
print(swift[f'swift_within_{early_epoch}_days'].sum())
# swift.sample(10)
# swift.head(10)

52
29

In [38]:
swift["TDE"].loc[(swift[f'swift_within_{late_epoch}_days'] == True)]

0        2MASX J01190869-3411305
2         2XMMi J184725.1-631724
3          3XMM J150052.0+015452
4          3XMM J152130.7+074916
6                    ASASSN-14ae
7                    ASASSN-14li
8                    ASASSN-15lh
9                    ASASSN-15oi
11                     AT2016ezh
12                     AT2017eqx
14                      AT2018zr
16                     AT2019dsg
18                     CSS100217
19                    CXOU J0332
23                    DES14C1kia
24                        Dougie
29               IGR J17361-4441
30                     iPTF16axa
31                     iPTF16fnl
50                MAXI J1807+132
51                       NGC 247
52                      NGC 3599
55                     OGLE16aaa
56                     OGLE17aaj
60                   PGC 1190358
63                     PS1-10adi
64                      PS1-10jh
65                      PS1-11af
67                      PS1-13jw
68                      PTF09axc
69                      PTF09djl
70                       PTF09ge
71                      PTF10iya
73                      PTF11glr
80                     SDSSJ0952
81                  SDSSJ1201+30
83                     SDSSJ1323
84                     SDSSJ1342
86                     SN2017bcc
100               Swift J1112-82
101               Swift J1644+57
102               Swift J2058+05
103                         TDE1
104                         TDE2
105                    UGC 01791
107    WINGS J134849.88+263557.5
108      XMMSL1 J024916.6-041244
109      XMMSL1 J061927.1-655311
110      XMMSL1 J063045.9-603110
111              XMMSL1 J0740-85
113      XMMSL2 J140446.9-251135
115                 ZTF18abxftqm
Name: TDE, dtype: object

In [39]:
swift["TDE"].loc[(swift[f'swift_within_{early_epoch}_days'] == True)]

0      2MASX J01190869-3411305
6                  ASASSN-14ae
7                  ASASSN-14li
8                  ASASSN-15lh
9                  ASASSN-15oi
11                   AT2016ezh
12                   AT2017eqx
14                    AT2018zr
16                   AT2019dsg
19                  CXOU J0332
23                  DES14C1kia
24                      Dougie
30                   iPTF16axa
31                   iPTF16fnl
50              MAXI J1807+132
55                   OGLE16aaa
63                   PS1-10adi
71                    PTF10iya
73                    PTF11glr
81                SDSSJ1201+30
84                   SDSSJ1342
86                   SN2017bcc
101             Swift J1644+57
102             Swift J2058+05
109    XMMSL1 J061927.1-655311
110    XMMSL1 J063045.9-603110
111            XMMSL1 J0740-85
113    XMMSL2 J140446.9-251135
115               ZTF18abxftqm
Name: TDE, dtype: object

In [40]:
swift.loc[(swift[f'swift_within_{late_epoch}_days'] == True)]

,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,"32: 00031789003 (2010-08-27, 2073.517), 000317...",2010/07/14,2MASX J01190869-3411305,True,True,False,44,16,16
2,"9: 07021936001 (2019-10-01, 72.702), 000319300...",2006/09/01,2XMMi J184725.1-631724,True,False,False,1636,5,None
3,"62: 03107787002 (2019-04-07, 95.34), 031077870...",2005/07/23,3XMM J150052.0+015452,True,False,False,2366,15,None
4,"2: 00035189001 (2005-09-10, 9555.588), 0001036...",2000/08/23,3XMM J152130.7+074916,True,False,False,1844,1,None
6,"30: 00033130007 (2014-03-18, 471.367), 0003313...",2014/01/25,ASASSN-14ae,True,True,False,2,24,24
7,"131: 00094094009 (2018-04-16, 1597.154), 00094...",2014/11/22,ASASSN-14li,True,True,False,8,114,114
8,"153: 00033886021 (2016-04-09, 1078.609), 00033...",2015/06/14,ASASSN-15lh,True,True,False,10,128,128
9,"59: 00095141005 (2019-07-06, 1807.381), 000951...",2015/08/14,ASASSN-15oi,True,True,False,11,49,49
11,"83: 00034704007 (2016-09-22, 1901.209), 000347...",2016/08/26,AT2016ezh,True,True,False,6,70,70
12,"18: 00010197006 (2017-08-08, 732.237), 0001019...",2017/06/07,AT2017eqx,True,True,True,34,10,10
14,"45: 00095142009 (2019-12-18, 2415.476), 000951...",2018/03/06,AT2018zr,True,True,False,21,40,40
16,"34: 00011396011 (2019-06-14, 908.154), 0001139...",2019/04/09,AT2019dsg,True,True,False,38,17,17
18,"13: 00049878002 (2020-02-28, 1652.021), 000316...",2002/12/31,CSS100217,True,False,False,2653,4,None
19,"100: 00032648001 (2012-12-18, 1266.717), 00032...",2014/10/01,CXOU J0332,True,True,True,4,10,10
23,"21: 00033565005 (2015-02-04, 2444.2), 00033565...",2014/11/11,DES14C1kia,True,True,False,56,18,18
24,"13: 03107573001 (2018-10-03, 584.195), 0003133...",2009/01/17,Dougie,True,True,False,11,8,8
29,"56: 00091446003 (2012-06-16, 983.05), 00091446...",2003/03/22,IGR J17361-4441,True,False,False,2607,1,None
30,"16: 00034572008 (2016-07-16, 717.081), 0003457...",2016/05/29,iPTF16axa,True,True,False,14,10,10
31,"36: 00034706002 (2016-09-05, 1877.956), 000347...",2016/08/26,iPTF16fnl,True,True,False,4,32,32
50,"48: 00010032001 (2017-03-26, 191.051), 0001003...",2017/03/15,MAXI J1807+132,True,True,False,12,17,17
51,"100: 00095158004 (2019-08-22, 1226.064), 00095...",2014/07/01,NGC 247,True,False,False,104,73,None
52,"10: 03108247001 (2018-07-19, 526.528), 0008436...",2002/05/27,NGC 3599,True,False,False,1649,1,None
55,"32: 00034281015 (2016-06-05, 1670.874), 000342...",2015/12/17,OGLE16aaa,True,True,False,33,23,23
56,"18: 00034916017 (2018-06-15, 932.71), 00034916...",2016/01/28,OGLE17aaj,True,False,False,362,11,None
60,"19: 00033708011 (2015-04-27, 1914.298), 031067...",2009/12/29,PGC 1190358,True,False,False,1906,15,None
63,"21: 03109704008 (2020-03-21, 220.633), 0310970...",2010/08/15,PS1-10adi,True,True,False,52,6,6
64,"5: 00021005002 (2020-06-28, 4531.74), 00021005...",2010/05/16,PS1-10jh,True,False,False,1428,3,None
65,"1: 00010349001 (2017-11-02, 5205.131),",2010/12/30,PS1-11af,True,False,False,2499,1,None
67,"19: 00049882005 (2019-02-23, 616.791), 0004988...",2013/02/06,PS1-13jw,True,False,True,2066,4,None
68,"9: 00033154007 (2014-04-05, 147.306), 00033154...",2009/06/20,PTF09axc,True,False,False,2095,1,None
69,"10: 00075577003 (2020-06-23, 69.066), 00075577...",2009/07/24,PTF09djl,True,False,False,1691,1,None
70,"8: 00033153002 (2014-03-11, 903.346), 00033153...",2009/05/07,PTF09ge,True,False,False,1765,1,None
71,"9: 00031737004 (2011-08-24, 1251.13), 00031737...",2010/06/11,PTF10iya,True,True,False,0,8,8
73,"1: 00032056001 (2011-08-11, 3981.745),",2011/05/28,PTF11glr,True,True,False,75,1,1
80,"7: 00092115005 (2015-04-17, 253.019), 00092115...",2008/02/05,SDSSJ0952,True,False,False,2627,2,None
81,"12: 03109080001 (2018-07-29, 47.629), 00031743...",2010/06/10,SDSSJ1201+30,True,True,False,10,10,10
83,"9: 00020309007 (2013-10-30, 158.917), 00020311...",2003/12/02,SDSSJ1323,True,False,False,1136,3,None
84,"3: 00090102003 (2009-05-20, 3279.528), 0009010...",2009/05/17,SDSSJ1342,True,True,True,0,2,2
86,"13: 00034971005 (2017-04-16, 1515.965), 000349...",2017/02/18,SN2017bcc,True,True,False,20,11,11
100,"13: 00032025010 (2011-07-31, 3048.874), 000320...",2011/12/27,Swift J1112-82,True,False,True,824,3,None
101,"987: 00033765007 (2015-06-13, 491.56), 0003376...",2011/03/29,Swift J1644+57,True,True,True,0,779,779
102,"32: 00032026003 (2011-07-11, 2311.727), 000320...",2011/05/27,Swift J2058+05,True,True,False,0,32,32
103,"2: 00045850001 (2012-05-04, 724.18), 000458500...",2006/08/27,TDE1,True,False,False,2276,1,None
104,"3: 00010348001 (2017-10-28, 4951.643), 0003975...",2007/06/18,TDE2,True,False,False,861,2,None
105,"9: 00054200008 (2005-10-14, 1046.905), 0005420...",2005/01/09,UGC 01791,True,False,False,278,3,None
107,"3: 00035184002 (2005-11-12, 13347.422), 000351...",1999/12/20,WINGS J134849.88+263557.5,True,False,False,2153,3,None
108,"18: 00040306012 (2021-06-18, 3949.505), 000403...",2004/07/24,XMMSL1 J024916.6-041244,True,False,False,1068,2,None
109,"13: 00032633012 (2013-07-08, 1953.621), 000326...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,13,13,13
110,"5: 00032225003 (2012-01-11, 596.732), 00032225...",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,19,3,3
111,"15: 00033229006 (2014-05-26, 513.208), 0003322...",2014/04/01,XMMSL1 J0740-85,True,True,False,13,13,13
113,"18: 00010584010 (2018-05-30, 2883.386), 000105...",2018/02/15,XMMSL2 J140446.9-251135,True,True,True,13,13,13
115,"14: 00010994007 (2018-12-21, 2883.404), 000109...",2018/10/04,ZTF18abxftqm,True,True,False,56,13,13

In [41]:
swift.loc[(swift[f'swift_within_{early_epoch}_days'] == True)]

,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,"32: 00031789003 (2010-08-27, 2073.517), 000317...",2010/07/14,2MASX J01190869-3411305,True,True,False,44,16,16
6,"30: 00033130007 (2014-03-18, 471.367), 0003313...",2014/01/25,ASASSN-14ae,True,True,False,2,24,24
7,"131: 00094094009 (2018-04-16, 1597.154), 00094...",2014/11/22,ASASSN-14li,True,True,False,8,114,114
8,"153: 00033886021 (2016-04-09, 1078.609), 00033...",2015/06/14,ASASSN-15lh,True,True,False,10,128,128
9,"59: 00095141005 (2019-07-06, 1807.381), 000951...",2015/08/14,ASASSN-15oi,True,True,False,11,49,49
11,"83: 00034704007 (2016-09-22, 1901.209), 000347...",2016/08/26,AT2016ezh,True,True,False,6,70,70
12,"18: 00010197006 (2017-08-08, 732.237), 0001019...",2017/06/07,AT2017eqx,True,True,True,34,10,10
14,"45: 00095142009 (2019-12-18, 2415.476), 000951...",2018/03/06,AT2018zr,True,True,False,21,40,40
16,"34: 00011396011 (2019-06-14, 908.154), 0001139...",2019/04/09,AT2019dsg,True,True,False,38,17,17
19,"100: 00032648001 (2012-12-18, 1266.717), 00032...",2014/10/01,CXOU J0332,True,True,True,4,10,10
23,"21: 00033565005 (2015-02-04, 2444.2), 00033565...",2014/11/11,DES14C1kia,True,True,False,56,18,18
24,"13: 03107573001 (2018-10-03, 584.195), 0003133...",2009/01/17,Dougie,True,True,False,11,8,8
30,"16: 00034572008 (2016-07-16, 717.081), 0003457...",2016/05/29,iPTF16axa,True,True,False,14,10,10
31,"36: 00034706002 (2016-09-05, 1877.956), 000347...",2016/08/26,iPTF16fnl,True,True,False,4,32,32
50,"48: 00010032001 (2017-03-26, 191.051), 0001003...",2017/03/15,MAXI J1807+132,True,True,False,12,17,17
55,"32: 00034281015 (2016-06-05, 1670.874), 000342...",2015/12/17,OGLE16aaa,True,True,False,33,23,23
63,"21: 03109704008 (2020-03-21, 220.633), 0310970...",2010/08/15,PS1-10adi,True,True,False,52,6,6
71,"9: 00031737004 (2011-08-24, 1251.13), 00031737...",2010/06/11,PTF10iya,True,True,False,0,8,8
73,"1: 00032056001 (2011-08-11, 3981.745),",2011/05/28,PTF11glr,True,True,False,75,1,1
81,"12: 03109080001 (2018-07-29, 47.629), 00031743...",2010/06/10,SDSSJ1201+30,True,True,False,10,10,10
84,"3: 00090102003 (2009-05-20, 3279.528), 0009010...",2009/05/17,SDSSJ1342,True,True,True,0,2,2
86,"13: 00034971005 (2017-04-16, 1515.965), 000349...",2017/02/18,SN2017bcc,True,True,False,20,11,11
101,"987: 00033765007 (2015-06-13, 491.56), 0003376...",2011/03/29,Swift J1644+57,True,True,True,0,779,779
102,"32: 00032026003 (2011-07-11, 2311.727), 000320...",2011/05/27,Swift J2058+05,True,True,False,0,32,32
109,"13: 00032633012 (2013-07-08, 1953.621), 000326...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,13,13,13
110,"5: 00032225003 (2012-01-11, 596.732), 00032225...",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,19,3,3
111,"15: 00033229006 (2014-05-26, 513.208), 0003322...",2014/04/01,XMMSL1 J0740-85,True,True,False,13,13,13
113,"18: 00010584010 (2018-05-30, 2883.386), 000105...",2018/02/15,XMMSL2 J140446.9-251135,True,True,True,13,13,13
115,"14: 00010994007 (2018-12-21, 2883.404), 000109...",2018/10/04,ZTF18abxftqm,True,True,False,56,13,13

In [42]:
swift.TDE.loc[(swift["swift_neg_delta_days?"] == True)]

10                 ASASSN-20il
12                   AT2017eqx
19                  CXOU J0332
47                     J155223
67                    PS1-13jw
84                   SDSSJ1342
100             Swift J1112-82
101             Swift J1644+57
113    XMMSL2 J140446.9-251135
Name: TDE, dtype: object

In [43]:
swift.loc[(swift["swift_neg_delta_days?"] == True)]

,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
10,"13: 00010296002 (2017-09-21, 1028.172), 031047...",2020/07/08,ASASSN-20il,False,None,True,None,None,None
12,"18: 00010197006 (2017-08-08, 732.237), 0001019...",2017/06/07,AT2017eqx,True,True,True,34,10,10
19,"100: 00032648001 (2012-12-18, 1266.717), 00032...",2014/10/01,CXOU J0332,True,True,True,4,10,10
47,"8: 00057002007 (2014-07-11, 458.205), 00057002...",2009/05/31,J155223,False,None,True,None,None,None
67,"19: 00049882005 (2019-02-23, 616.791), 0004988...",2013/02/06,PS1-13jw,True,False,True,2066,4,None
84,"3: 00090102003 (2009-05-20, 3279.528), 0009010...",2009/05/17,SDSSJ1342,True,True,True,0,2,2
100,"13: 00032025010 (2011-07-31, 3048.874), 000320...",2011/12/27,Swift J1112-82,True,False,True,824,3,None
101,"987: 00033765007 (2015-06-13, 491.56), 0003376...",2011/03/29,Swift J1644+57,True,True,True,0,779,779
113,"18: 00010584010 (2018-05-30, 2883.386), 000105...",2018/02/15,XMMSL2 J140446.9-251135,True,True,True,13,13,13

In [44]:
swift.loc[ (swift[f'swift_within_{late_epoch}_days'] == True) 
            & (swift["swift_neg_delta_days?"] == False)
           ]

,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,"32: 00031789003 (2010-08-27, 2073.517), 000317...",2010/07/14,2MASX J01190869-3411305,True,True,False,44,16,16
2,"9: 07021936001 (2019-10-01, 72.702), 000319300...",2006/09/01,2XMMi J184725.1-631724,True,False,False,1636,5,None
3,"62: 03107787002 (2019-04-07, 95.34), 031077870...",2005/07/23,3XMM J150052.0+015452,True,False,False,2366,15,None
4,"2: 00035189001 (2005-09-10, 9555.588), 0001036...",2000/08/23,3XMM J152130.7+074916,True,False,False,1844,1,None
6,"30: 00033130007 (2014-03-18, 471.367), 0003313...",2014/01/25,ASASSN-14ae,True,True,False,2,24,24
7,"131: 00094094009 (2018-04-16, 1597.154), 00094...",2014/11/22,ASASSN-14li,True,True,False,8,114,114
8,"153: 00033886021 (2016-04-09, 1078.609), 00033...",2015/06/14,ASASSN-15lh,True,True,False,10,128,128
9,"59: 00095141005 (2019-07-06, 1807.381), 000951...",2015/08/14,ASASSN-15oi,True,True,False,11,49,49
11,"83: 00034704007 (2016-09-22, 1901.209), 000347...",2016/08/26,AT2016ezh,True,True,False,6,70,70
14,"45: 00095142009 (2019-12-18, 2415.476), 000951...",2018/03/06,AT2018zr,True,True,False,21,40,40
16,"34: 00011396011 (2019-06-14, 908.154), 0001139...",2019/04/09,AT2019dsg,True,True,False,38,17,17
18,"13: 00049878002 (2020-02-28, 1652.021), 000316...",2002/12/31,CSS100217,True,False,False,2653,4,None
23,"21: 00033565005 (2015-02-04, 2444.2), 00033565...",2014/11/11,DES14C1kia,True,True,False,56,18,18
24,"13: 03107573001 (2018-10-03, 584.195), 0003133...",2009/01/17,Dougie,True,True,False,11,8,8
29,"56: 00091446003 (2012-06-16, 983.05), 00091446...",2003/03/22,IGR J17361-4441,True,False,False,2607,1,None
30,"16: 00034572008 (2016-07-16, 717.081), 0003457...",2016/05/29,iPTF16axa,True,True,False,14,10,10
31,"36: 00034706002 (2016-09-05, 1877.956), 000347...",2016/08/26,iPTF16fnl,True,True,False,4,32,32
50,"48: 00010032001 (2017-03-26, 191.051), 0001003...",2017/03/15,MAXI J1807+132,True,True,False,12,17,17
51,"100: 00095158004 (2019-08-22, 1226.064), 00095...",2014/07/01,NGC 247,True,False,False,104,73,None
52,"10: 03108247001 (2018-07-19, 526.528), 0008436...",2002/05/27,NGC 3599,True,False,False,1649,1,None
55,"32: 00034281015 (2016-06-05, 1670.874), 000342...",2015/12/17,OGLE16aaa,True,True,False,33,23,23
56,"18: 00034916017 (2018-06-15, 932.71), 00034916...",2016/01/28,OGLE17aaj,True,False,False,362,11,None
60,"19: 00033708011 (2015-04-27, 1914.298), 031067...",2009/12/29,PGC 1190358,True,False,False,1906,15,None
63,"21: 03109704008 (2020-03-21, 220.633), 0310970...",2010/08/15,PS1-10adi,True,True,False,52,6,6
64,"5: 00021005002 (2020-06-28, 4531.74), 00021005...",2010/05/16,PS1-10jh,True,False,False,1428,3,None
65,"1: 00010349001 (2017-11-02, 5205.131),",2010/12/30,PS1-11af,True,False,False,2499,1,None
68,"9: 00033154007 (2014-04-05, 147.306), 00033154...",2009/06/20,PTF09axc,True,False,False,2095,1,None
69,"10: 00075577003 (2020-06-23, 69.066), 00075577...",2009/07/24,PTF09djl,True,False,False,1691,1,None
70,"8: 00033153002 (2014-03-11, 903.346), 00033153...",2009/05/07,PTF09ge,True,False,False,1765,1,None
71,"9: 00031737004 (2011-08-24, 1251.13), 00031737...",2010/06/11,PTF10iya,True,True,False,0,8,8
73,"1: 00032056001 (2011-08-11, 3981.745),",2011/05/28,PTF11glr,True,True,False,75,1,1
80,"7: 00092115005 (2015-04-17, 253.019), 00092115...",2008/02/05,SDSSJ0952,True,False,False,2627,2,None
81,"12: 03109080001 (2018-07-29, 47.629), 00031743...",2010/06/10,SDSSJ1201+30,True,True,False,10,10,10
83,"9: 00020309007 (2013-10-30, 158.917), 00020311...",2003/12/02,SDSSJ1323,True,False,False,1136,3,None
86,"13: 00034971005 (2017-04-16, 1515.965), 000349...",2017/02/18,SN2017bcc,True,True,False,20,11,11
102,"32: 00032026003 (2011-07-11, 2311.727), 000320...",2011/05/27,Swift J2058+05,True,True,False,0,32,32
103,"2: 00045850001 (2012-05-04, 724.18), 000458500...",2006/08/27,TDE1,True,False,False,2276,1,None
104,"3: 00010348001 (2017-10-28, 4951.643), 0003975...",2007/06/18,TDE2,True,False,False,861,2,None
105,"9: 00054200008 (2005-10-14, 1046.905), 0005420...",2005/01/09,UGC 01791,True,False,False,278,3,None
107,"3: 00035184002 (2005-11-12, 13347.422), 000351...",1999/12/20,WINGS J134849.88+263557.5,True,False,False,2153,3,None
108,"18: 00040306012 (2021-06-18, 3949.505), 000403...",2004/07/24,XMMSL1 J024916.6-041244,True,False,False,1068,2,None
109,"13: 00032633012 (2013-07-08, 1953.621), 000326...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,13,13,13
110,"5: 00032225003 (2012-01-11, 596.732), 00032225...",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,19,3,3
111,"15: 00033229006 (2014-05-26, 513.208), 0003322...",2014/04/01,XMMSL1 J0740-85,True,True,False,13,13,13
115,"14: 00010994007 (2018-12-21, 2883.404), 000109...",2018/10/04,ZTF18abxftqm,True,True,False,56,13,13

In [45]:
print(list(swift.TDE.loc[ (swift[f'swift_within_{late_epoch}_days'] == True) 
            & (swift["swift_neg_delta_days?"] == False)
           ]))

swift_late_list = list(swift.TDE.loc[ (swift[f'swift_within_{late_epoch}_days'] == True) 
            & (swift["swift_neg_delta_days?"] == False)
           ])

print(len(swift_late_list))

['2MASX J01190869-3411305', '2XMMi J184725.1-631724', '3XMM J150052.0+015452', '3XMM J152130.7+074916', 'ASASSN-14ae', 'ASASSN-14li', 'ASASSN-15lh', 'ASASSN-15oi', 'AT2016ezh', 'AT2018zr', 'AT2019dsg', 'CSS100217', 'DES14C1kia', 'Dougie', 'IGR J17361-4441', 'iPTF16axa', 'iPTF16fnl', 'MAXI J1807+132', 'NGC 247', 'NGC 3599', 'OGLE16aaa', 'OGLE17aaj', 'PGC 1190358', 'PS1-10adi', 'PS1-10jh', 'PS1-11af', 'PTF09axc', 'PTF09djl', 'PTF09ge', 'PTF10iya', 'PTF11glr', 'SDSSJ0952', 'SDSSJ1201+30', 'SDSSJ1323', 'SN2017bcc', 'Swift J2058+05', 'TDE1', 'TDE2', 'UGC 01791', 'WINGS J134849.88+263557.5', 'XMMSL1 J024916.6-041244', 'XMMSL1 J061927.1-655311', 'XMMSL1 J063045.9-603110', 'XMMSL1 J0740-85', 'ZTF18abxftqm']
45

In [46]:
swift.loc[ (swift[f'swift_within_{early_epoch}_days'] == True) 
            & (swift["swift_neg_delta_days?"] == False)
           ]

,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,"32: 00031789003 (2010-08-27, 2073.517), 000317...",2010/07/14,2MASX J01190869-3411305,True,True,False,44,16,16
6,"30: 00033130007 (2014-03-18, 471.367), 0003313...",2014/01/25,ASASSN-14ae,True,True,False,2,24,24
7,"131: 00094094009 (2018-04-16, 1597.154), 00094...",2014/11/22,ASASSN-14li,True,True,False,8,114,114
8,"153: 00033886021 (2016-04-09, 1078.609), 00033...",2015/06/14,ASASSN-15lh,True,True,False,10,128,128
9,"59: 00095141005 (2019-07-06, 1807.381), 000951...",2015/08/14,ASASSN-15oi,True,True,False,11,49,49
11,"83: 00034704007 (2016-09-22, 1901.209), 000347...",2016/08/26,AT2016ezh,True,True,False,6,70,70
14,"45: 00095142009 (2019-12-18, 2415.476), 000951...",2018/03/06,AT2018zr,True,True,False,21,40,40
16,"34: 00011396011 (2019-06-14, 908.154), 0001139...",2019/04/09,AT2019dsg,True,True,False,38,17,17
23,"21: 00033565005 (2015-02-04, 2444.2), 00033565...",2014/11/11,DES14C1kia,True,True,False,56,18,18
24,"13: 03107573001 (2018-10-03, 584.195), 0003133...",2009/01/17,Dougie,True,True,False,11,8,8
30,"16: 00034572008 (2016-07-16, 717.081), 0003457...",2016/05/29,iPTF16axa,True,True,False,14,10,10
31,"36: 00034706002 (2016-09-05, 1877.956), 000347...",2016/08/26,iPTF16fnl,True,True,False,4,32,32
50,"48: 00010032001 (2017-03-26, 191.051), 0001003...",2017/03/15,MAXI J1807+132,True,True,False,12,17,17
55,"32: 00034281015 (2016-06-05, 1670.874), 000342...",2015/12/17,OGLE16aaa,True,True,False,33,23,23
63,"21: 03109704008 (2020-03-21, 220.633), 0310970...",2010/08/15,PS1-10adi,True,True,False,52,6,6
71,"9: 00031737004 (2011-08-24, 1251.13), 00031737...",2010/06/11,PTF10iya,True,True,False,0,8,8
73,"1: 00032056001 (2011-08-11, 3981.745),",2011/05/28,PTF11glr,True,True,False,75,1,1
81,"12: 03109080001 (2018-07-29, 47.629), 00031743...",2010/06/10,SDSSJ1201+30,True,True,False,10,10,10
86,"13: 00034971005 (2017-04-16, 1515.965), 000349...",2017/02/18,SN2017bcc,True,True,False,20,11,11
102,"32: 00032026003 (2011-07-11, 2311.727), 000320...",2011/05/27,Swift J2058+05,True,True,False,0,32,32
109,"13: 00032633012 (2013-07-08, 1953.621), 000326...",2012/11/12,XMMSL1 J061927.1-655311,True,True,False,13,13,13
110,"5: 00032225003 (2012-01-11, 596.732), 00032225...",2011/12/01,XMMSL1 J063045.9-603110,True,True,False,19,3,3
111,"15: 00033229006 (2014-05-26, 513.208), 0003322...",2014/04/01,XMMSL1 J0740-85,True,True,False,13,13,13
115,"14: 00010994007 (2018-12-21, 2883.404), 000109...",2018/10/04,ZTF18abxftqm,True,True,False,56,13,13

In [47]:
print(list(swift.TDE.loc[ (swift[f'swift_within_{early_epoch}_days'] == True) 
            & (swift["swift_neg_delta_days?"] == False)
           ]))

swift_early_list = list(swift.TDE.loc[ (swift[f'swift_within_{early_epoch}_days'] == True) 
            & (swift["swift_neg_delta_days?"] == False)
           ])

print(len(swift_early_list))

['2MASX J01190869-3411305', 'ASASSN-14ae', 'ASASSN-14li', 'ASASSN-15lh', 'ASASSN-15oi', 'AT2016ezh', 'AT2018zr', 'AT2019dsg', 'DES14C1kia', 'Dougie', 'iPTF16axa', 'iPTF16fnl', 'MAXI J1807+132', 'OGLE16aaa', 'PS1-10adi', 'PTF10iya', 'PTF11glr', 'SDSSJ1201+30', 'SN2017bcc', 'Swift J2058+05', 'XMMSL1 J061927.1-655311', 'XMMSL1 J063045.9-603110', 'XMMSL1 J0740-85', 'ZTF18abxftqm']
24

# All Data Together

In [48]:
full_df = pd.concat( (xmm, chan, swift), axis='columns')
full_df

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",...,chan_num_dt_within_100,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,"10: 0657820101 (2010-12-02, 14913.0), 07409601...",2010/07/14,2MASX J01190869-3411305,True,False,False,141,2,None,"1: 22096 (2019-02-14, 73570.0, ACIS-S ),",...,None,"32: 00031789003 (2010-08-27, 2073.517), 000317...",2010/07/14,2MASX J01190869-3411305,True,True,False,44,16,16
1,"5: 0145800101 (2003-07-13, 107002.0), 03066301...",2003/07/13,2XMM J123103.2+110648,True,True,False,0,5,1,"1: 17129 (2016-02-10, 40060.0, ACIS-S ),",...,None,"11: 00032732009 (2014-05-13, 2494.821), 000327...",2003/07/13,2XMM J123103.2+110648,False,None,False,None,None,None
2,"3: 0405550401 (2006-09-06, 28262.0), 069461010...",2006/09/01,2XMMi J184725.1-631724,True,True,False,5,3,1,"1: 15637 (2013-03-29, 15070.0, ACIS-S ),",...,None,"9: 07021936001 (2019-10-01, 72.702), 000319300...",2006/09/01,2XMMi J184725.1-631724,True,False,False,1636,5,None
3,"11: 0302460101 (2005-07-23, 36708.0), 05546805...",2005/07/23,3XMM J150052.0+015452,True,True,False,0,5,1,"12: 9517 (2008-06-05, 100060.0, ACIS-S ), 5...",...,None,"62: 03107787002 (2019-04-07, 95.34), 031077870...",2005/07/23,3XMM J150052.0+015452,True,False,False,2366,15,None
4,"3: 0109930101 (2000-08-22, 55413.0), 010993020...",2000/08/23,3XMM J152130.7+074916,True,True,True,0,1,1,"1: 900 (2000-04-03, 58030.0, ACIS-I ),",...,None,"2: 00035189001 (2005-09-10, 9555.588), 0001036...",2000/08/23,3XMM J152130.7+074916,True,False,False,1844,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,"4: 0740340301 (2014-04-29, 17340.0), 074034040...",2014/04/01,XMMSL1 J0740-85,True,True,False,28,4,3,NaN,...,None,"15: 00033229006 (2014-05-26, 513.208), 0003322...",2014/04/01,XMMSL1 J0740-85,True,True,False,13,13,13
112,"1: 0721830301 (2013-12-21, 8600.0),",2005/07/15,XMMSL1 J131952.3+225958,False,None,False,None,None,None,NaN,...,None,"1: 03106172001 (2018-08-14, 576.671),",2005/07/15,XMMSL1 J131952.3+225958,False,None,False,None,None,None
113,"2: 0804860201 (2018-07-17, 34300.0), 080486030...",2018/02/15,XMMSL2 J140446.9-251135,True,False,False,152,2,None,NaN,...,None,"18: 00010584010 (2018-05-30, 2883.386), 000105...",2018/02/15,XMMSL2 J140446.9-251135,True,True,True,13,13,13
114,"5: 0763640201 (2016-09-08, 11600.0), 076364040...",2006/08/22,XMMSL2 J144605.0+685735,False,None,False,None,None,None,NaN,...,None,"23: 00034707020 (2017-03-26, 2219.934), 000347...",2006/08/22,XMMSL2 J144605.0+685735,False,None,False,None,None,None
115,"1: 0822040901 (2018-12-27, 21000.0),",2018/10/04,ZTF18abxftqm,True,True,False,84,1,1,NaN,...,None,"14: 00010994007 (2018-12-21, 2883.404), 000109...",2018/10/04,ZTF18abxftqm,True,True,False,56,13,13

In [49]:
# full_df.loc[ (full_df[3] == True) 
#                 & (full_df[4] == False)
#                 & (full_df[10] == True) 
#                 & (full_df[11] == False)
#                 & (full_df[17] == True) 
#                 & (full_df[18] == False)
#                ]

full_df.loc[ (full_df[f'xmm_within_{early_epoch}_days'] == True) 
#                 & (full_df[4] == False)
                & (full_df[f'chan_within_{early_epoch}_days'] == True) 
#                 & (full_df[11] == False)
                & (full_df[f'swift_within_{early_epoch}_days'] == True) 
#                 & (full_df[18] == False)
               ]

,"XMM Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec])",Disc Date,TDE,xmm_within_3000_days,xmm_within_100_days,xmm_neg_delta_days?,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,"Chandra Data (#obs: ObsIDs, exp date [yyyy-mm-dd], exp dur [sec], detector)",...,chan_num_dt_within_100,"Swift Data (#obs: ObsIDs, exp date [yyyy-mm-dd], XRT exp dur [sec])",Disc Date,TDE,swift_within_3000_days,swift_within_100_days,swift_neg_delta_days?,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
7,"13: 0694651201 (2014-12-06, 23000.0), 06946514...",2014/11/22,ASASSN-14li,True,True,False,14,13,3,"7: 17566 (2014-12-08, 35040.0, HRC-S ), 1756...",...,2,"131: 00094094009 (2018-04-16, 1597.154), 00094...",2014/11/22,ASASSN-14li,True,True,False,8,114,114
101,"19: 0678380101 (2011-04-16, 24919.0), 06783802...",2011/03/29,Swift J1644+57,True,True,False,2,19,7,"14: 15584 (2012-11-26, 24970.0, ACIS-S ), 171...",...,1,"987: 00033765007 (2015-06-13, 491.56), 0003376...",2011/03/29,Swift J1644+57,True,True,True,0,779,779

In [50]:
# list(full_df.TDE.loc[ (full_df[3] == True) 
#                     & (full_df[4] == False)
#                     & (full_df[10] == True) 
#                     & (full_df[11] == False)
#                     & (full_df[17] == True) 
#                     & (full_df[18] == False)
#                    ])

In [51]:
# full_df.iloc[:,[3,4,10,11,17,18]] == [True,False,True,False,True,False]

In [52]:
for tde in xmm_late_list:
    if tde in (swift_late_list and chan_late_list):
        print(tde)

2XMMi J184725.1-631724
3XMM J215022.4-055108
ASASSN-14ae
ASASSN-14li
ASASSN-15lh
D23H-1
DES14C1kia
NGC 3599
SDSSJ0159
Swift J1644+57
Swift J2058+05
WINGS J134849.88+263557.5

In [53]:
tde_list = list(set(xmm_late_list + swift_late_list + chan_late_list)) # returns all TDEs from all lists without duplicates
tde_list.sort()
print(len(tde_list))
tde_list

54

['2MASX J01190869-3411305',
 '2XMM J123103.2+110648',
 '2XMMi J184725.1-631724',
 '3XMM J150052.0+015452',
 '3XMM J152130.7+074916',
 '3XMM J215022.4-055108',
 'ASASSN-14ae',
 'ASASSN-14li',
 'ASASSN-15lh',
 'ASASSN-15oi',
 'AT2016ezh',
 'AT2018zr',
 'AT2019dsg',
 'CSS100217',
 'D23H-1',
 'D3-13',
 'DES14C1kia',
 'Dougie',
 'IGR J17361-4441',
 'MAXI J1807+132',
 'NGC 247',
 'NGC 3599',
 'OGLE16aaa',
 'OGLE17aaj',
 'PGC 1185375',
 'PGC 1190358',
 'PS1-10adi',
 'PS1-10jh',
 'PS1-11af',
 'PS1-13jw',
 'PTF09axc',
 'PTF09djl',
 'PTF09ge',
 'PTF10iya',
 'PTF11glr',
 'SDSSJ0159',
 'SDSSJ0952',
 'SDSSJ1201+30',
 'SDSSJ1323',
 'SN2017bcc',
 'Swift J1644+57',
 'Swift J2058+05',
 'TDE1',
 'TDE2',
 'UGC 01791',
 'WINGS J134849.88+263557.5',
 'XMMSL1 J024916.6-041244',
 'XMMSL1 J061927.1-655311',
 'XMMSL1 J063045.9-603110',
 'XMMSL1 J0740-85',
 'XMMSL2 J140446.9-251135',
 'ZTF18abxftqm',
 'iPTF16axa',
 'iPTF16fnl']

In [54]:
# xmm[f'xmm_within_{late_epoch}_days'].to_clipboard()

In [55]:
# xmm[f'xmm_within_{early_epoch}_days'].to_clipboard()

In [56]:
# chan[f'chan_within_1{late_epoch}_days'].to_clipboard()

In [57]:
# chan[f'chan_within_{early_epoch}_days'].to_clipboard()

In [58]:
# swift[f'swift_within_{late_epoch}_days'].to_clipboard()

In [59]:
# swift[f'swift_within_{early_epoch}_days'].to_clipboard()

In [60]:
xmm_late_list

['2MASX J01190869-3411305',
 '2XMM J123103.2+110648',
 '2XMMi J184725.1-631724',
 '3XMM J150052.0+015452',
 '3XMM J215022.4-055108',
 'ASASSN-14ae',
 'ASASSN-14li',
 'ASASSN-15lh',
 'ASASSN-15oi',
 'AT2018zr',
 'AT2019dsg',
 'D23H-1',
 'DES14C1kia',
 'Dougie',
 'MAXI J1807+132',
 'NGC 3599',
 'OGLE16aaa',
 'SDSSJ0159',
 'SDSSJ1201+30',
 'SDSSJ1323',
 'Swift J1644+57',
 'Swift J2058+05',
 'WINGS J134849.88+263557.5',
 'XMMSL1 J024916.6-041244',
 'XMMSL1 J061927.1-655311',
 'XMMSL1 J063045.9-603110',
 'XMMSL1 J0740-85',
 'XMMSL2 J140446.9-251135',
 'ZTF18abxftqm']

In [61]:
chan_late_list

['2XMMi J184725.1-631724',
 '3XMM J215022.4-055108',
 'ASASSN-14ae',
 'ASASSN-14li',
 'ASASSN-15lh',
 'D23H-1',
 'D3-13',
 'DES14C1kia',
 'IGR J17361-4441',
 'iPTF16axa',
 'iPTF16fnl',
 'NGC 3599',
 'PGC 1185375',
 'PS1-13jw',
 'SDSSJ0159',
 'SDSSJ0952',
 'Swift J1644+57',
 'Swift J2058+05',
 'WINGS J134849.88+263557.5']

In [62]:
swift_late_list

['2MASX J01190869-3411305',
 '2XMMi J184725.1-631724',
 '3XMM J150052.0+015452',
 '3XMM J152130.7+074916',
 'ASASSN-14ae',
 'ASASSN-14li',
 'ASASSN-15lh',
 'ASASSN-15oi',
 'AT2016ezh',
 'AT2018zr',
 'AT2019dsg',
 'CSS100217',
 'DES14C1kia',
 'Dougie',
 'IGR J17361-4441',
 'iPTF16axa',
 'iPTF16fnl',
 'MAXI J1807+132',
 'NGC 247',
 'NGC 3599',
 'OGLE16aaa',
 'OGLE17aaj',
 'PGC 1190358',
 'PS1-10adi',
 'PS1-10jh',
 'PS1-11af',
 'PTF09axc',
 'PTF09djl',
 'PTF09ge',
 'PTF10iya',
 'PTF11glr',
 'SDSSJ0952',
 'SDSSJ1201+30',
 'SDSSJ1323',
 'SN2017bcc',
 'Swift J2058+05',
 'TDE1',
 'TDE2',
 'UGC 01791',
 'WINGS J134849.88+263557.5',
 'XMMSL1 J024916.6-041244',
 'XMMSL1 J061927.1-655311',
 'XMMSL1 J063045.9-603110',
 'XMMSL1 J0740-85',
 'ZTF18abxftqm']

In [63]:
xray_late_list = list(set(xmm_late_list + chan_late_list))
xray_late_list.sort()
print(len(xray_late_list))
xray_late_list

36

['2MASX J01190869-3411305',
 '2XMM J123103.2+110648',
 '2XMMi J184725.1-631724',
 '3XMM J150052.0+015452',
 '3XMM J215022.4-055108',
 'ASASSN-14ae',
 'ASASSN-14li',
 'ASASSN-15lh',
 'ASASSN-15oi',
 'AT2018zr',
 'AT2019dsg',
 'D23H-1',
 'D3-13',
 'DES14C1kia',
 'Dougie',
 'IGR J17361-4441',
 'MAXI J1807+132',
 'NGC 3599',
 'OGLE16aaa',
 'PGC 1185375',
 'PS1-13jw',
 'SDSSJ0159',
 'SDSSJ0952',
 'SDSSJ1201+30',
 'SDSSJ1323',
 'Swift J1644+57',
 'Swift J2058+05',
 'WINGS J134849.88+263557.5',
 'XMMSL1 J024916.6-041244',
 'XMMSL1 J061927.1-655311',
 'XMMSL1 J063045.9-603110',
 'XMMSL1 J0740-85',
 'XMMSL2 J140446.9-251135',
 'ZTF18abxftqm',
 'iPTF16axa',
 'iPTF16fnl']

In [64]:
count = 0
for tde in xray_late_list:
    if tde in swift_late_list:
        print(tde)
        count += 1
print(count)

2MASX J01190869-3411305
2XMMi J184725.1-631724
3XMM J150052.0+015452
ASASSN-14ae
ASASSN-14li
ASASSN-15lh
ASASSN-15oi
AT2018zr
AT2019dsg
DES14C1kia
Dougie
IGR J17361-4441
MAXI J1807+132
NGC 3599
OGLE16aaa
SDSSJ0952
SDSSJ1201+30
SDSSJ1323
Swift J2058+05
WINGS J134849.88+263557.5
XMMSL1 J024916.6-041244
XMMSL1 J061927.1-655311
XMMSL1 J063045.9-603110
XMMSL1 J0740-85
ZTF18abxftqm
iPTF16axa
iPTF16fnl
27

In [65]:
xray_early_list = list(set(xmm_early_list + chan_early_list))
xray_early_list.sort()
print(len(xray_early_list))
xray_early_list

20

['2XMM J123103.2+110648',
 '2XMMi J184725.1-631724',
 '3XMM J150052.0+015452',
 'ASASSN-14li',
 'ASASSN-15oi',
 'AT2018zr',
 'AT2019dsg',
 'D23H-1',
 'DES14C1kia',
 'MAXI J1807+132',
 'SDSSJ0159',
 'SDSSJ0952',
 'SDSSJ1201+30',
 'Swift J1644+57',
 'Swift J2058+05',
 'WINGS J134849.88+263557.5',
 'XMMSL1 J061927.1-655311',
 'XMMSL1 J063045.9-603110',
 'XMMSL1 J0740-85',
 'ZTF18abxftqm']

In [66]:
count = 0
for tde in xray_early_list:
    if tde in swift_late_list:
        print(tde)
        count += 1
print(count)

2XMMi J184725.1-631724
3XMM J150052.0+015452
ASASSN-14li
ASASSN-15oi
AT2018zr
AT2019dsg
DES14C1kia
MAXI J1807+132
SDSSJ0952
SDSSJ1201+30
Swift J2058+05
WINGS J134849.88+263557.5
XMMSL1 J061927.1-655311
XMMSL1 J063045.9-603110
XMMSL1 J0740-85
ZTF18abxftqm
16

In [67]:
full_df[['TDE'
         ,'xmm_min_dt',f'xmm_num_dt_within_{late_epoch}',f'xmm_num_dt_within_{early_epoch}'
         ,'chan_min_dt',f'chan_num_dt_within_{late_epoch}',f'chan_num_dt_within_{early_epoch}'
         ,'swift_min_dt',f'swift_num_dt_within_{late_epoch}',f'swift_num_dt_within_{early_epoch}'
        ]]

,TDE,TDE,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,2MASX J01190869-3411305,2MASX J01190869-3411305,2MASX J01190869-3411305,141,2,None,None,None,None,44,16,16
1,2XMM J123103.2+110648,2XMM J123103.2+110648,2XMM J123103.2+110648,0,5,1,None,None,None,None,None,None
2,2XMMi J184725.1-631724,2XMMi J184725.1-631724,2XMMi J184725.1-631724,5,3,1,2401,1,None,1636,5,None
3,3XMM J150052.0+015452,3XMM J150052.0+015452,3XMM J150052.0+015452,0,5,1,1048,9,None,2366,15,None
4,3XMM J152130.7+074916,3XMM J152130.7+074916,3XMM J152130.7+074916,0,1,1,None,None,None,1844,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...
111,XMMSL1 J0740-85,XMMSL1 J0740-85,XMMSL1 J0740-85,28,4,3,None,None,None,13,13,13
112,XMMSL1 J131952.3+225958,XMMSL1 J131952.3+225958,XMMSL1 J131952.3+225958,None,None,None,None,None,None,None,None,None
113,XMMSL2 J140446.9-251135,XMMSL2 J140446.9-251135,XMMSL2 J140446.9-251135,152,2,None,None,None,None,13,13,13
114,XMMSL2 J144605.0+685735,XMMSL2 J144605.0+685735,XMMSL2 J144605.0+685735,None,None,None,None,None,None,None,None,None
115,ZTF18abxftqm,ZTF18abxftqm,ZTF18abxftqm,84,1,1,None,None,None,56,13,13

In [68]:
# full_df[['TDE'
#          ,'xmm_min_dt',f'xmm_num_dt_within_{late_epoch}',f'xmm_num_dt_within_{early_epoch}'
#          ,'chan_min_dt',f'chan_num_dt_within_{late_epoch}',f'chan_num_dt_within_{early_epoch}'
#          ,'swift_min_dt',f'swift_num_dt_within_{late_epoch}',f'swift_num_dt_within_{early_epoch}'
#         ]].to_clipboard()

In [69]:
abr_df = full_df[['TDE'
         ,'xmm_min_dt',f'xmm_num_dt_within_{late_epoch}',f'xmm_num_dt_within_{early_epoch}'
         ,'chan_min_dt',f'chan_num_dt_within_{late_epoch}',f'chan_num_dt_within_{early_epoch}'
         ,'swift_min_dt',f'swift_num_dt_within_{late_epoch}',f'swift_num_dt_within_{early_epoch}'
        ]]

In [70]:
# abr_df.to_clipboard()

# Prioritization

## Tier 1 (Best Data): 
1. XMM and/or Chandra data with more than one >1 ksec (based on exp time-->counts, but z and object’s brightness important too) spectrum within 100 days (based on trying to sample the super-Edd or ~Edd regime) 
2. and more than one >3 ksec spectra (based on Wen et al. 2020’s result showing that more epochs can provide better constraints) at later times.

In [71]:
best_df = abr_df.loc[((abr_df[f'xmm_num_dt_within_{early_epoch}'] > 1)
                      | (abr_df[f'chan_num_dt_within_{early_epoch}'] > 1)
                      | ((abr_df[f'xmm_num_dt_within_{early_epoch}'] >= 1)
                          & (abr_df[f'chan_num_dt_within_{early_epoch}'] >= 1))
                     ) 
                     & ((abr_df[f'xmm_num_dt_within_{late_epoch}'] > 1)
                          | (abr_df[f'chan_num_dt_within_{late_epoch}'] > 1)
                          | ((abr_df[f'xmm_num_dt_within_{late_epoch}'] >= 1)
                              & (abr_df[f'chan_num_dt_within_{late_epoch}'] >= 1))
                         ) 
                    ]

best_df

,TDE,TDE,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
7,ASASSN-14li,ASASSN-14li,ASASSN-14li,14,13,3,16,7,2,8,114,114
14,AT2018zr,AT2018zr,AT2018zr,36,3,2,None,None,None,21,40,40
19,CXOU J0332,CXOU J0332,CXOU J0332,1770,1,None,0,39,22,4,10,10
21,D23H-1,D23H-1,D23H-1,1212,2,None,27,8,2,None,None,None
50,MAXI J1807+132,MAXI J1807+132,MAXI J1807+132,14,2,2,None,None,None,12,17,17
101,Swift J1644+57,Swift J1644+57,Swift J1644+57,2,19,7,6,14,1,0,779,779
107,WINGS J134849.88+263557.5,WINGS J134849.88+263557.5,WINGS J134849.88+263557.5,189,2,None,0,13,2,2153,3,None
111,XMMSL1 J0740-85,XMMSL1 J0740-85,XMMSL1 J0740-85,28,4,3,None,None,None,13,13,13

In [72]:
best_index = list(best_df.index)
print(best_index, '\n', len(best_index))

[7, 14, 19, 21, 50, 101, 107, 111]
 8

In [73]:
rem_df = abr_df.drop(best_index)
# rem_df

## Tier 2 (Very Good Data)
1. XMM and/or Chandra data with one >1 ksec (based on exp time-->counts, but z and object’s brightness important too) spectrum within 100 days (based on trying to sample the super-Edd or ~Edd regime) 
2. and more than one >3 ksec spectra (based on Wen et al. 2020’s result showing that more epochs can provide better constraints) at later times.

In [74]:
very_good_df = rem_df.loc[((abr_df[f'xmm_num_dt_within_{early_epoch}'] > 0)
                      | (abr_df[f'chan_num_dt_within_{early_epoch}'] > 0)
                      # | ((abr_df[f'xmm_num_dt_within_{early_epoch}'] >= 1)
                      #     & (abr_df[f'chan_num_dt_within_{early_epoch}'] >= 1))
                     ) 
                     & ((abr_df[f'xmm_num_dt_within_{late_epoch}'] > 1)
                          | (abr_df[f'chan_num_dt_within_{late_epoch}'] > 1)
                          | ((abr_df[f'xmm_num_dt_within_{late_epoch}'] >= 1)
                              & (abr_df[f'chan_num_dt_within_{late_epoch}'] >= 1))
                         ) 
                    ]
very_good_df

,TDE,TDE,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
1,2XMM J123103.2+110648,2XMM J123103.2+110648,2XMM J123103.2+110648,0,5,1,None,None,None,None,None,None
2,2XMMi J184725.1-631724,2XMMi J184725.1-631724,2XMMi J184725.1-631724,5,3,1,2401,1,None,1636,5,None
3,3XMM J150052.0+015452,3XMM J150052.0+015452,3XMM J150052.0+015452,0,5,1,1048,9,None,2366,15,None
9,ASASSN-15oi,ASASSN-15oi,ASASSN-15oi,76,2,1,None,None,None,11,49,49
12,AT2017eqx,AT2017eqx,AT2017eqx,None,None,None,70,2,1,34,10,10
16,AT2019dsg,AT2019dsg,AT2019dsg,51,2,1,None,None,None,38,17,17
23,DES14C1kia,DES14C1kia,DES14C1kia,62,2,1,1579,1,None,56,18,18
25,F01004-2237,F01004-2237,F01004-2237,None,None,None,70,8,1,None,None,None
51,NGC 247,NGC 247,NGC 247,0,9,1,134,1,None,104,73,None
78,SDSSJ0159,SDSSJ0159,SDSSJ0159,0,1,1,1123,2,None,None,None,None
80,SDSSJ0952,SDSSJ0952,SDSSJ0952,None,None,None,0,3,1,2627,2,None
81,SDSSJ1201+30,SDSSJ1201+30,SDSSJ1201+30,12,3,1,None,None,None,10,10,10
82,SDSSJ1311,SDSSJ1311,SDSSJ1311,None,None,None,0,4,1,None,None,None
102,Swift J2058+05,Swift J2058+05,Swift J2058+05,177,3,None,26,4,1,0,32,32
109,XMMSL1 J061927.1-655311,XMMSL1 J061927.1-655311,XMMSL1 J061927.1-655311,33,2,1,None,None,None,13,13,13

In [75]:
very_good_index = list(very_good_df.index)
print(very_good_index, '\n', len(very_good_index))

[1, 2, 3, 9, 12, 16, 23, 25, 51, 78, 80, 81, 82, 102, 109]
 15

In [76]:
rem_df = rem_df.drop(very_good_index)
# rem_df

## Tier 3 (Good Data)
1. XMM and/or Chandra data with one >1 ksec (based on exp time-->counts, but z and object’s brightness important too) spectrum within 100 days (based on trying to sample the super-Edd or ~Edd regime)

In [77]:
good_df = rem_df.loc[((abr_df[f'xmm_num_dt_within_{early_epoch}'] > 0)
                      | (abr_df[f'chan_num_dt_within_{early_epoch}'] > 0)
                     )
                      ]

good_df

,TDE,TDE,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
4,3XMM J152130.7+074916,3XMM J152130.7+074916,3XMM J152130.7+074916,0,1,1,None,None,None,1844,1,None
110,XMMSL1 J063045.9-603110,XMMSL1 J063045.9-603110,XMMSL1 J063045.9-603110,21,1,1,None,None,None,19,3,3
115,ZTF18abxftqm,ZTF18abxftqm,ZTF18abxftqm,84,1,1,None,None,None,56,13,13

In [78]:
good_index = list(good_df.index)
print(good_index, '\n', len(good_index))

[4, 110, 115]
 3

In [79]:
rem_df = rem_df.drop(good_index)
# rem_df

## Tier 4 (Fair Data)
1. XMM and/or Chandra data with more than one >3 ksec spectra (based on Wen et al. 2020’s result showing that more epochs can provide better constraints) at later times.

In [80]:
fair_df = rem_df.loc[((abr_df[f'xmm_num_dt_within_{late_epoch}'] > 1)
                      | (abr_df[f'chan_num_dt_within_{late_epoch}'] > 1)
                      | ((abr_df[f'xmm_num_dt_within_{late_epoch}'] >= 1)
                          & (abr_df[f'chan_num_dt_within_{late_epoch}'] >= 1))
                     ) 
                    ]
fair_df

,TDE,TDE,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
0,2MASX J01190869-3411305,2MASX J01190869-3411305,2MASX J01190869-3411305,141,2,None,None,None,None,44,16,16
5,3XMM J215022.4-055108,3XMM J215022.4-055108,3XMM J215022.4-055108,369,3,None,515,1,None,None,None,None
6,ASASSN-14ae,ASASSN-14ae,ASASSN-14ae,110,3,None,1757,1,None,2,24,24
8,ASASSN-15lh,ASASSN-15lh,ASASSN-15lh,157,2,None,151,4,None,10,128,128
11,AT2016ezh,AT2016ezh,AT2016ezh,None,None,None,867,3,None,6,70,70
22,D3-13,D3-13,D3-13,None,None,None,434,69,None,None,None,None
24,Dougie,Dougie,Dougie,475,2,None,None,None,None,11,8,8
52,NGC 3599,NGC 3599,NGC 3599,1488,2,None,2070,1,None,1649,1,None
55,OGLE16aaa,OGLE16aaa,OGLE16aaa,175,2,None,None,None,None,33,23,23
59,PGC 1185375,PGC 1185375,PGC 1185375,None,None,None,218,2,None,None,None,None
113,XMMSL2 J140446.9-251135,XMMSL2 J140446.9-251135,XMMSL2 J140446.9-251135,152,2,None,None,None,None,13,13,13

In [81]:
fair_index = list(fair_df.index)
print(fair_index, '\n', len(fair_index))

[0, 5, 6, 8, 11, 22, 24, 52, 55, 59, 113]
 11

In [82]:
rem_df = rem_df.drop(fair_index)
rem_df.head(60)

,TDE,TDE,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
10,ASASSN-20il,ASASSN-20il,ASASSN-20il,None,None,None,None,None,None,None,None,None
13,AT2018fyk,AT2018fyk,AT2018fyk,None,None,None,None,None,None,None,None,None
15,AT2019azh,AT2019azh,AT2019azh,None,None,None,None,None,None,None,None,None
17,AT2020ocn,AT2020ocn,AT2020ocn,None,None,None,None,None,None,None,None,None
18,CSS100217,CSS100217,CSS100217,None,None,None,None,None,None,2653,4,None
20,D1-9,D1-9,D1-9,None,None,None,None,None,None,None,None,None
26,Gaia16aax,Gaia16aax,Gaia16aax,None,None,None,None,None,None,None,None,None
27,Gaia16ajq,Gaia16ajq,Gaia16ajq,None,None,None,None,None,None,None,None,None
28,Gaia16aka,Gaia16aka,Gaia16aka,None,None,None,None,None,None,None,None,None
29,IGR J17361-4441,IGR J17361-4441,IGR J17361-4441,None,None,None,761,1,None,2607,1,None
30,iPTF16axa,iPTF16axa,iPTF16axa,None,None,None,915,1,None,14,10,10
31,iPTF16fnl,iPTF16fnl,iPTF16fnl,None,None,None,1006,1,None,4,32,32
32,J030257,J030257,J030257,None,None,None,None,None,None,None,None,None
33,J091225,J091225,J091225,None,None,None,None,None,None,None,None,None
34,J094608,J094608,J094608,None,None,None,None,None,None,None,None,None
35,J094806,J094806,J094806,None,None,None,None,None,None,None,None,None
36,J100933,J100933,J100933,None,None,None,None,None,None,None,None,None
37,J113527,J113527,J113527,None,None,None,None,None,None,None,None,None
38,J121116,J121116,J121116,None,None,None,None,None,None,None,None,None
39,J123715,J123715,J123715,None,None,None,None,None,None,None,None,None
40,J130819,J130819,J130819,None,None,None,None,None,None,None,None,None
41,J133737,J133737,J133737,None,None,None,None,None,None,None,None,None
42,J133837,J133837,J133837,None,None,None,None,None,None,None,None,None
43,J134244,J134244,J134244,None,None,None,None,None,None,None,None,None
44,J141036,J141036,J141036,None,None,None,None,None,None,None,None,None
45,J142401,J142401,J142401,None,None,None,None,None,None,None,None,None
46,J145851,J145851,J145851,None,None,None,None,None,None,None,None,None
47,J155223,J155223,J155223,None,None,None,None,None,None,None,None,None
48,J233454,J233454,J233454,None,None,None,None,None,None,None,None,None
49,LEDA 095953,LEDA 095953,LEDA 095953,None,None,None,None,None,None,None,None,None
53,NGC 5905,NGC 5905,NGC 5905,None,None,None,None,None,None,None,None,None
54,NGC 6021,NGC 6021,NGC 6021,None,None,None,None,None,None,None,None,None
56,OGLE17aaj,OGLE17aaj,OGLE17aaj,None,None,None,None,None,None,362,11,None
57,PGC 015259,PGC 015259,PGC 015259,None,None,None,None,None,None,None,None,None
58,PGC 1127938,PGC 1127938,PGC 1127938,None,None,None,None,None,None,None,None,None
60,PGC 1190358,PGC 1190358,PGC 1190358,None,None,None,None,None,None,1906,15,None
61,PGC 133344,PGC 133344,PGC 133344,None,None,None,None,None,None,None,None,None
62,PGC 170392,PGC 170392,PGC 170392,None,None,None,None,None,None,None,None,None
63,PS1-10adi,PS1-10adi,PS1-10adi,None,None,None,None,None,None,52,6,6
64,PS1-10jh,PS1-10jh,PS1-10jh,None,None,None,371,1,None,1428,3,None
65,PS1-11af,PS1-11af,PS1-11af,None,None,None,None,None,None,2499,1,None
66,PS1-12yp,PS1-12yp,PS1-12yp,None,None,None,None,None,None,None,None,None
67,PS1-13jw,PS1-13jw,PS1-13jw,None,None,None,1054,1,None,2066,4,None
68,PTF09axc,PTF09axc,PTF09axc,None,None,None,None,None,None,2095,1,None
69,PTF09djl,PTF09djl,PTF09djl,None,None,None,None,None,None,1691,1,None
70,PTF09ge,PTF09ge,PTF09ge,None,None,None,None,None,None,1765,1,None
71,PTF10iya,PTF10iya,PTF10iya,None,None,None,None,None,None,0,8,8
72,PTF10nuj,PTF10nuj,PTF10nuj,None,None,None,None,None,None,None,None,None
73,PTF11glr,PTF11glr,PTF11glr,None,None,None,None,None,None,75,1,1
74,RBS 1032,RBS 1032,RBS 1032,None,None,None,None,None,None,None,None,None
75,RX J1242-11A,RX J1242-11A,RX J1242-11A,None,None,None,None,None,None,None,None,None
76,RX J1420+53,RX J1420+53,RX J1420+53,None,None,None,None,None,None,None,None,None
77,RX J1624+75,RX J1624+75,RX J1624+75,None,None,None,None,None,None,None,None,None
79,SDSSJ0748,SDSSJ0748,SDSSJ0748,None,None,None,None,None,None,None,None,None
83,SDSSJ1323,SDSSJ1323,SDSSJ1323,956,1,None,None,None,None,1136,3,None
84,SDSSJ1342,SDSSJ1342,SDSSJ1342,None,None,None,None,None,None,0,2,2
85,SDSSJ1350,SDSSJ1350,SDSSJ1350,None,None,None,None,None,None,None,None,None
86,SN2017bcc,SN2017bcc,SN2017bcc,None,None,None,None,None,None,20,11,11
87,SRGE J013204.6+122236,SRGE J013204.6+122236,SRGE J013204.6+122236,None,None,None,None,None,None,None,None,None
88,SRGE J021939.9+361819,SRGE J021939.9+361819,SRGE J021939.9+361819,None,None,None,None,None,None,None,None,None

### Export dataframes

In [83]:
# best_df.to_clipboard()
# very_good_df.to_clipboard()
# good_df.to_clipboard()
# fair_df.to_clipboard()

In [84]:
all_priority_indices = best_index + very_good_index + good_index + fair_index
print(all_priority_indices, '\n', len(all_priority_indices))

[7, 14, 19, 21, 50, 101, 107, 111, 1, 2, 3, 9, 12, 16, 23, 25, 51, 78, 80, 81, 82, 102, 109, 4, 110, 115, 0, 5, 6, 8, 11, 22, 24, 52, 55, 59, 113]
 37

In [85]:
# save indicies for use in other code.

save_bool = True
# save_bool = False

if save_bool == True:
    save_file = 'priority_tde_indicies.txt'
    with open('priority_tde_indicies.txt', 'w') as savf:
        savf.write(str(all_priority_indices))

## Export info to LaTeX table

In [86]:
priority_df = abr_df.iloc[all_priority_indices]
priority_df = priority_df.loc[:,~priority_df.columns.duplicated()].copy() # drop duplicate columns
priority_df

,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100
7,ASASSN-14li,14,13,3,16,7,2,8,114,114
14,AT2018zr,36,3,2,None,None,None,21,40,40
19,CXOU J0332,1770,1,None,0,39,22,4,10,10
21,D23H-1,1212,2,None,27,8,2,None,None,None
50,MAXI J1807+132,14,2,2,None,None,None,12,17,17
101,Swift J1644+57,2,19,7,6,14,1,0,779,779
107,WINGS J134849.88+263557.5,189,2,None,0,13,2,2153,3,None
111,XMMSL1 J0740-85,28,4,3,None,None,None,13,13,13
1,2XMM J123103.2+110648,0,5,1,None,None,None,None,None,None
2,2XMMi J184725.1-631724,5,3,1,2401,1,None,1636,5,None
3,3XMM J150052.0+015452,0,5,1,1048,9,None,2366,15,None
9,ASASSN-15oi,76,2,1,None,None,None,11,49,49
12,AT2017eqx,None,None,None,70,2,1,34,10,10
16,AT2019dsg,51,2,1,None,None,None,38,17,17
23,DES14C1kia,62,2,1,1579,1,None,56,18,18
25,F01004-2237,None,None,None,70,8,1,None,None,None
51,NGC 247,0,9,1,134,1,None,104,73,None
78,SDSSJ0159,0,1,1,1123,2,None,None,None,None
80,SDSSJ0952,None,None,None,0,3,1,2627,2,None
81,SDSSJ1201+30,12,3,1,None,None,None,10,10,10
82,SDSSJ1311,None,None,None,0,4,1,None,None,None
102,Swift J2058+05,177,3,None,26,4,1,0,32,32
109,XMMSL1 J061927.1-655311,33,2,1,None,None,None,13,13,13
4,3XMM J152130.7+074916,0,1,1,None,None,None,1844,1,None
110,XMMSL1 J063045.9-603110,21,1,1,None,None,None,19,3,3
115,ZTF18abxftqm,84,1,1,None,None,None,56,13,13
0,2MASX J01190869-3411305,141,2,None,None,None,None,44,16,16
5,3XMM J215022.4-055108,369,3,None,515,1,None,None,None,None
6,ASASSN-14ae,110,3,None,1757,1,None,2,24,24
8,ASASSN-15lh,157,2,None,151,4,None,10,128,128
11,AT2016ezh,None,None,None,867,3,None,6,70,70
22,D3-13,None,None,None,434,69,None,None,None,None
24,Dougie,475,2,None,None,None,None,11,8,8
52,NGC 3599,1488,2,None,2070,1,None,1649,1,None
55,OGLE16aaa,175,2,None,None,None,None,33,23,23
59,PGC 1185375,None,None,None,218,2,None,None,None,None
113,XMMSL2 J140446.9-251135,152,2,None,None,None,None,13,13,13

In [87]:
priority_df['swift_num_dt_after_100'] = priority_df['swift_num_dt_within_3000'] - priority_df['swift_num_dt_within_100'].fillna(0)
priority_df

,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100,swift_num_dt_after_100
7,ASASSN-14li,14,13,3,16,7,2,8,114,114,0
14,AT2018zr,36,3,2,None,None,None,21,40,40,0
19,CXOU J0332,1770,1,None,0,39,22,4,10,10,0
21,D23H-1,1212,2,None,27,8,2,None,None,None,NaN
50,MAXI J1807+132,14,2,2,None,None,None,12,17,17,0
101,Swift J1644+57,2,19,7,6,14,1,0,779,779,0
107,WINGS J134849.88+263557.5,189,2,None,0,13,2,2153,3,None,3
111,XMMSL1 J0740-85,28,4,3,None,None,None,13,13,13,0
1,2XMM J123103.2+110648,0,5,1,None,None,None,None,None,None,NaN
2,2XMMi J184725.1-631724,5,3,1,2401,1,None,1636,5,None,5
3,3XMM J150052.0+015452,0,5,1,1048,9,None,2366,15,None,15
9,ASASSN-15oi,76,2,1,None,None,None,11,49,49,0
12,AT2017eqx,None,None,None,70,2,1,34,10,10,0
16,AT2019dsg,51,2,1,None,None,None,38,17,17,0
23,DES14C1kia,62,2,1,1579,1,None,56,18,18,0
25,F01004-2237,None,None,None,70,8,1,None,None,None,NaN
51,NGC 247,0,9,1,134,1,None,104,73,None,73
78,SDSSJ0159,0,1,1,1123,2,None,None,None,None,NaN
80,SDSSJ0952,None,None,None,0,3,1,2627,2,None,2
81,SDSSJ1201+30,12,3,1,None,None,None,10,10,10,0
82,SDSSJ1311,None,None,None,0,4,1,None,None,None,NaN
102,Swift J2058+05,177,3,None,26,4,1,0,32,32,0
109,XMMSL1 J061927.1-655311,33,2,1,None,None,None,13,13,13,0
4,3XMM J152130.7+074916,0,1,1,None,None,None,1844,1,None,1
110,XMMSL1 J063045.9-603110,21,1,1,None,None,None,19,3,3,0
115,ZTF18abxftqm,84,1,1,None,None,None,56,13,13,0
0,2MASX J01190869-3411305,141,2,None,None,None,None,44,16,16,0
5,3XMM J215022.4-055108,369,3,None,515,1,None,None,None,None,NaN
6,ASASSN-14ae,110,3,None,1757,1,None,2,24,24,0
8,ASASSN-15lh,157,2,None,151,4,None,10,128,128,0
11,AT2016ezh,None,None,None,867,3,None,6,70,70,0
22,D3-13,None,None,None,434,69,None,None,None,None,NaN
24,Dougie,475,2,None,None,None,None,11,8,8,0
52,NGC 3599,1488,2,None,2070,1,None,1649,1,None,1
55,OGLE16aaa,175,2,None,None,None,None,33,23,23,0
59,PGC 1185375,None,None,None,218,2,None,None,None,None,NaN
113,XMMSL2 J140446.9-251135,152,2,None,None,None,None,13,13,13,0

In [88]:
priority_df = priority_df.fillna('dots')
priority_df

,TDE,xmm_min_dt,xmm_num_dt_within_3000,xmm_num_dt_within_100,chan_min_dt,chan_num_dt_within_3000,chan_num_dt_within_100,swift_min_dt,swift_num_dt_within_3000,swift_num_dt_within_100,swift_num_dt_after_100
7,ASASSN-14li,14,13,3,16,7,2,8,114,114,0
14,AT2018zr,36,3,2,dots,dots,dots,21,40,40,0
19,CXOU J0332,1770,1,dots,0,39,22,4,10,10,0
21,D23H-1,1212,2,dots,27,8,2,dots,dots,dots,dots
50,MAXI J1807+132,14,2,2,dots,dots,dots,12,17,17,0
101,Swift J1644+57,2,19,7,6,14,1,0,779,779,0
107,WINGS J134849.88+263557.5,189,2,dots,0,13,2,2153,3,dots,3
111,XMMSL1 J0740-85,28,4,3,dots,dots,dots,13,13,13,0
1,2XMM J123103.2+110648,0,5,1,dots,dots,dots,dots,dots,dots,dots
2,2XMMi J184725.1-631724,5,3,1,2401,1,dots,1636,5,dots,5
3,3XMM J150052.0+015452,0,5,1,1048,9,dots,2366,15,dots,15
9,ASASSN-15oi,76,2,1,dots,dots,dots,11,49,49,0
12,AT2017eqx,dots,dots,dots,70,2,1,34,10,10,0
16,AT2019dsg,51,2,1,dots,dots,dots,38,17,17,0
23,DES14C1kia,62,2,1,1579,1,dots,56,18,18,0
25,F01004-2237,dots,dots,dots,70,8,1,dots,dots,dots,dots
51,NGC 247,0,9,1,134,1,dots,104,73,dots,73
78,SDSSJ0159,0,1,1,1123,2,dots,dots,dots,dots,dots
80,SDSSJ0952,dots,dots,dots,0,3,1,2627,2,dots,2
81,SDSSJ1201+30,12,3,1,dots,dots,dots,10,10,10,0
82,SDSSJ1311,dots,dots,dots,0,4,1,dots,dots,dots,dots
102,Swift J2058+05,177,3,dots,26,4,1,0,32,32,0
109,XMMSL1 J061927.1-655311,33,2,1,dots,dots,dots,13,13,13,0
4,3XMM J152130.7+074916,0,1,1,dots,dots,dots,1844,1,dots,1
110,XMMSL1 J063045.9-603110,21,1,1,dots,dots,dots,19,3,3,0
115,ZTF18abxftqm,84,1,1,dots,dots,dots,56,13,13,0
0,2MASX J01190869-3411305,141,2,dots,dots,dots,dots,44,16,16,0
5,3XMM J215022.4-055108,369,3,dots,515,1,dots,dots,dots,dots,dots
6,ASASSN-14ae,110,3,dots,1757,1,dots,2,24,24,0
8,ASASSN-15lh,157,2,dots,151,4,dots,10,128,128,0
11,AT2016ezh,dots,dots,dots,867,3,dots,6,70,70,0
22,D3-13,dots,dots,dots,434,69,dots,dots,dots,dots,dots
24,Dougie,475,2,dots,dots,dots,dots,11,8,8,0
52,NGC 3599,1488,2,dots,2070,1,dots,1649,1,dots,1
55,OGLE16aaa,175,2,dots,dots,dots,dots,33,23,23,0
59,PGC 1185375,dots,dots,dots,218,2,dots,dots,dots,dots,dots
113,XMMSL2 J140446.9-251135,152,2,dots,dots,dots,dots,13,13,13,0

In [89]:
# priority_df['xmm_num_dt_within_100'] = 'textbf{' + str(priority_df['xmm_num_dt_within_100']) + '}'
# priority_df

In [90]:
latex_str = priority_df.to_latex(header=False, index=False)
latex_list = latex_str.split('\n')
new_latex_list = []

for i, line in enumerate(latex_list):
    new_line = []
    # print(i, line)
    line = line.split('&')
    # print(line)
    if i in range(2,len(latex_list)-3):  # get rid of header and footer info
        # print(i, line)
        for j, element in enumerate(line):
            element = element.strip('\\').strip()
            # print(j, element)
            
            if element == 'dots':
                element = '\\dots'
            
            if j in [3,6,9]:
                new_line.append("\\textbf{" + f"{element}" + "} & ")
            
            elif j == 10:
                new_line.append("\\textbf{" + f"{element}" + "} \\\\")    
                
            else:
                new_line.append(f"{element} & ")
                
        new_latex_list.append(new_line)

# print(new_latex_list)

new_latex_string = ""

for strlist in new_latex_list:
    new_latex_string += "".join(strlist) + '\n'

print(new_latex_string)

ASASSN-14li & 14 & 13 & \textbf{3} & 16 & 7 & \textbf{2} & 8 & 114 & \textbf{114} & \textbf{0} \\
AT2018zr & 36 & 3 & \textbf{2} & \dots & \dots & \textbf{\dots} & 21 & 40 & \textbf{40} & \textbf{0} \\
CXOU J0332 & 1770 & 1 & \textbf{\dots} & 0 & 39 & \textbf{22} & 4 & 10 & \textbf{10} & \textbf{0} \\
D23H-1 & 1212 & 2 & \textbf{\dots} & 27 & 8 & \textbf{2} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
MAXI J1807+132 & 14 & 2 & \textbf{2} & \dots & \dots & \textbf{\dots} & 12 & 17 & \textbf{17} & \textbf{0} \\
Swift J1644+57 & 2 & 19 & \textbf{7} & 6 & 14 & \textbf{1} & 0 & 779 & \textbf{779} & \textbf{0} \\
WINGS J134849.88+263557.5 & 189 & 2 & \textbf{\dots} & 0 & 13 & \textbf{2} & 2153 & 3 & \textbf{\dots} & \textbf{3} \\
XMMSL1 J0740-85 & 28 & 4 & \textbf{3} & \dots & \dots & \textbf{\dots} & 13 & 13 & \textbf{13} & \textbf{0} \\
2XMM J123103.2+110648 & 0 & 5 & \textbf{1} & \dots & \dots & \textbf{\dots} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
2XMMi J184725.1-631724 & 5 & 3 & \textbf{1} & 2401 & 1 & \textbf{\dots} & 1636 & 5 & \textbf{\dots} & \textbf{5} \\
3XMM J150052.0+015452 & 0 & 5 & \textbf{1} & 1048 & 9 & \textbf{\dots} & 2366 & 15 & \textbf{\dots} & \textbf{15} \\
ASASSN-15oi & 76 & 2 & \textbf{1} & \dots & \dots & \textbf{\dots} & 11 & 49 & \textbf{49} & \textbf{0} \\
AT2017eqx & \dots & \dots & \textbf{\dots} & 70 & 2 & \textbf{1} & 34 & 10 & \textbf{10} & \textbf{0} \\
AT2019dsg & 51 & 2 & \textbf{1} & \dots & \dots & \textbf{\dots} & 38 & 17 & \textbf{17} & \textbf{0} \\
DES14C1kia & 62 & 2 & \textbf{1} & 1579 & 1 & \textbf{\dots} & 56 & 18 & \textbf{18} & \textbf{0} \\
F01004-2237 & \dots & \dots & \textbf{\dots} & 70 & 8 & \textbf{1} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
NGC 247 & 0 & 9 & \textbf{1} & 134 & 1 & \textbf{\dots} & 104 & 73 & \textbf{\dots} & \textbf{73} \\
SDSSJ0159 & 0 & 1 & \textbf{1} & 1123 & 2 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
SDSSJ0952 & \dots & \dots & \textbf{\dots} & 0 & 3 & \textbf{1} & 2627 & 2 & \textbf{\dots} & \textbf{2} \\
SDSSJ1201+30 & 12 & 3 & \textbf{1} & \dots & \dots & \textbf{\dots} & 10 & 10 & \textbf{10} & \textbf{0} \\
SDSSJ1311 & \dots & \dots & \textbf{\dots} & 0 & 4 & \textbf{1} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
Swift J2058+05 & 177 & 3 & \textbf{\dots} & 26 & 4 & \textbf{1} & 0 & 32 & \textbf{32} & \textbf{0} \\
XMMSL1 J061927.1-655311 & 33 & 2 & \textbf{1} & \dots & \dots & \textbf{\dots} & 13 & 13 & \textbf{13} & \textbf{0} \\
3XMM J152130.7+074916 & 0 & 1 & \textbf{1} & \dots & \dots & \textbf{\dots} & 1844 & 1 & \textbf{\dots} & \textbf{1} \\
XMMSL1 J063045.9-603110 & 21 & 1 & \textbf{1} & \dots & \dots & \textbf{\dots} & 19 & 3 & \textbf{3} & \textbf{0} \\
ZTF18abxftqm & 84 & 1 & \textbf{1} & \dots & \dots & \textbf{\dots} & 56 & 13 & \textbf{13} & \textbf{0} \\
2MASX J01190869-3411305 & 141 & 2 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & 44 & 16 & \textbf{16} & \textbf{0} \\
3XMM J215022.4-055108 & 369 & 3 & \textbf{\dots} & 515 & 1 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
ASASSN-14ae & 110 & 3 & \textbf{\dots} & 1757 & 1 & \textbf{\dots} & 2 & 24 & \textbf{24} & \textbf{0} \\
ASASSN-15lh & 157 & 2 & \textbf{\dots} & 151 & 4 & \textbf{\dots} & 10 & 128 & \textbf{128} & \textbf{0} \\
AT2016ezh & \dots & \dots & \textbf{\dots} & 867 & 3 & \textbf{\dots} & 6 & 70 & \textbf{70} & \textbf{0} \\
D3-13 & \dots & \dots & \textbf{\dots} & 434 & 69 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
Dougie & 475 & 2 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & 11 & 8 & \textbf{8} & \textbf{0} \\
NGC 3599 & 1488 & 2 & \textbf{\dots} & 2070 & 1 & \textbf{\dots} & 1649 & 1 & \textbf{\dots} & \textbf{1} \\
OGLE16aaa & 175 & 2 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & 33 & 23 & \textbf{23} & \textbf{0} \\
PGC 1185375 & \dots & \dots & \textbf{\dots} & 218 & 2 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & \textbf{\dots} \\
XMMSL2 J140446.9-251135 & 152 & 2 & \textbf{\dots} & \dots & \dots & \textbf{\dots} & 13 & 13 & \textbf{13} & \textbf{0} \\

/var/folders/_h/d0h8vzsj39scjk2c_h8m33cm0000gn/T/ipykernel_5842/2783487442.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex_str = priority_df.to_latex(header=False, index=False)